/// Auto-generated startup code for ATSAMR21E17A
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#include <cstdint>
#include <cstring>

// Linker script symbols
extern uint32_t _sidata;  // Start of .data in flash
extern uint32_t _sdata;   // Start of .data in RAM
extern uint32_t _edata;   // End of .data in RAM
extern uint32_t _sbss;    // Start of .bss
extern uint32_t _ebss;    // End of .bss

// Stack top (defined in linker script)
extern uint32_t _estack;

// User application entry point
extern "C" int main();

// System initialization (weak, can be overridden)
extern "C" void SystemInit() __attribute__((weak));
extern "C" void SystemInit() {}

// Default handler for unhandled interrupts
extern "C" [[noreturn]] void Default_Handler() {
    while (true) {
        // Trap
    }
}

// Interrupt handlers (weak, can be overridden)
extern "C" void PM_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SYSCTRL_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void WDT_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RTC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EIC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void NVMCTRL_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMAC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USB_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EVSYS_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM0_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM1_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM2_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM3_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM4_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SERCOM5_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TCC0_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TCC1_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TCC2_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC3_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC4_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC5_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC6_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC7_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ADC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void AC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DAC_INTREQ_Handler() __attribute__((weak, alias("Default_Handler")));

// Reset Handler - Entry point after reset
extern "C" [[noreturn]] void Reset_Handler() {
    // 1. Copy .data section from Flash to RAM
    uint32_t* src = &_sidata;
    uint32_t* dest = &_sdata;
    while (dest < &_edata) {
        *dest++ = *src++;
    }

    // 2. Zero out .bss section
    dest = &_sbss;
    while (dest < &_ebss) {
        *dest++ = 0;
    }

    // 3. Call system initialization
    SystemInit();

    // 4. Call static constructors
    extern void (*__init_array_start[])();
    extern void (*__init_array_end[])();
    for (auto ctor = __init_array_start; ctor < __init_array_end; ++ctor) {
        (*ctor)();
    }

    // 5. Call main
    main();

    // 6. If main returns, loop forever
    while (true) {}
}

// Vector table
__attribute__((section(".isr_vector"), used)) void (*const vector_table[])() = {
    reinterpret_cast<void (*)()>(&_estack),  // Initial stack pointer
    Reset_Handler,                           // Reset handler
    PM_INTREQ_Handler,                       // IRQ 0: PM_INTREQ
    SYSCTRL_INTREQ_Handler,                  // IRQ 1: SYSCTRL_INTREQ
    WDT_INTREQ_Handler,                      // IRQ 2: WDT_INTREQ
    RTC_INTREQ_Handler,                      // IRQ 3: RTC_INTREQ
    EIC_INTREQ_Handler,                      // IRQ 4: EIC_INTREQ
    NVMCTRL_INTREQ_Handler,                  // IRQ 5: NVMCTRL_INTREQ
    DMAC_INTREQ_Handler,                     // IRQ 6: DMAC_INTREQ
    USB_INTREQ_Handler,                      // IRQ 7: USB_INTREQ
    EVSYS_INTREQ_Handler,                    // IRQ 8: EVSYS_INTREQ
    SERCOM0_INTREQ_Handler,                  // IRQ 9: SERCOM0_INTREQ
    SERCOM1_INTREQ_Handler,                  // IRQ 10: SERCOM1_INTREQ
    SERCOM2_INTREQ_Handler,                  // IRQ 11: SERCOM2_INTREQ
    SERCOM3_INTREQ_Handler,                  // IRQ 12: SERCOM3_INTREQ
    SERCOM4_INTREQ_Handler,                  // IRQ 13: SERCOM4_INTREQ
    SERCOM5_INTREQ_Handler,                  // IRQ 14: SERCOM5_INTREQ
    TCC0_INTREQ_Handler,                     // IRQ 15: TCC0_INTREQ
    TCC1_INTREQ_Handler,                     // IRQ 16: TCC1_INTREQ
    TCC2_INTREQ_Handler,                     // IRQ 17: TCC2_INTREQ
    TC3_INTREQ_Handler,                      // IRQ 18: TC3_INTREQ
    TC4_INTREQ_Handler,                      // IRQ 19: TC4_INTREQ
    TC5_INTREQ_Handler,                      // IRQ 20: TC5_INTREQ
    TC6_INTREQ_Handler,                      // IRQ 21: TC6_INTREQ
    TC7_INTREQ_Handler,                      // IRQ 22: TC7_INTREQ
    ADC_INTREQ_Handler,                      // IRQ 23: ADC_INTREQ
    AC_INTREQ_Handler,                       // IRQ 24: AC_INTREQ
    DAC_INTREQ_Handler,                      // IRQ 25: DAC_INTREQ
};
