/// Auto-generated peripheral definitions for STM32G484xx
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_STM32G484XX_PERIPHERALS_HPP
#define UCORE_GENERATED_STM32G484XX_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::stm32g484xx {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::stm32g484xx

#endif  // ALLOY_GENERATED_STM32G484XX_PERIPHERALS_HPP
