/// Auto-generated bit field definitions for NVIC_STIR
/// Device: STM32F407
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "bitfield_utils.hpp"

namespace alloy::hal::st::stm32f4::stm32f407::nvic_stir {

using namespace alloy::hal::bitfields;

// ============================================================================
// NVIC_STIR Bit Field Definitions
// ============================================================================

/// STIR - Software trigger interrupt
          register
namespace stir {
    /// Software generated interrupt
              ID
    /// Position: 0, Width: 9
    using INTID = BitField<0, 9>;
    constexpr uint32_t INTID_Pos = 0;
    constexpr uint32_t INTID_Msk = INTID::mask;

}  // namespace stir

}  // namespace alloy::hal::st::stm32f4::stm32f407::nvic_stir
