/// Auto-generated bit field definitions for SCB_ACTRL
/// Device: STM32F407
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::st::stm32f4::stm32f407::scb_actrl {

using namespace alloy::hal::bitfields;

// ============================================================================
// SCB_ACTRL Bit Field Definitions
// ============================================================================

/// ACTRL - Auxiliary control register
namespace actrl {
    /// DISMCYCINT
    /// Position: 0, Width: 1
    using DISMCYCINT = BitField<0, 1>;
    constexpr uint32_t DISMCYCINT_Pos = 0;
    constexpr uint32_t DISMCYCINT_Msk = DISMCYCINT::mask;

    /// DISDEFWBUF
    /// Position: 1, Width: 1
    using DISDEFWBUF = BitField<1, 1>;
    constexpr uint32_t DISDEFWBUF_Pos = 1;
    constexpr uint32_t DISDEFWBUF_Msk = DISDEFWBUF::mask;

    /// DISFOLD
    /// Position: 2, Width: 1
    using DISFOLD = BitField<2, 1>;
    constexpr uint32_t DISFOLD_Pos = 2;
    constexpr uint32_t DISFOLD_Msk = DISFOLD::mask;

    /// DISFPCA
    /// Position: 8, Width: 1
    using DISFPCA = BitField<8, 1>;
    constexpr uint32_t DISFPCA_Pos = 8;
    constexpr uint32_t DISFPCA_Msk = DISFPCA::mask;

    /// DISOOFP
    /// Position: 9, Width: 1
    using DISOOFP = BitField<9, 1>;
    constexpr uint32_t DISOOFP_Pos = 9;
    constexpr uint32_t DISOOFP_Msk = DISOOFP::mask;

}  // namespace actrl

}  // namespace alloy::hal::st::stm32f4::stm32f407::scb_actrl
