/// Auto-generated bit field definitions for AES
/// Device: ATSAMV71J21
/// Vendor: Microchip Technology
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::atmel::samv71::atsamv71j21::aes {

using namespace alloy::hal::bitfields;

// ============================================================================
// AES Bit Field Definitions
// ============================================================================

/// CR - Control Register
namespace cr {
    /// Start Processing
    /// Position: 0, Width: 1
    using START = BitField<0, 1>;
    constexpr uint32_t START_Pos = 0;
    constexpr uint32_t START_Msk = START::mask;

    /// Software Reset
    /// Position: 8, Width: 1
    using SWRST = BitField<8, 1>;
    constexpr uint32_t SWRST_Pos = 8;
    constexpr uint32_t SWRST_Msk = SWRST::mask;

    /// Random Number Generator Seed Loading
    /// Position: 16, Width: 1
    using LOADSEED = BitField<16, 1>;
    constexpr uint32_t LOADSEED_Pos = 16;
    constexpr uint32_t LOADSEED_Msk = LOADSEED::mask;

}  // namespace cr

/// MR - Mode Register
namespace mr {
    /// Processing Mode
    /// Position: 0, Width: 1
    using CIPHER = BitField<0, 1>;
    constexpr uint32_t CIPHER_Pos = 0;
    constexpr uint32_t CIPHER_Msk = CIPHER::mask;

    /// GCM Automatic Tag Generation Enable
    /// Position: 1, Width: 1
    using GTAGEN = BitField<1, 1>;
    constexpr uint32_t GTAGEN_Pos = 1;
    constexpr uint32_t GTAGEN_Msk = GTAGEN::mask;

    /// Dual Input Buffer
    /// Position: 3, Width: 1
    using DUALBUFF = BitField<3, 1>;
    constexpr uint32_t DUALBUFF_Pos = 3;
    constexpr uint32_t DUALBUFF_Msk = DUALBUFF::mask;
    /// Enumerated values for DUALBUFF
    namespace dualbuff {
        constexpr uint32_t INACTIVE = 0;
        constexpr uint32_t ACTIVE = 1;
    }

    /// Processing Delay
    /// Position: 4, Width: 4
    using PROCDLY = BitField<4, 4>;
    constexpr uint32_t PROCDLY_Pos = 4;
    constexpr uint32_t PROCDLY_Msk = PROCDLY::mask;

    /// Start Mode
    /// Position: 8, Width: 2
    using SMOD = BitField<8, 2>;
    constexpr uint32_t SMOD_Pos = 8;
    constexpr uint32_t SMOD_Msk = SMOD::mask;
    /// Enumerated values for SMOD
    namespace smod {
        constexpr uint32_t MANUAL_START = 0;
        constexpr uint32_t AUTO_START = 1;
        constexpr uint32_t IDATAR0_START = 2;
    }

    /// Key Size
    /// Position: 10, Width: 2
    using KEYSIZE = BitField<10, 2>;
    constexpr uint32_t KEYSIZE_Pos = 10;
    constexpr uint32_t KEYSIZE_Msk = KEYSIZE::mask;
    /// Enumerated values for KEYSIZE
    namespace keysize {
        constexpr uint32_t AES128 = 0;
        constexpr uint32_t AES192 = 1;
        constexpr uint32_t AES256 = 2;
    }

    /// Operating Mode
    /// Position: 12, Width: 3
    using OPMOD = BitField<12, 3>;
    constexpr uint32_t OPMOD_Pos = 12;
    constexpr uint32_t OPMOD_Msk = OPMOD::mask;
    /// Enumerated values for OPMOD
    namespace opmod {
        constexpr uint32_t ECB = 0;
        constexpr uint32_t CBC = 1;
        constexpr uint32_t OFB = 2;
        constexpr uint32_t CFB = 3;
        constexpr uint32_t CTR = 4;
        constexpr uint32_t GCM = 5;
    }

    /// Last Output Data Mode
    /// Position: 15, Width: 1
    using LOD = BitField<15, 1>;
    constexpr uint32_t LOD_Pos = 15;
    constexpr uint32_t LOD_Msk = LOD::mask;

    /// Cipher Feedback Data Size
    /// Position: 16, Width: 3
    using CFBS = BitField<16, 3>;
    constexpr uint32_t CFBS_Pos = 16;
    constexpr uint32_t CFBS_Msk = CFBS::mask;
    /// Enumerated values for CFBS
    namespace cfbs {
        constexpr uint32_t SIZE_128BIT = 0;
        constexpr uint32_t SIZE_64BIT = 1;
        constexpr uint32_t SIZE_32BIT = 2;
        constexpr uint32_t SIZE_16BIT = 3;
        constexpr uint32_t SIZE_8BIT = 4;
    }

    /// Countermeasure Key
    /// Position: 20, Width: 4
    using CKEY = BitField<20, 4>;
    constexpr uint32_t CKEY_Pos = 20;
    constexpr uint32_t CKEY_Msk = CKEY::mask;
    /// Enumerated values for CKEY
    namespace ckey {
        constexpr uint32_t PASSWD = 14;
    }

    /// Countermeasure Type 1
    /// Position: 24, Width: 1
    using CMTYP1 = BitField<24, 1>;
    constexpr uint32_t CMTYP1_Pos = 24;
    constexpr uint32_t CMTYP1_Msk = CMTYP1::mask;
    /// Enumerated values for CMTYP1
    namespace cmtyp1 {
        constexpr uint32_t NOPROT_EXTKEY = 0;
        constexpr uint32_t PROT_EXTKEY = 1;
    }

    /// Countermeasure Type 2
    /// Position: 25, Width: 1
    using CMTYP2 = BitField<25, 1>;
    constexpr uint32_t CMTYP2_Pos = 25;
    constexpr uint32_t CMTYP2_Msk = CMTYP2::mask;
    /// Enumerated values for CMTYP2
    namespace cmtyp2 {
        constexpr uint32_t NO_PAUSE = 0;
        constexpr uint32_t PAUSE = 1;
    }

    /// Countermeasure Type 3
    /// Position: 26, Width: 1
    using CMTYP3 = BitField<26, 1>;
    constexpr uint32_t CMTYP3_Pos = 26;
    constexpr uint32_t CMTYP3_Msk = CMTYP3::mask;
    /// Enumerated values for CMTYP3
    namespace cmtyp3 {
        constexpr uint32_t NO_DUMMY = 0;
        constexpr uint32_t DUMMY = 1;
    }

    /// Countermeasure Type 4
    /// Position: 27, Width: 1
    using CMTYP4 = BitField<27, 1>;
    constexpr uint32_t CMTYP4_Pos = 27;
    constexpr uint32_t CMTYP4_Msk = CMTYP4::mask;
    /// Enumerated values for CMTYP4
    namespace cmtyp4 {
        constexpr uint32_t NO_RESTART = 0;
        constexpr uint32_t RESTART = 1;
    }

    /// Countermeasure Type 5
    /// Position: 28, Width: 1
    using CMTYP5 = BitField<28, 1>;
    constexpr uint32_t CMTYP5_Pos = 28;
    constexpr uint32_t CMTYP5_Msk = CMTYP5::mask;
    /// Enumerated values for CMTYP5
    namespace cmtyp5 {
        constexpr uint32_t NO_ADDACCESS = 0;
        constexpr uint32_t ADDACCESS = 1;
    }

    /// Countermeasure Type 6
    /// Position: 29, Width: 1
    using CMTYP6 = BitField<29, 1>;
    constexpr uint32_t CMTYP6_Pos = 29;
    constexpr uint32_t CMTYP6_Msk = CMTYP6::mask;
    /// Enumerated values for CMTYP6
    namespace cmtyp6 {
        constexpr uint32_t NO_IDLECURRENT = 0;
        constexpr uint32_t IDLECURRENT = 1;
    }

}  // namespace mr

/// IER - Interrupt Enable Register
namespace ier {
    /// Data Ready Interrupt Enable
    /// Position: 0, Width: 1
    using DATRDY = BitField<0, 1>;
    constexpr uint32_t DATRDY_Pos = 0;
    constexpr uint32_t DATRDY_Msk = DATRDY::mask;

    /// Unspecified Register Access Detection Interrupt Enable
    /// Position: 8, Width: 1
    using URAD = BitField<8, 1>;
    constexpr uint32_t URAD_Pos = 8;
    constexpr uint32_t URAD_Msk = URAD::mask;

    /// GCM Tag Ready Interrupt Enable
    /// Position: 16, Width: 1
    using TAGRDY = BitField<16, 1>;
    constexpr uint32_t TAGRDY_Pos = 16;
    constexpr uint32_t TAGRDY_Msk = TAGRDY::mask;

}  // namespace ier

/// IDR - Interrupt Disable Register
namespace idr {
    /// Data Ready Interrupt Disable
    /// Position: 0, Width: 1
    using DATRDY = BitField<0, 1>;
    constexpr uint32_t DATRDY_Pos = 0;
    constexpr uint32_t DATRDY_Msk = DATRDY::mask;

    /// Unspecified Register Access Detection Interrupt Disable
    /// Position: 8, Width: 1
    using URAD = BitField<8, 1>;
    constexpr uint32_t URAD_Pos = 8;
    constexpr uint32_t URAD_Msk = URAD::mask;

    /// GCM Tag Ready Interrupt Disable
    /// Position: 16, Width: 1
    using TAGRDY = BitField<16, 1>;
    constexpr uint32_t TAGRDY_Pos = 16;
    constexpr uint32_t TAGRDY_Msk = TAGRDY::mask;

}  // namespace idr

/// IMR - Interrupt Mask Register
namespace imr {
    /// Data Ready Interrupt Mask
    /// Position: 0, Width: 1
    using DATRDY = BitField<0, 1>;
    constexpr uint32_t DATRDY_Pos = 0;
    constexpr uint32_t DATRDY_Msk = DATRDY::mask;

    /// Unspecified Register Access Detection Interrupt Mask
    /// Position: 8, Width: 1
    using URAD = BitField<8, 1>;
    constexpr uint32_t URAD_Pos = 8;
    constexpr uint32_t URAD_Msk = URAD::mask;

    /// GCM Tag Ready Interrupt Mask
    /// Position: 16, Width: 1
    using TAGRDY = BitField<16, 1>;
    constexpr uint32_t TAGRDY_Pos = 16;
    constexpr uint32_t TAGRDY_Msk = TAGRDY::mask;

}  // namespace imr

/// ISR - Interrupt Status Register
namespace isr {
    /// Data Ready (cleared by setting bit START or bit SWRST in AES_CR or by reading AES_ODATARx)
    /// Position: 0, Width: 1
    using DATRDY = BitField<0, 1>;
    constexpr uint32_t DATRDY_Pos = 0;
    constexpr uint32_t DATRDY_Msk = DATRDY::mask;

    /// Unspecified Register Access Detection Status (cleared by writing SWRST in AES_CR)
    /// Position: 8, Width: 1
    using URAD = BitField<8, 1>;
    constexpr uint32_t URAD_Pos = 8;
    constexpr uint32_t URAD_Msk = URAD::mask;

    /// Unspecified Register Access (cleared by writing SWRST in AES_CR)
    /// Position: 12, Width: 4
    using URAT = BitField<12, 4>;
    constexpr uint32_t URAT_Pos = 12;
    constexpr uint32_t URAT_Msk = URAT::mask;
    /// Enumerated values for URAT
    namespace urat {
        constexpr uint32_t IDR_WR_PROCESSING = 0;
        constexpr uint32_t ODR_RD_PROCESSING = 1;
        constexpr uint32_t MR_WR_PROCESSING = 2;
        constexpr uint32_t ODR_RD_SUBKGEN = 3;
        constexpr uint32_t MR_WR_SUBKGEN = 4;
        constexpr uint32_t WOR_RD_ACCESS = 5;
    }

    /// GCM Tag Ready
    /// Position: 16, Width: 1
    using TAGRDY = BitField<16, 1>;
    constexpr uint32_t TAGRDY_Pos = 16;
    constexpr uint32_t TAGRDY_Msk = TAGRDY::mask;

}  // namespace isr

/// KEYWR[8] - Key Word Register 0
namespace keywr[8] {
    /// Key Word
    /// Position: 0, Width: 32
    using KEYW = BitField<0, 32>;
    constexpr uint32_t KEYW_Pos = 0;
    constexpr uint32_t KEYW_Msk = KEYW::mask;

}  // namespace keywr[8]

/// IDATAR[4] - Input Data Register 0
namespace idatar[4] {
    /// Input Data Word
    /// Position: 0, Width: 32
    using IDATA = BitField<0, 32>;
    constexpr uint32_t IDATA_Pos = 0;
    constexpr uint32_t IDATA_Msk = IDATA::mask;

}  // namespace idatar[4]

/// ODATAR[4] - Output Data Register 0
namespace odatar[4] {
    /// Output Data
    /// Position: 0, Width: 32
    using ODATA = BitField<0, 32>;
    constexpr uint32_t ODATA_Pos = 0;
    constexpr uint32_t ODATA_Msk = ODATA::mask;

}  // namespace odatar[4]

/// IVR[4] - Initialization Vector Register 0
namespace ivr[4] {
    /// Initialization Vector
    /// Position: 0, Width: 32
    using IV = BitField<0, 32>;
    constexpr uint32_t IV_Pos = 0;
    constexpr uint32_t IV_Msk = IV::mask;

}  // namespace ivr[4]

/// AADLENR - Additional Authenticated Data Length Register
namespace aadlenr {
    /// Additional Authenticated Data Length
    /// Position: 0, Width: 32
    using AADLEN = BitField<0, 32>;
    constexpr uint32_t AADLEN_Pos = 0;
    constexpr uint32_t AADLEN_Msk = AADLEN::mask;

}  // namespace aadlenr

/// CLENR - Plaintext/Ciphertext Length Register
namespace clenr {
    /// Plaintext/Ciphertext Length
    /// Position: 0, Width: 32
    using CLEN = BitField<0, 32>;
    constexpr uint32_t CLEN_Pos = 0;
    constexpr uint32_t CLEN_Msk = CLEN::mask;

}  // namespace clenr

/// GHASHR[4] - GCM Intermediate Hash Word Register 0
namespace ghashr[4] {
    /// Intermediate GCM Hash Word x
    /// Position: 0, Width: 32
    using GHASH = BitField<0, 32>;
    constexpr uint32_t GHASH_Pos = 0;
    constexpr uint32_t GHASH_Msk = GHASH::mask;

}  // namespace ghashr[4]

/// TAGR[4] - GCM Authentication Tag Word Register 0
namespace tagr[4] {
    /// GCM Authentication Tag x
    /// Position: 0, Width: 32
    using TAG = BitField<0, 32>;
    constexpr uint32_t TAG_Pos = 0;
    constexpr uint32_t TAG_Msk = TAG::mask;

}  // namespace tagr[4]

/// CTRR - GCM Encryption Counter Value Register
namespace ctrr {
    /// GCM Encryption Counter
    /// Position: 0, Width: 32
    using CTR = BitField<0, 32>;
    constexpr uint32_t CTR_Pos = 0;
    constexpr uint32_t CTR_Msk = CTR::mask;

}  // namespace ctrr

/// GCMHR[4] - GCM H Word Register 0
namespace gcmhr[4] {
    /// GCM H Word x
    /// Position: 0, Width: 32
    using H = BitField<0, 32>;
    constexpr uint32_t H_Pos = 0;
    constexpr uint32_t H_Msk = H::mask;

}  // namespace gcmhr[4]

/// VERSION - Version Register
namespace version {
    /// Version of the Hardware Module
    /// Position: 0, Width: 12
    using VERSION = BitField<0, 12>;
    constexpr uint32_t VERSION_Pos = 0;
    constexpr uint32_t VERSION_Msk = VERSION::mask;

    /// Metal Fix Number
    /// Position: 16, Width: 3
    using MFN = BitField<16, 3>;
    constexpr uint32_t MFN_Pos = 16;
    constexpr uint32_t MFN_Msk = MFN::mask;

}  // namespace version

}  // namespace alloy::hal::atmel::samv71::atsamv71j21::aes
