/// Auto-generated register definitions for LOCKBIT
/// Device: ATSAMV71Q19
/// Vendor: Microchip Technology
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::atmel::samv71::atsamv71q19::lockbit {

// ============================================================================
// LOCKBIT - Peripheral Registers
// Base Address: 0x00000000
// ============================================================================

/// LOCKBIT Register Structure
struct LOCKBIT_Registers {

    /// Lock Bits
    /// Offset: 0x0000
    volatile uint32_t LOCKBIT;
};

static_assert(sizeof(LOCKBIT_Registers) >= 4, "LOCKBIT_Registers size mismatch");

/// LOCKBIT peripheral instance
constexpr LOCKBIT_Registers* LOCKBIT = 
    reinterpret_cast<LOCKBIT_Registers*>(0x00000000);

}  // namespace alloy::hal::atmel::samv71::atsamv71q19::lockbit
