/// Auto-generated peripheral definitions for ATSAM3N1A
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_ATSAM3N1A_PERIPHERALS_HPP
#define UCORE_GENERATED_ATSAM3N1A_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::atsam3n1a {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::atsam3n1a

#endif  // ALLOY_GENERATED_ATSAM3N1A_PERIPHERALS_HPP
