"""Emit the linker script from the chip's memory map.

The old database shipped family-max sizes that would have produced broken
linker scripts; the alloy-devices plausibility lints run before generation,
so by the time we get here the sizes have been checked against the part
number.
"""

from __future__ import annotations

from typing import Any

from .common import EmitError

_BANNER = "/* GENERATED by alloy — DO NOT EDIT (fix the data or the emitter and regenerate) */\n"


def app_regions(chip: dict[str, Any],
                arch_ns: str = "cortex_m") -> dict[str, dict[str, Any] | None]:
    """The memories the app's code and data are actually linked into.

    `alloy size` measures against these, so it must not guess: on Cortex-M the
    script below takes the first flash and the first ram, while the Xtensa one
    places .text in IROM and .data/.bss in DRAM — picking "the first ram" there
    would report the 2 KiB vector window as the whole of RAM.
    """
    memories = chip.get("memories") or []
    if arch_ns == "xtensa":
        by_name = {m["name"]: m for m in memories}
        return {"code": by_name.get("irom"), "data": by_name.get("dram")}
    return {
        "code": next((m for m in memories if m.get("kind") == "flash"), None),
        "data": next((m for m in memories if m.get("kind") == "ram"), None),
    }


def emit_linker_script(chip: dict[str, Any], arch_ns: str = "cortex_m",
                       layout: str = "flash", flash_reserved: int = 0,
                       flash_window: tuple[int, int] | None = None) -> str:
    if arch_ns == "xtensa":
        if layout == "ram":
            raise EmitError("run-from-RAM (--ram) is not supported on xtensa (the "
                            "resident bootloader owns the boot flow)")
        return _emit_xtensa_linker(chip)
    flash = next((m for m in chip["memories"] if m["kind"] == "flash"), None)
    ram = next((m for m in chip["memories"] if m["kind"] == "ram"), None)
    if flash is None or ram is None:
        raise EmitError("chip data must declare flash and ram memories")

    # Board roles (nvm/fs) reserve flash at the TOP; shrink the app's FLASH
    # window by that much so an oversized app fails the LINK ("region FLASH
    # overflowed") instead of overlapping the region and being self-erased on the
    # first mount/format at runtime. flash_reserved is 0 for the per-chip smoke
    # (no board) and for boards with no flash-backed role.
    flash_len = int(flash["size"]) - flash_reserved
    if flash_len <= 0:
        raise EmitError(f"chip {chip['part']}: board reserves {flash_reserved} B of flash "
                        f"but the part only has {flash['size']} B")
    reserved_note = (f"\n/* Top {flash_reserved} B reserved for board nvm/fs roles — "
                     f"fenced off below. */" if flash_reserved else "")

    # A/B slot build: link into the given window (bootloader region, or a slot at
    # its app offset) instead of the whole flash. The top-of-flash nvm/fs reserve
    # can't coexist with the slot layout (the boot-state store owns those pages) —
    # refuse loudly rather than let the two carve the same pages.
    flash_origin = flash["base"]
    if flash_window is not None:
        if flash_reserved:
            raise EmitError(
                f"chip {chip['part']}: a board with flash-backed nvm/fs roles can't "
                f"use A/B slots — both claim the top of flash")
        flash_origin, flash_len = f"{flash_window[0]:#010x}", flash_window[1]
        reserved_note = "\n/* A/B slot build: linked into a slot window, not whole flash. */"

    # Run-from-RAM: the debugger loads every section into RAM and starts there —
    # no flash erase, fast iterate, code out of the fastest memory. Code lives in
    # RAM and .data/.fastcode load in place (LMA == VMA), so the startup copies
    # are harmless no-ops. Chips with their own flash boot stub (RP2040 boot2)
    # can't be entered this way.
    if layout == "ram":
        if "boot" in chip:
            raise EmitError("run-from-RAM (--ram) unsupported: this chip boots via a "
                            "flash boot stub (.boot2)")
        code_region = "RAM"
        data_lma = "RAM"
        boot_section = ""
    else:
        code_region = "FLASH"
        data_lma = "FLASH"
        boot_section = ""
        if "boot" in chip:
            boot_section = """    .boot2 :
    {
        KEEP(*(.boot2))
    } > FLASH

"""

    return f"""{_BANNER}/* Chip: {chip['vendor']}/{chip['part']} — layout: {layout} */{reserved_note}

MEMORY
{{
    FLASH (rx)  : ORIGIN = {flash_origin}, LENGTH = {flash_len}
    RAM   (rwx) : ORIGIN = {ram['base']}, LENGTH = {ram['size']}
}}

ENTRY(Reset_Handler)

_estack = ORIGIN(RAM) + LENGTH(RAM);

/* Minimum stack reserved below _estack (overridable via --defsym). The link
   fails loudly if the static footprint leaves less than this — see ._heap_stack. */
_Min_Stack_Size = DEFINED(_Min_Stack_Size) ? _Min_Stack_Size : 0x800;

SECTIONS
{{
{boot_section}    .isr_vector :
    {{
        KEEP(*(.isr_vector))
    }} > {code_region}

    .text :
    {{
        *(.text*)
        *(.rodata*)
        . = ALIGN(4);
    }} > {code_region}

    .init_array :
    {{
        __preinit_array_start = .;
        KEEP(*(.preinit_array*))
        __preinit_array_end = .;
        __init_array_start = .;
        KEEP(*(SORT(.init_array.*)))
        KEEP(*(.init_array*))
        __init_array_end = .;
    }} > {code_region}

    .fini_array :
    {{
        __fini_array_start = .;
        KEEP(*(SORT(.fini_array.*)))
        KEEP(*(.fini_array*))
        __fini_array_end = .;
    }} > {code_region}

    _sidata = LOADADDR(.data);

    .data :
    {{
        . = ALIGN(4);
        _sdata = .;
        *(.data*)
        . = ALIGN(4);
        _edata = .;
    }} > RAM AT> {data_lma}

    /* Hot code (ALLOY_FASTCODE) executed from RAM: no flash wait states. Loaded
       from flash and copied to RAM by the startup, exactly like .data. Empty (no
       cost) unless a function opts in. */
    _sifastcode = LOADADDR(.fastcode);

    .fastcode :
    {{
        . = ALIGN(4);
        _sfastcode = .;
        *(.fastcode*)
        . = ALIGN(4);
        _efastcode = .;
    }} > RAM AT> {data_lma}

    .bss :
    {{
        . = ALIGN(4);
        _sbss = .;
        *(.bss*)
        *(COMMON)
        . = ALIGN(4);
        _ebss = .;
    }} > RAM

    /* SURVIVES A RESET. RAM keeps its contents across a warm reset, so anything
       here is readable by the code that runs after a crash — which is the whole
       point: a fault handler writes its record, resets, and the next boot reads
       it. Deliberately OUTSIDE .bss so startup's zero-fill cannot erase it, and
       NOLOAD so nothing is copied over it at boot either. */
    .noinit (NOLOAD) :
    {{
        . = ALIGN(4);
        _snoinit = .;
        *(.noinit .noinit.*)
        . = ALIGN(4);
        _enoinit = .;
    }} > RAM

    /* Heapless, but reserve the minimum stack in RAM and expose the heap-base
       symbols newlib's _sbrk expects. Placed `> RAM`, so a static footprint that
       overflows RAM fails the LINK with a readable "region RAM overflowed"
       instead of silently corrupting .bss/stack at runtime (NORTH_STAR goal #4).
       `end`/__heap_start also give a stray malloc/printf a bounded heap and a
       clear error rather than "undefined reference to `end'". */
    ._heap_stack (NOLOAD) :
    {{
        . = ALIGN(8);
        _end = .;
        PROVIDE(end = .);
        PROVIDE(__heap_start = .);
        . = . + _Min_Stack_Size;
        . = ALIGN(8);
    }} > RAM

    /DISCARD/ :
    {{
        *(.ARM.exidx*)
        *(.ARM.extab*)
    }}
}}
"""


def _emit_xtensa_linker(chip: dict[str, Any]) -> str:
    """Classic-ESP32 XIP layout, byte-faithful to the old repo's
    hardware-validated esp32.ld (IROM/DROM MMU-mapped by the resident IDF
    bootloader; +0x10 origins leave room for the image segment header;
    literals placed before text for l32r negative offsets)."""
    mem = {m["name"]: m for m in chip["memories"]}
    for req in ("irom", "drom", "iram", "dram", "vectors"):
        if req not in mem:
            raise EmitError(f"xtensa linker needs memory '{req}' in chip data")

    return f"""{_BANNER}/* Chip: {chip['vendor']}/{chip['part']} — XIP app under resident 2nd-stage bootloader */

ENTRY(call_start_cpu0)

MEMORY
{{
    DROM (r)   : ORIGIN = {mem['drom']['base']}, LENGTH = {mem['drom']['size']}
    IROM (rx)  : ORIGIN = {mem['irom']['base']}, LENGTH = {mem['irom']['size']}
    VECTORS (rx) : ORIGIN = {mem['vectors']['base']}, LENGTH = {mem['vectors']['size']}
    IRAM (rwx) : ORIGIN = {mem['iram']['base']}, LENGTH = {mem['iram']['size']}
    DRAM (rw)  : ORIGIN = {mem['dram']['base']}, LENGTH = {mem['dram']['size']}
}}

_stack_top = ORIGIN(DRAM) + LENGTH(DRAM);

SECTIONS
{{
    /* XEA2 relocatable vector table + level-1 handlers: 1 KiB-aligned,
     * loaded to IRAM by the resident bootloader, pointed at by VECBASE. */
    .alloy.vectors : ALIGN(1024)
    {{
        KEEP(*(.alloy.vectors))
    }} > VECTORS

    .rodata : ALIGN(4)
    {{
        *(.rodata .rodata.*)
        *(.rodata1)
        . = ALIGN(4);
    }} > DROM

    .text : ALIGN(4)
    {{
        /* Literal pools must precede their l32r users */
        *(.literal .literal.*)
        *(.text .text.*)
        . = ALIGN(4);
    }} > IROM

    .init_array : ALIGN(4)
    {{
        __preinit_array_start = .;
        KEEP(*(.preinit_array*))
        __preinit_array_end = .;
        __init_array_start = .;
        KEEP(*(SORT(.init_array.*)))
        KEEP(*(.init_array*))
        __init_array_end = .;
        __fini_array_start = .;
        __fini_array_end = .;
    }} > IROM

    /* No AT> flash LMA and no _sidata on xtensa: esptool images sections
     * by VMA and the resident bootloader loads .data straight into DRAM —
     * a flash LMA would be an unloadable trap (see startup.cpp note). */
    .data : ALIGN(4)
    {{
        *(.data .data.*)
        . = ALIGN(4);
    }} > DRAM

    /* ALLOY_FASTCODE runs from IRAM (the ESP32's fast instruction RAM), loaded
       by the resident bootloader by VMA like .data. Empty unless opted into. */
    .fastcode : ALIGN(4)
    {{
        *(.fastcode .fastcode.*)
        . = ALIGN(4);
    }} > IRAM

    .bss (NOLOAD) : ALIGN(4)
    {{
        _sbss = .;
        *(.bss .bss.*)
        *(COMMON)
        . = ALIGN(4);
        _ebss = .;
    }} > DRAM
}}
"""
