/// Auto-generated peripheral definitions for ESP32-S2
/// Generated by Alloy Code Generator from CMSIS-SVD
///
/// Device:  ESP32-S2
/// Vendor:  ESPRESSIF SYSTEMS (SHANGHAI) CO., LTD.
/// Family:  esp32_s2
///
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_ESP32-S2_PERIPHERALS_HPP
#define ALLOY_GENERATED_ESP32-S2_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::esp32_s2 {

// ============================================================================
// PERIPHERAL BASE ADDRESSES
// ============================================================================

namespace peripherals {
    constexpr uintptr_t UART0                = 0x3F400000;  // UART (Universal Asynchronous Receiver-Transmitter) Controller 0
    constexpr uintptr_t SPI1                 = 0x3F402000;  // SPI (Serial Peripheral Interface) Controller 1
    constexpr uintptr_t SPI0                 = 0x3F403000;  // SPI (Serial Peripheral Interface) Controller 0
    constexpr uintptr_t GPIO                 = 0x3F404000;  // General Purpose Input/Output
    constexpr uintptr_t GPIO_SD              = 0x3F404F00;  // Sigma-Delta Modulation
    constexpr uintptr_t RTC_CNTL             = 0x3F408000;  // Real-Time Clock Control
    constexpr uintptr_t RTC_IO               = 0x3F408400;  // Low-power Input/Output
    constexpr uintptr_t SENS                 = 0x3F408800;  // SENS Peripheral
    constexpr uintptr_t RTC_I2C              = 0x3F408C00;  // Low-power I2C (Inter-Integrated Circuit) Controller
    constexpr uintptr_t IO_MUX               = 0x3F409000;  // Input/Output Multiplexer
    constexpr uintptr_t I2S0                 = 0x3F40F000;  // I2S (Inter-IC Sound) Controller 0
    constexpr uintptr_t UART1                = 0x3F410000;  // UART (Universal Asynchronous Receiver-Transmitter) Controller 1
    constexpr uintptr_t I2C0                 = 0x3F413000;  // I2C (Inter-Integrated Circuit) Controller 0
    constexpr uintptr_t UHCI0                = 0x3F414000;  // Universal Host Controller Interface 0
    constexpr uintptr_t RMT                  = 0x3F416000;  // Remote Control
    constexpr uintptr_t PCNT                 = 0x3F417000;  // Pulse Count Controller
    constexpr uintptr_t LEDC                 = 0x3F419000;  // LED Control PWM (Pulse Width Modulation)
    constexpr uintptr_t EFUSE                = 0x3F41A000;  // eFuse Controller
    constexpr uintptr_t BB                   = 0x3F41D000;  // BB Peripheral
    constexpr uintptr_t TIMG0                = 0x3F41F000;  // Timer Group 0
    constexpr uintptr_t TIMG1                = 0x3F420000;  // Timer Group 1
    constexpr uintptr_t SYSTIMER             = 0x3F423000;  // System Timer
    constexpr uintptr_t SPI2                 = 0x3F424000;  // SPI (Serial Peripheral Interface) Controller 2
    constexpr uintptr_t SPI3                 = 0x3F425000;  // SPI (Serial Peripheral Interface) Controller 3
    constexpr uintptr_t SYSCON               = 0x3F426000;  // SYSCON Peripheral
    constexpr uintptr_t I2C1                 = 0x3F427000;  // I2C (Inter-Integrated Circuit) Controller 1
    constexpr uintptr_t TWAI0                = 0x3F42B000;  // Two-Wire Automotive Interface
    constexpr uintptr_t SPI4                 = 0x3F437000;  // SPI (Serial Peripheral Interface) Controller 4
    constexpr uintptr_t USB_WRAP             = 0x3F439000;  // USB_WRAP Peripheral
    constexpr uintptr_t APB_SARADC           = 0x3F440000;  // SAR (Successive Approximation Register) Analog-to-Digital Converter
    constexpr uintptr_t SYSTEM               = 0x3F4C0000;  // System Configuration Registers
    constexpr uintptr_t PMS                  = 0x3F4C1000;  // Permissions Controller
    constexpr uintptr_t INTERRUPT_CORE0      = 0x3F4C2000;  // Interrupt Controller (Core 0)
    constexpr uintptr_t DEDICATED_GPIO       = 0x3F4CF000;  // DEDICATED_GPIO Peripheral
    constexpr uintptr_t RNG                  = 0x60035000;  // Hardware Random Number Generator
    constexpr uintptr_t AES                  = 0x6003A000;  // AES (Advanced Encryption Standard) Accelerator
    constexpr uintptr_t XTS_AES              = 0x6003A100;  // XTS-AES-128 Flash Encryption
    constexpr uintptr_t SHA                  = 0x6003B000;  // SHA (Secure Hash Algorithm) Accelerator
    constexpr uintptr_t RSA                  = 0x6003C000;  // RSA (Rivest Shamir Adleman) Accelerator
    constexpr uintptr_t DS                   = 0x6003D000;  // Digital Signature
    constexpr uintptr_t HMAC                 = 0x6003E000;  // HMAC (Hash-based Message Authentication Code) Accelerator
    constexpr uintptr_t USB0                 = 0x60080000;  // USB OTG (On-The-Go)
    constexpr uintptr_t EXTMEM               = 0x61800000;  // External Memory
} // namespace peripherals

// ============================================================================
// MEMORY MAP
// ============================================================================

namespace memory {
    // Memory regions not defined in SVD
} // namespace memory

} // namespace alloy::generated::esp32_s2

#endif // ALLOY_GENERATED_ESP32-S2_PERIPHERALS_HPP
