/// Auto-generated peripheral definitions for ATSAM4SP32A
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_ATSAM4SP32A_PERIPHERALS_HPP
#define ALLOY_GENERATED_ATSAM4SP32A_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::atsam4sp32a {

/// Basic peripheral base addresses
namespace peripherals {
    // Peripheral addresses will be added here
    // This is a minimal implementation
}

} // namespace alloy::generated::atsam4sp32a

#endif // ALLOY_GENERATED_ATSAM4SP32A_PERIPHERALS_HPP
