/// Auto-generated register definitions for COMP
/// Family: stm32g0
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::st::stm32g0::comp {

// ============================================================================
// COMP - Comparator
// Base Address: 0x40010200
// ============================================================================

/// COMP Register Structure
struct COMP_Registers {

    /// Comparator 1 control and status register
    /// Offset: 0x0000
    /// Reset value: 0x00000000
    volatile uint32_t COMP1_CSR;

    /// Comparator 2 control and status register
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    volatile uint32_t COMP2_CSR;

    /// Comparator 2 control and status register
    /// Offset: 0x0008
    /// Reset value: 0x00000000
    volatile uint32_t COMP3_CSR;
};

static_assert(sizeof(COMP_Registers) >= 12, "COMP_Registers size mismatch");

/// COMP peripheral instance
inline COMP_Registers* COMP() {
    return reinterpret_cast<COMP_Registers*>(0x40010200);
}

}  // namespace alloy::hal::st::stm32g0::comp
