/// Auto-generated register definitions for RNG
/// Device: ESP32
/// Vendor: ESPRESSIF SYSTEMS (SHANGHAI) CO., LTD.
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::espressif::esp32::esp32::rng {

// ============================================================================
// RNG - Hardware Random Number Generator
// Base Address: 0x60035000
// ============================================================================

/// RNG Register Structure
struct RNG_Registers {
    uint8_t RESERVED_0000[324]; ///< Reserved

    /// Random number data
    /// Offset: 0x0144
    /// Access: read-only
    volatile uint32_t DATA;
};

static_assert(sizeof(RNG_Registers) >= 328, "RNG_Registers size mismatch");

/// RNG peripheral instance
constexpr RNG_Registers* RNG = 
    reinterpret_cast<RNG_Registers*>(0x60035000);

}  // namespace alloy::hal::espressif::esp32::esp32::rng
