/// Auto-generated register definitions for RTC_I2C
/// Device: ESP32
/// Vendor: ESPRESSIF SYSTEMS (SHANGHAI) CO., LTD.
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::espressif::esp32::esp32::rtc_i2c {

// ============================================================================
// RTC_I2C - Low-power I2C (Inter-Integrated Circuit) Controller
// Base Address: 0x3FF48C00
// ============================================================================

/// RTC_I2C Register Structure
struct RTC_I2C_Registers {

    /// SCL_LOW_PERIOD
    /// Offset: 0x0000
    volatile uint32_t SCL_LOW_PERIOD;

    /// CTRL
    /// Offset: 0x0004
    volatile uint32_t CTRL;

    /// DEBUG_STATUS
    /// Offset: 0x0008
    volatile uint32_t DEBUG_STATUS;

    /// TIMEOUT
    /// Offset: 0x000C
    volatile uint32_t TIMEOUT;

    /// SLAVE_ADDR
    /// Offset: 0x0010
    volatile uint32_t SLAVE_ADDR;
    uint8_t RESERVED_0014[8]; ///< Reserved

    /// DATA
    /// Offset: 0x001C
    volatile uint32_t DATA;

    /// INT_RAW
    /// Offset: 0x0020
    volatile uint32_t INT_RAW;

    /// INT_CLR
    /// Offset: 0x0024
    volatile uint32_t INT_CLR;

    /// INT_EN
    /// Offset: 0x0028
    volatile uint32_t INT_EN;

    /// INT_ST
    /// Offset: 0x002C
    volatile uint32_t INT_ST;

    /// SDA_DUTY
    /// Offset: 0x0030
    volatile uint32_t SDA_DUTY;
    uint8_t RESERVED_0034[4]; ///< Reserved

    /// SCL_HIGH_PERIOD
    /// Offset: 0x0038
    volatile uint32_t SCL_HIGH_PERIOD;
    uint8_t RESERVED_003C[4]; ///< Reserved

    /// SCL_START_PERIOD
    /// Offset: 0x0040
    volatile uint32_t SCL_START_PERIOD;

    /// SCL_STOP_PERIOD
    /// Offset: 0x0044
    volatile uint32_t SCL_STOP_PERIOD;

    /// CMD
    /// Offset: 0x0048
    volatile uint32_t CMD;
};

static_assert(sizeof(RTC_I2C_Registers) >= 76, "RTC_I2C_Registers size mismatch");

/// RTC_I2C peripheral instance
constexpr RTC_I2C_Registers* RTC_I2C = 
    reinterpret_cast<RTC_I2C_Registers*>(0x3FF48C00);

}  // namespace alloy::hal::espressif::esp32::esp32::rtc_i2c
