/// Auto-generated peripheral definitions for STM32G030
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_STM32G030_PERIPHERALS_HPP
#define ALLOY_GENERATED_STM32G030_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::stm32g030 {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace alloy::generated::stm32g030

#endif  // ALLOY_GENERATED_STM32G030_PERIPHERALS_HPP
