/// Auto-generated bit field definitions for HMATRIX
/// Device: ATSAMD21J18A
/// Vendor: Microchip Technology Inc.
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::atmel::samd21::atsamd21j18a::hmatrix {

using namespace alloy::hal::bitfields;

// ============================================================================
// HMATRIX Bit Field Definitions
// ============================================================================

/// SFR[16] - Special Function
namespace sfr[16] {
    /// Special Function Register
    /// Position: 0, Width: 32
    using SFR = BitField<0, 32>;
    constexpr uint32_t SFR_Pos = 0;
    constexpr uint32_t SFR_Msk = SFR::mask;

}  // namespace sfr[16]

}  // namespace alloy::hal::atmel::samd21::atsamd21j18a::hmatrix
