/// Auto-generated peripheral definitions for AT91SAM9G25
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_AT91SAM9G25_PERIPHERALS_HPP
#define ALLOY_GENERATED_AT91SAM9G25_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::at91sam9g25 {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace alloy::generated::at91sam9g25

#endif  // ALLOY_GENERATED_AT91SAM9G25_PERIPHERALS_HPP
