/// Auto-generated bit field definitions for FSMC
/// Family: stm32f1
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>

#include "hal/utils/bitfield.hpp"

namespace alloy::hal::st::stm32f1::fsmc {

using namespace alloy::hal::bitfields;

// ============================================================================
// FSMC Bit Field Definitions
// ============================================================================

/// BCR1 - SRAM/NOR-Flash chip-select control register 1
namespace bcr1 {
/// MBKEN
/// Position: 0, Width: 1
using MBKEN = BitField<0, 1>;
constexpr uint32_t MBKEN_Pos = 0;
constexpr uint32_t MBKEN_Msk = MBKEN::mask;

/// MUXEN
/// Position: 1, Width: 1
using MUXEN = BitField<1, 1>;
constexpr uint32_t MUXEN_Pos = 1;
constexpr uint32_t MUXEN_Msk = MUXEN::mask;

/// MTYP
/// Position: 2, Width: 2
using MTYP = BitField<2, 2>;
constexpr uint32_t MTYP_Pos = 2;
constexpr uint32_t MTYP_Msk = MTYP::mask;

/// MWID
/// Position: 4, Width: 2
using MWID = BitField<4, 2>;
constexpr uint32_t MWID_Pos = 4;
constexpr uint32_t MWID_Msk = MWID::mask;

/// FACCEN
/// Position: 6, Width: 1
using FACCEN = BitField<6, 1>;
constexpr uint32_t FACCEN_Pos = 6;
constexpr uint32_t FACCEN_Msk = FACCEN::mask;

/// BURSTEN
/// Position: 8, Width: 1
using BURSTEN = BitField<8, 1>;
constexpr uint32_t BURSTEN_Pos = 8;
constexpr uint32_t BURSTEN_Msk = BURSTEN::mask;

/// WAITPOL
/// Position: 9, Width: 1
using WAITPOL = BitField<9, 1>;
constexpr uint32_t WAITPOL_Pos = 9;
constexpr uint32_t WAITPOL_Msk = WAITPOL::mask;

/// WAITCFG
/// Position: 11, Width: 1
using WAITCFG = BitField<11, 1>;
constexpr uint32_t WAITCFG_Pos = 11;
constexpr uint32_t WAITCFG_Msk = WAITCFG::mask;

/// WREN
/// Position: 12, Width: 1
using WREN = BitField<12, 1>;
constexpr uint32_t WREN_Pos = 12;
constexpr uint32_t WREN_Msk = WREN::mask;

/// WAITEN
/// Position: 13, Width: 1
using WAITEN = BitField<13, 1>;
constexpr uint32_t WAITEN_Pos = 13;
constexpr uint32_t WAITEN_Msk = WAITEN::mask;

/// EXTMOD
/// Position: 14, Width: 1
using EXTMOD = BitField<14, 1>;
constexpr uint32_t EXTMOD_Pos = 14;
constexpr uint32_t EXTMOD_Msk = EXTMOD::mask;

/// ASYNCWAIT
/// Position: 15, Width: 1
using ASYNCWAIT = BitField<15, 1>;
constexpr uint32_t ASYNCWAIT_Pos = 15;
constexpr uint32_t ASYNCWAIT_Msk = ASYNCWAIT::mask;

/// CBURSTRW
/// Position: 19, Width: 1
using CBURSTRW = BitField<19, 1>;
constexpr uint32_t CBURSTRW_Pos = 19;
constexpr uint32_t CBURSTRW_Msk = CBURSTRW::mask;

}  // namespace bcr1

/// BTR1 - SRAM/NOR-Flash chip-select timing register 1
namespace btr1 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// BUSTURN
/// Position: 16, Width: 4
using BUSTURN = BitField<16, 4>;
constexpr uint32_t BUSTURN_Pos = 16;
constexpr uint32_t BUSTURN_Msk = BUSTURN::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace btr1

/// BCR2 - SRAM/NOR-Flash chip-select control register 2
namespace bcr2 {
/// MBKEN
/// Position: 0, Width: 1
using MBKEN = BitField<0, 1>;
constexpr uint32_t MBKEN_Pos = 0;
constexpr uint32_t MBKEN_Msk = MBKEN::mask;

/// MUXEN
/// Position: 1, Width: 1
using MUXEN = BitField<1, 1>;
constexpr uint32_t MUXEN_Pos = 1;
constexpr uint32_t MUXEN_Msk = MUXEN::mask;

/// MTYP
/// Position: 2, Width: 2
using MTYP = BitField<2, 2>;
constexpr uint32_t MTYP_Pos = 2;
constexpr uint32_t MTYP_Msk = MTYP::mask;

/// MWID
/// Position: 4, Width: 2
using MWID = BitField<4, 2>;
constexpr uint32_t MWID_Pos = 4;
constexpr uint32_t MWID_Msk = MWID::mask;

/// FACCEN
/// Position: 6, Width: 1
using FACCEN = BitField<6, 1>;
constexpr uint32_t FACCEN_Pos = 6;
constexpr uint32_t FACCEN_Msk = FACCEN::mask;

/// BURSTEN
/// Position: 8, Width: 1
using BURSTEN = BitField<8, 1>;
constexpr uint32_t BURSTEN_Pos = 8;
constexpr uint32_t BURSTEN_Msk = BURSTEN::mask;

/// WAITPOL
/// Position: 9, Width: 1
using WAITPOL = BitField<9, 1>;
constexpr uint32_t WAITPOL_Pos = 9;
constexpr uint32_t WAITPOL_Msk = WAITPOL::mask;

/// WRAPMOD
/// Position: 10, Width: 1
using WRAPMOD = BitField<10, 1>;
constexpr uint32_t WRAPMOD_Pos = 10;
constexpr uint32_t WRAPMOD_Msk = WRAPMOD::mask;

/// WAITCFG
/// Position: 11, Width: 1
using WAITCFG = BitField<11, 1>;
constexpr uint32_t WAITCFG_Pos = 11;
constexpr uint32_t WAITCFG_Msk = WAITCFG::mask;

/// WREN
/// Position: 12, Width: 1
using WREN = BitField<12, 1>;
constexpr uint32_t WREN_Pos = 12;
constexpr uint32_t WREN_Msk = WREN::mask;

/// WAITEN
/// Position: 13, Width: 1
using WAITEN = BitField<13, 1>;
constexpr uint32_t WAITEN_Pos = 13;
constexpr uint32_t WAITEN_Msk = WAITEN::mask;

/// EXTMOD
/// Position: 14, Width: 1
using EXTMOD = BitField<14, 1>;
constexpr uint32_t EXTMOD_Pos = 14;
constexpr uint32_t EXTMOD_Msk = EXTMOD::mask;

/// ASYNCWAIT
/// Position: 15, Width: 1
using ASYNCWAIT = BitField<15, 1>;
constexpr uint32_t ASYNCWAIT_Pos = 15;
constexpr uint32_t ASYNCWAIT_Msk = ASYNCWAIT::mask;

/// CBURSTRW
/// Position: 19, Width: 1
using CBURSTRW = BitField<19, 1>;
constexpr uint32_t CBURSTRW_Pos = 19;
constexpr uint32_t CBURSTRW_Msk = CBURSTRW::mask;

}  // namespace bcr2

/// BTR2 - SRAM/NOR-Flash chip-select timing register 2
namespace btr2 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// BUSTURN
/// Position: 16, Width: 4
using BUSTURN = BitField<16, 4>;
constexpr uint32_t BUSTURN_Pos = 16;
constexpr uint32_t BUSTURN_Msk = BUSTURN::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace btr2

/// BCR3 - SRAM/NOR-Flash chip-select control register 3
namespace bcr3 {
/// MBKEN
/// Position: 0, Width: 1
using MBKEN = BitField<0, 1>;
constexpr uint32_t MBKEN_Pos = 0;
constexpr uint32_t MBKEN_Msk = MBKEN::mask;

/// MUXEN
/// Position: 1, Width: 1
using MUXEN = BitField<1, 1>;
constexpr uint32_t MUXEN_Pos = 1;
constexpr uint32_t MUXEN_Msk = MUXEN::mask;

/// MTYP
/// Position: 2, Width: 2
using MTYP = BitField<2, 2>;
constexpr uint32_t MTYP_Pos = 2;
constexpr uint32_t MTYP_Msk = MTYP::mask;

/// MWID
/// Position: 4, Width: 2
using MWID = BitField<4, 2>;
constexpr uint32_t MWID_Pos = 4;
constexpr uint32_t MWID_Msk = MWID::mask;

/// FACCEN
/// Position: 6, Width: 1
using FACCEN = BitField<6, 1>;
constexpr uint32_t FACCEN_Pos = 6;
constexpr uint32_t FACCEN_Msk = FACCEN::mask;

/// BURSTEN
/// Position: 8, Width: 1
using BURSTEN = BitField<8, 1>;
constexpr uint32_t BURSTEN_Pos = 8;
constexpr uint32_t BURSTEN_Msk = BURSTEN::mask;

/// WAITPOL
/// Position: 9, Width: 1
using WAITPOL = BitField<9, 1>;
constexpr uint32_t WAITPOL_Pos = 9;
constexpr uint32_t WAITPOL_Msk = WAITPOL::mask;

/// WRAPMOD
/// Position: 10, Width: 1
using WRAPMOD = BitField<10, 1>;
constexpr uint32_t WRAPMOD_Pos = 10;
constexpr uint32_t WRAPMOD_Msk = WRAPMOD::mask;

/// WAITCFG
/// Position: 11, Width: 1
using WAITCFG = BitField<11, 1>;
constexpr uint32_t WAITCFG_Pos = 11;
constexpr uint32_t WAITCFG_Msk = WAITCFG::mask;

/// WREN
/// Position: 12, Width: 1
using WREN = BitField<12, 1>;
constexpr uint32_t WREN_Pos = 12;
constexpr uint32_t WREN_Msk = WREN::mask;

/// WAITEN
/// Position: 13, Width: 1
using WAITEN = BitField<13, 1>;
constexpr uint32_t WAITEN_Pos = 13;
constexpr uint32_t WAITEN_Msk = WAITEN::mask;

/// EXTMOD
/// Position: 14, Width: 1
using EXTMOD = BitField<14, 1>;
constexpr uint32_t EXTMOD_Pos = 14;
constexpr uint32_t EXTMOD_Msk = EXTMOD::mask;

/// ASYNCWAIT
/// Position: 15, Width: 1
using ASYNCWAIT = BitField<15, 1>;
constexpr uint32_t ASYNCWAIT_Pos = 15;
constexpr uint32_t ASYNCWAIT_Msk = ASYNCWAIT::mask;

/// CBURSTRW
/// Position: 19, Width: 1
using CBURSTRW = BitField<19, 1>;
constexpr uint32_t CBURSTRW_Pos = 19;
constexpr uint32_t CBURSTRW_Msk = CBURSTRW::mask;

}  // namespace bcr3

/// BTR3 - SRAM/NOR-Flash chip-select timing register 3
namespace btr3 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// BUSTURN
/// Position: 16, Width: 4
using BUSTURN = BitField<16, 4>;
constexpr uint32_t BUSTURN_Pos = 16;
constexpr uint32_t BUSTURN_Msk = BUSTURN::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace btr3

/// BCR4 - SRAM/NOR-Flash chip-select control register 4
namespace bcr4 {
/// MBKEN
/// Position: 0, Width: 1
using MBKEN = BitField<0, 1>;
constexpr uint32_t MBKEN_Pos = 0;
constexpr uint32_t MBKEN_Msk = MBKEN::mask;

/// MUXEN
/// Position: 1, Width: 1
using MUXEN = BitField<1, 1>;
constexpr uint32_t MUXEN_Pos = 1;
constexpr uint32_t MUXEN_Msk = MUXEN::mask;

/// MTYP
/// Position: 2, Width: 2
using MTYP = BitField<2, 2>;
constexpr uint32_t MTYP_Pos = 2;
constexpr uint32_t MTYP_Msk = MTYP::mask;

/// MWID
/// Position: 4, Width: 2
using MWID = BitField<4, 2>;
constexpr uint32_t MWID_Pos = 4;
constexpr uint32_t MWID_Msk = MWID::mask;

/// FACCEN
/// Position: 6, Width: 1
using FACCEN = BitField<6, 1>;
constexpr uint32_t FACCEN_Pos = 6;
constexpr uint32_t FACCEN_Msk = FACCEN::mask;

/// BURSTEN
/// Position: 8, Width: 1
using BURSTEN = BitField<8, 1>;
constexpr uint32_t BURSTEN_Pos = 8;
constexpr uint32_t BURSTEN_Msk = BURSTEN::mask;

/// WAITPOL
/// Position: 9, Width: 1
using WAITPOL = BitField<9, 1>;
constexpr uint32_t WAITPOL_Pos = 9;
constexpr uint32_t WAITPOL_Msk = WAITPOL::mask;

/// WRAPMOD
/// Position: 10, Width: 1
using WRAPMOD = BitField<10, 1>;
constexpr uint32_t WRAPMOD_Pos = 10;
constexpr uint32_t WRAPMOD_Msk = WRAPMOD::mask;

/// WAITCFG
/// Position: 11, Width: 1
using WAITCFG = BitField<11, 1>;
constexpr uint32_t WAITCFG_Pos = 11;
constexpr uint32_t WAITCFG_Msk = WAITCFG::mask;

/// WREN
/// Position: 12, Width: 1
using WREN = BitField<12, 1>;
constexpr uint32_t WREN_Pos = 12;
constexpr uint32_t WREN_Msk = WREN::mask;

/// WAITEN
/// Position: 13, Width: 1
using WAITEN = BitField<13, 1>;
constexpr uint32_t WAITEN_Pos = 13;
constexpr uint32_t WAITEN_Msk = WAITEN::mask;

/// EXTMOD
/// Position: 14, Width: 1
using EXTMOD = BitField<14, 1>;
constexpr uint32_t EXTMOD_Pos = 14;
constexpr uint32_t EXTMOD_Msk = EXTMOD::mask;

/// ASYNCWAIT
/// Position: 15, Width: 1
using ASYNCWAIT = BitField<15, 1>;
constexpr uint32_t ASYNCWAIT_Pos = 15;
constexpr uint32_t ASYNCWAIT_Msk = ASYNCWAIT::mask;

/// CBURSTRW
/// Position: 19, Width: 1
using CBURSTRW = BitField<19, 1>;
constexpr uint32_t CBURSTRW_Pos = 19;
constexpr uint32_t CBURSTRW_Msk = CBURSTRW::mask;

}  // namespace bcr4

/// BTR4 - SRAM/NOR-Flash chip-select timing register 4
namespace btr4 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// BUSTURN
/// Position: 16, Width: 4
using BUSTURN = BitField<16, 4>;
constexpr uint32_t BUSTURN_Pos = 16;
constexpr uint32_t BUSTURN_Msk = BUSTURN::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace btr4

/// PCR2 - PC Card/NAND Flash control register 2
namespace pcr2 {
/// PWAITEN
/// Position: 1, Width: 1
using PWAITEN = BitField<1, 1>;
constexpr uint32_t PWAITEN_Pos = 1;
constexpr uint32_t PWAITEN_Msk = PWAITEN::mask;

/// PBKEN
/// Position: 2, Width: 1
using PBKEN = BitField<2, 1>;
constexpr uint32_t PBKEN_Pos = 2;
constexpr uint32_t PBKEN_Msk = PBKEN::mask;

/// PTYP
/// Position: 3, Width: 1
using PTYP = BitField<3, 1>;
constexpr uint32_t PTYP_Pos = 3;
constexpr uint32_t PTYP_Msk = PTYP::mask;

/// PWID
/// Position: 4, Width: 2
using PWID = BitField<4, 2>;
constexpr uint32_t PWID_Pos = 4;
constexpr uint32_t PWID_Msk = PWID::mask;

/// ECCEN
/// Position: 6, Width: 1
using ECCEN = BitField<6, 1>;
constexpr uint32_t ECCEN_Pos = 6;
constexpr uint32_t ECCEN_Msk = ECCEN::mask;

/// TCLR
/// Position: 9, Width: 4
using TCLR = BitField<9, 4>;
constexpr uint32_t TCLR_Pos = 9;
constexpr uint32_t TCLR_Msk = TCLR::mask;

/// TAR
/// Position: 13, Width: 4
using TAR = BitField<13, 4>;
constexpr uint32_t TAR_Pos = 13;
constexpr uint32_t TAR_Msk = TAR::mask;

/// ECCPS
/// Position: 17, Width: 3
using ECCPS = BitField<17, 3>;
constexpr uint32_t ECCPS_Pos = 17;
constexpr uint32_t ECCPS_Msk = ECCPS::mask;

}  // namespace pcr2

/// SR2 - FIFO status and interrupt register 2
namespace sr2 {
/// IRS
/// Position: 0, Width: 1
/// Access: read-write
using IRS = BitField<0, 1>;
constexpr uint32_t IRS_Pos = 0;
constexpr uint32_t IRS_Msk = IRS::mask;

/// ILS
/// Position: 1, Width: 1
/// Access: read-write
using ILS = BitField<1, 1>;
constexpr uint32_t ILS_Pos = 1;
constexpr uint32_t ILS_Msk = ILS::mask;

/// IFS
/// Position: 2, Width: 1
/// Access: read-write
using IFS = BitField<2, 1>;
constexpr uint32_t IFS_Pos = 2;
constexpr uint32_t IFS_Msk = IFS::mask;

/// IREN
/// Position: 3, Width: 1
/// Access: read-write
using IREN = BitField<3, 1>;
constexpr uint32_t IREN_Pos = 3;
constexpr uint32_t IREN_Msk = IREN::mask;

/// ILEN
/// Position: 4, Width: 1
/// Access: read-write
using ILEN = BitField<4, 1>;
constexpr uint32_t ILEN_Pos = 4;
constexpr uint32_t ILEN_Msk = ILEN::mask;

/// IFEN
/// Position: 5, Width: 1
/// Access: read-write
using IFEN = BitField<5, 1>;
constexpr uint32_t IFEN_Pos = 5;
constexpr uint32_t IFEN_Msk = IFEN::mask;

/// FEMPT
/// Position: 6, Width: 1
/// Access: read-only
using FEMPT = BitField<6, 1>;
constexpr uint32_t FEMPT_Pos = 6;
constexpr uint32_t FEMPT_Msk = FEMPT::mask;

}  // namespace sr2

/// PMEM2 - Common memory space timing register 2
namespace pmem2 {
/// MEMSETx
/// Position: 0, Width: 8
using MEMSETx = BitField<0, 8>;
constexpr uint32_t MEMSETx_Pos = 0;
constexpr uint32_t MEMSETx_Msk = MEMSETx::mask;

/// MEMWAITx
/// Position: 8, Width: 8
using MEMWAITx = BitField<8, 8>;
constexpr uint32_t MEMWAITx_Pos = 8;
constexpr uint32_t MEMWAITx_Msk = MEMWAITx::mask;

/// MEMHOLDx
/// Position: 16, Width: 8
using MEMHOLDx = BitField<16, 8>;
constexpr uint32_t MEMHOLDx_Pos = 16;
constexpr uint32_t MEMHOLDx_Msk = MEMHOLDx::mask;

/// MEMHIZx
/// Position: 24, Width: 8
using MEMHIZx = BitField<24, 8>;
constexpr uint32_t MEMHIZx_Pos = 24;
constexpr uint32_t MEMHIZx_Msk = MEMHIZx::mask;

}  // namespace pmem2

/// PATT2 - Attribute memory space timing register 2
namespace patt2 {
/// Attribute memory x setup time
/// Position: 0, Width: 8
using ATTSETx = BitField<0, 8>;
constexpr uint32_t ATTSETx_Pos = 0;
constexpr uint32_t ATTSETx_Msk = ATTSETx::mask;

/// Attribute memory x wait time
/// Position: 8, Width: 8
using ATTWAITx = BitField<8, 8>;
constexpr uint32_t ATTWAITx_Pos = 8;
constexpr uint32_t ATTWAITx_Msk = ATTWAITx::mask;

/// Attribute memory x hold time
/// Position: 16, Width: 8
using ATTHOLDx = BitField<16, 8>;
constexpr uint32_t ATTHOLDx_Pos = 16;
constexpr uint32_t ATTHOLDx_Msk = ATTHOLDx::mask;

/// Attribute memory x databus HiZ time
/// Position: 24, Width: 8
using ATTHIZx = BitField<24, 8>;
constexpr uint32_t ATTHIZx_Pos = 24;
constexpr uint32_t ATTHIZx_Msk = ATTHIZx::mask;

}  // namespace patt2

/// ECCR2 - ECC result register 2
namespace eccr2 {
/// ECC result
/// Position: 0, Width: 32
using ECCx = BitField<0, 32>;
constexpr uint32_t ECCx_Pos = 0;
constexpr uint32_t ECCx_Msk = ECCx::mask;

}  // namespace eccr2

/// PCR3 - PC Card/NAND Flash control register 3
namespace pcr3 {
/// PWAITEN
/// Position: 1, Width: 1
using PWAITEN = BitField<1, 1>;
constexpr uint32_t PWAITEN_Pos = 1;
constexpr uint32_t PWAITEN_Msk = PWAITEN::mask;

/// PBKEN
/// Position: 2, Width: 1
using PBKEN = BitField<2, 1>;
constexpr uint32_t PBKEN_Pos = 2;
constexpr uint32_t PBKEN_Msk = PBKEN::mask;

/// PTYP
/// Position: 3, Width: 1
using PTYP = BitField<3, 1>;
constexpr uint32_t PTYP_Pos = 3;
constexpr uint32_t PTYP_Msk = PTYP::mask;

/// PWID
/// Position: 4, Width: 2
using PWID = BitField<4, 2>;
constexpr uint32_t PWID_Pos = 4;
constexpr uint32_t PWID_Msk = PWID::mask;

/// ECCEN
/// Position: 6, Width: 1
using ECCEN = BitField<6, 1>;
constexpr uint32_t ECCEN_Pos = 6;
constexpr uint32_t ECCEN_Msk = ECCEN::mask;

/// TCLR
/// Position: 9, Width: 4
using TCLR = BitField<9, 4>;
constexpr uint32_t TCLR_Pos = 9;
constexpr uint32_t TCLR_Msk = TCLR::mask;

/// TAR
/// Position: 13, Width: 4
using TAR = BitField<13, 4>;
constexpr uint32_t TAR_Pos = 13;
constexpr uint32_t TAR_Msk = TAR::mask;

/// ECCPS
/// Position: 17, Width: 3
using ECCPS = BitField<17, 3>;
constexpr uint32_t ECCPS_Pos = 17;
constexpr uint32_t ECCPS_Msk = ECCPS::mask;

}  // namespace pcr3

/// SR3 - FIFO status and interrupt register 3
namespace sr3 {
/// IRS
/// Position: 0, Width: 1
/// Access: read-write
using IRS = BitField<0, 1>;
constexpr uint32_t IRS_Pos = 0;
constexpr uint32_t IRS_Msk = IRS::mask;

/// ILS
/// Position: 1, Width: 1
/// Access: read-write
using ILS = BitField<1, 1>;
constexpr uint32_t ILS_Pos = 1;
constexpr uint32_t ILS_Msk = ILS::mask;

/// IFS
/// Position: 2, Width: 1
/// Access: read-write
using IFS = BitField<2, 1>;
constexpr uint32_t IFS_Pos = 2;
constexpr uint32_t IFS_Msk = IFS::mask;

/// IREN
/// Position: 3, Width: 1
/// Access: read-write
using IREN = BitField<3, 1>;
constexpr uint32_t IREN_Pos = 3;
constexpr uint32_t IREN_Msk = IREN::mask;

/// ILEN
/// Position: 4, Width: 1
/// Access: read-write
using ILEN = BitField<4, 1>;
constexpr uint32_t ILEN_Pos = 4;
constexpr uint32_t ILEN_Msk = ILEN::mask;

/// IFEN
/// Position: 5, Width: 1
/// Access: read-write
using IFEN = BitField<5, 1>;
constexpr uint32_t IFEN_Pos = 5;
constexpr uint32_t IFEN_Msk = IFEN::mask;

/// FEMPT
/// Position: 6, Width: 1
/// Access: read-only
using FEMPT = BitField<6, 1>;
constexpr uint32_t FEMPT_Pos = 6;
constexpr uint32_t FEMPT_Msk = FEMPT::mask;

}  // namespace sr3

/// PMEM3 - Common memory space timing register 3
namespace pmem3 {
/// MEMSETx
/// Position: 0, Width: 8
using MEMSETx = BitField<0, 8>;
constexpr uint32_t MEMSETx_Pos = 0;
constexpr uint32_t MEMSETx_Msk = MEMSETx::mask;

/// MEMWAITx
/// Position: 8, Width: 8
using MEMWAITx = BitField<8, 8>;
constexpr uint32_t MEMWAITx_Pos = 8;
constexpr uint32_t MEMWAITx_Msk = MEMWAITx::mask;

/// MEMHOLDx
/// Position: 16, Width: 8
using MEMHOLDx = BitField<16, 8>;
constexpr uint32_t MEMHOLDx_Pos = 16;
constexpr uint32_t MEMHOLDx_Msk = MEMHOLDx::mask;

/// MEMHIZx
/// Position: 24, Width: 8
using MEMHIZx = BitField<24, 8>;
constexpr uint32_t MEMHIZx_Pos = 24;
constexpr uint32_t MEMHIZx_Msk = MEMHIZx::mask;

}  // namespace pmem3

/// PATT3 - Attribute memory space timing register 3
namespace patt3 {
/// ATTSETx
/// Position: 0, Width: 8
using ATTSETx = BitField<0, 8>;
constexpr uint32_t ATTSETx_Pos = 0;
constexpr uint32_t ATTSETx_Msk = ATTSETx::mask;

/// ATTWAITx
/// Position: 8, Width: 8
using ATTWAITx = BitField<8, 8>;
constexpr uint32_t ATTWAITx_Pos = 8;
constexpr uint32_t ATTWAITx_Msk = ATTWAITx::mask;

/// ATTHOLDx
/// Position: 16, Width: 8
using ATTHOLDx = BitField<16, 8>;
constexpr uint32_t ATTHOLDx_Pos = 16;
constexpr uint32_t ATTHOLDx_Msk = ATTHOLDx::mask;

/// ATTHIZx
/// Position: 24, Width: 8
using ATTHIZx = BitField<24, 8>;
constexpr uint32_t ATTHIZx_Pos = 24;
constexpr uint32_t ATTHIZx_Msk = ATTHIZx::mask;

}  // namespace patt3

/// ECCR3 - ECC result register 3
namespace eccr3 {
/// ECCx
/// Position: 0, Width: 32
using ECCx = BitField<0, 32>;
constexpr uint32_t ECCx_Pos = 0;
constexpr uint32_t ECCx_Msk = ECCx::mask;

}  // namespace eccr3

/// PCR4 - PC Card/NAND Flash control register 4
namespace pcr4 {
/// PWAITEN
/// Position: 1, Width: 1
using PWAITEN = BitField<1, 1>;
constexpr uint32_t PWAITEN_Pos = 1;
constexpr uint32_t PWAITEN_Msk = PWAITEN::mask;

/// PBKEN
/// Position: 2, Width: 1
using PBKEN = BitField<2, 1>;
constexpr uint32_t PBKEN_Pos = 2;
constexpr uint32_t PBKEN_Msk = PBKEN::mask;

/// PTYP
/// Position: 3, Width: 1
using PTYP = BitField<3, 1>;
constexpr uint32_t PTYP_Pos = 3;
constexpr uint32_t PTYP_Msk = PTYP::mask;

/// PWID
/// Position: 4, Width: 2
using PWID = BitField<4, 2>;
constexpr uint32_t PWID_Pos = 4;
constexpr uint32_t PWID_Msk = PWID::mask;

/// ECCEN
/// Position: 6, Width: 1
using ECCEN = BitField<6, 1>;
constexpr uint32_t ECCEN_Pos = 6;
constexpr uint32_t ECCEN_Msk = ECCEN::mask;

/// TCLR
/// Position: 9, Width: 4
using TCLR = BitField<9, 4>;
constexpr uint32_t TCLR_Pos = 9;
constexpr uint32_t TCLR_Msk = TCLR::mask;

/// TAR
/// Position: 13, Width: 4
using TAR = BitField<13, 4>;
constexpr uint32_t TAR_Pos = 13;
constexpr uint32_t TAR_Msk = TAR::mask;

/// ECCPS
/// Position: 17, Width: 3
using ECCPS = BitField<17, 3>;
constexpr uint32_t ECCPS_Pos = 17;
constexpr uint32_t ECCPS_Msk = ECCPS::mask;

}  // namespace pcr4

/// SR4 - FIFO status and interrupt register 4
namespace sr4 {
/// IRS
/// Position: 0, Width: 1
/// Access: read-write
using IRS = BitField<0, 1>;
constexpr uint32_t IRS_Pos = 0;
constexpr uint32_t IRS_Msk = IRS::mask;

/// ILS
/// Position: 1, Width: 1
/// Access: read-write
using ILS = BitField<1, 1>;
constexpr uint32_t ILS_Pos = 1;
constexpr uint32_t ILS_Msk = ILS::mask;

/// IFS
/// Position: 2, Width: 1
/// Access: read-write
using IFS = BitField<2, 1>;
constexpr uint32_t IFS_Pos = 2;
constexpr uint32_t IFS_Msk = IFS::mask;

/// IREN
/// Position: 3, Width: 1
/// Access: read-write
using IREN = BitField<3, 1>;
constexpr uint32_t IREN_Pos = 3;
constexpr uint32_t IREN_Msk = IREN::mask;

/// ILEN
/// Position: 4, Width: 1
/// Access: read-write
using ILEN = BitField<4, 1>;
constexpr uint32_t ILEN_Pos = 4;
constexpr uint32_t ILEN_Msk = ILEN::mask;

/// IFEN
/// Position: 5, Width: 1
/// Access: read-write
using IFEN = BitField<5, 1>;
constexpr uint32_t IFEN_Pos = 5;
constexpr uint32_t IFEN_Msk = IFEN::mask;

/// FEMPT
/// Position: 6, Width: 1
/// Access: read-only
using FEMPT = BitField<6, 1>;
constexpr uint32_t FEMPT_Pos = 6;
constexpr uint32_t FEMPT_Msk = FEMPT::mask;

}  // namespace sr4

/// PMEM4 - Common memory space timing register 4
namespace pmem4 {
/// MEMSETx
/// Position: 0, Width: 8
using MEMSETx = BitField<0, 8>;
constexpr uint32_t MEMSETx_Pos = 0;
constexpr uint32_t MEMSETx_Msk = MEMSETx::mask;

/// MEMWAITx
/// Position: 8, Width: 8
using MEMWAITx = BitField<8, 8>;
constexpr uint32_t MEMWAITx_Pos = 8;
constexpr uint32_t MEMWAITx_Msk = MEMWAITx::mask;

/// MEMHOLDx
/// Position: 16, Width: 8
using MEMHOLDx = BitField<16, 8>;
constexpr uint32_t MEMHOLDx_Pos = 16;
constexpr uint32_t MEMHOLDx_Msk = MEMHOLDx::mask;

/// MEMHIZx
/// Position: 24, Width: 8
using MEMHIZx = BitField<24, 8>;
constexpr uint32_t MEMHIZx_Pos = 24;
constexpr uint32_t MEMHIZx_Msk = MEMHIZx::mask;

}  // namespace pmem4

/// PATT4 - Attribute memory space timing register 4
namespace patt4 {
/// ATTSETx
/// Position: 0, Width: 8
using ATTSETx = BitField<0, 8>;
constexpr uint32_t ATTSETx_Pos = 0;
constexpr uint32_t ATTSETx_Msk = ATTSETx::mask;

/// ATTWAITx
/// Position: 8, Width: 8
using ATTWAITx = BitField<8, 8>;
constexpr uint32_t ATTWAITx_Pos = 8;
constexpr uint32_t ATTWAITx_Msk = ATTWAITx::mask;

/// ATTHOLDx
/// Position: 16, Width: 8
using ATTHOLDx = BitField<16, 8>;
constexpr uint32_t ATTHOLDx_Pos = 16;
constexpr uint32_t ATTHOLDx_Msk = ATTHOLDx::mask;

/// ATTHIZx
/// Position: 24, Width: 8
using ATTHIZx = BitField<24, 8>;
constexpr uint32_t ATTHIZx_Pos = 24;
constexpr uint32_t ATTHIZx_Msk = ATTHIZx::mask;

}  // namespace patt4

/// PIO4 - I/O space timing register 4
namespace pio4 {
/// IOSETx
/// Position: 0, Width: 8
using IOSETx = BitField<0, 8>;
constexpr uint32_t IOSETx_Pos = 0;
constexpr uint32_t IOSETx_Msk = IOSETx::mask;

/// IOWAITx
/// Position: 8, Width: 8
using IOWAITx = BitField<8, 8>;
constexpr uint32_t IOWAITx_Pos = 8;
constexpr uint32_t IOWAITx_Msk = IOWAITx::mask;

/// IOHOLDx
/// Position: 16, Width: 8
using IOHOLDx = BitField<16, 8>;
constexpr uint32_t IOHOLDx_Pos = 16;
constexpr uint32_t IOHOLDx_Msk = IOHOLDx::mask;

/// IOHIZx
/// Position: 24, Width: 8
using IOHIZx = BitField<24, 8>;
constexpr uint32_t IOHIZx_Pos = 24;
constexpr uint32_t IOHIZx_Msk = IOHIZx::mask;

}  // namespace pio4

/// BWTR1 - SRAM/NOR-Flash write timing registers 1
namespace bwtr1 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace bwtr1

/// BWTR2 - SRAM/NOR-Flash write timing registers 2
namespace bwtr2 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace bwtr2

/// BWTR3 - SRAM/NOR-Flash write timing registers 3
namespace bwtr3 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace bwtr3

/// BWTR4 - SRAM/NOR-Flash write timing registers 4
namespace bwtr4 {
/// ADDSET
/// Position: 0, Width: 4
using ADDSET = BitField<0, 4>;
constexpr uint32_t ADDSET_Pos = 0;
constexpr uint32_t ADDSET_Msk = ADDSET::mask;

/// ADDHLD
/// Position: 4, Width: 4
using ADDHLD = BitField<4, 4>;
constexpr uint32_t ADDHLD_Pos = 4;
constexpr uint32_t ADDHLD_Msk = ADDHLD::mask;

/// DATAST
/// Position: 8, Width: 8
using DATAST = BitField<8, 8>;
constexpr uint32_t DATAST_Pos = 8;
constexpr uint32_t DATAST_Msk = DATAST::mask;

/// CLKDIV
/// Position: 20, Width: 4
using CLKDIV = BitField<20, 4>;
constexpr uint32_t CLKDIV_Pos = 20;
constexpr uint32_t CLKDIV_Msk = CLKDIV::mask;

/// DATLAT
/// Position: 24, Width: 4
using DATLAT = BitField<24, 4>;
constexpr uint32_t DATLAT_Pos = 24;
constexpr uint32_t DATLAT_Msk = DATLAT::mask;

/// ACCMOD
/// Position: 28, Width: 2
using ACCMOD = BitField<28, 2>;
constexpr uint32_t ACCMOD_Pos = 28;
constexpr uint32_t ACCMOD_Msk = ACCMOD::mask;

}  // namespace bwtr4

}  // namespace alloy::hal::st::stm32f1::fsmc
