/// Auto-generated register definitions for LOCKBIT
/// Device: ATSAMV71N21B
/// Vendor: Microchip Technology
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::atmel::samv71::atsamv71n21b::lockbit {

// ============================================================================
// LOCKBIT - Peripheral Registers
// Base Address: 0x00000000
// ============================================================================

/// LOCKBIT Register Structure
struct LOCKBIT_Registers {

    /// Lock Bits Word 0
    /// Offset: 0x0000
    volatile uint32_t WORD0;

    /// Lock Bits Word 1
    /// Offset: 0x0004
    volatile uint32_t WORD1;

    /// Lock Bits Word 2
    /// Offset: 0x0008
    volatile uint32_t WORD2;

    /// Lock Bits Word 3
    /// Offset: 0x000C
    volatile uint32_t WORD3;
};

static_assert(sizeof(LOCKBIT_Registers) >= 16, "LOCKBIT_Registers size mismatch");

/// LOCKBIT peripheral instance
constexpr LOCKBIT_Registers* LOCKBIT = 
    reinterpret_cast<LOCKBIT_Registers*>(0x00000000);

}  // namespace alloy::hal::atmel::samv71::atsamv71n21b::lockbit
