/// Auto-generated peripheral definitions for ATSAML22J16A
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_ATSAML22J16A_PERIPHERALS_HPP
#define UCORE_GENERATED_ATSAML22J16A_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::atsaml22j16a {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::atsaml22j16a

#endif  // ALLOY_GENERATED_ATSAML22J16A_PERIPHERALS_HPP
