/// Auto-generated bit field definitions for DMA
/// Device: RP2040
/// Vendor: Raspberry Pi
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::raspberrypi::rp2040::rp2040::dma {

using namespace alloy::hal::bitfields;

// ============================================================================
// DMA Bit Field Definitions
// ============================================================================

}  // namespace alloy::hal::raspberrypi::rp2040::rp2040::dma
