/// Auto-generated peripheral definitions for STM32G051
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_STM32G051_PERIPHERALS_HPP
#define ALLOY_GENERATED_STM32G051_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::stm32g051 {

/// Basic peripheral base addresses
namespace peripherals {
    // Peripheral addresses will be added here
    // This is a minimal implementation
}

} // namespace alloy::generated::stm32g051

#endif // ALLOY_GENERATED_STM32G051_PERIPHERALS_HPP
