/// Auto-generated bit field definitions for PWM
/// Family: rp2040
/// Vendor: Raspberry Pi
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::raspberrypi::rp2040::pwm {

using namespace alloy::hal::bitfields;

// ============================================================================
// PWM Bit Field Definitions
// ============================================================================

}  // namespace alloy::hal::raspberrypi::rp2040::pwm
