/// Auto-generated peripheral definitions for ATSAM4S2C
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_ATSAM4S2C_PERIPHERALS_HPP
#define UCORE_GENERATED_ATSAM4S2C_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::atsam4s2c {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::atsam4s2c

#endif  // ALLOY_GENERATED_ATSAM4S2C_PERIPHERALS_HPP
