/// Auto-generated peripheral definitions for STM32G07x
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_STM32G07X_PERIPHERALS_HPP
#define UCORE_GENERATED_STM32G07X_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::stm32g07x {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::stm32g07x

#endif  // ALLOY_GENERATED_STM32G07X_PERIPHERALS_HPP
