/// Auto-generated register definitions for MPU
/// Device: ATSAME70J21B
/// Vendor: Microchip Technology
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::atmel::same70::atsame70j21b::mpu {

// ============================================================================
// MPU - Memory Protection Unit
// Base Address: 0xE000ED90
// ============================================================================

/// MPU Register Structure
struct MPU_Registers {

    /// MPU Type Register
    /// Offset: 0x0000
    /// Reset value: 0x00001000
    volatile uint32_t TYPE;

    /// MPU Control Register
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    volatile uint32_t CTRL;

    /// MPU Region Number Register
    /// Offset: 0x0008
    volatile uint32_t RNR;

    /// MPU Region Base Address Register
    /// Offset: 0x000C
    volatile uint32_t RBAR;

    /// MPU Region Attribute and Size Register
    /// Offset: 0x0010
    volatile uint32_t RASR;

    /// MPU Alias 1 Region Base Address Register
    /// Offset: 0x0014
    volatile uint32_t RBAR_A1;

    /// MPU Alias 1 Region Attribute and Size Register
    /// Offset: 0x0018
    volatile uint32_t RASR_A1;

    /// MPU Alias 2 Region Base Address Register
    /// Offset: 0x001C
    volatile uint32_t RBAR_A2;

    /// MPU Alias 2 Region Attribute and Size Register
    /// Offset: 0x0020
    volatile uint32_t RASR_A2;

    /// MPU Alias 3 Region Base Address Register
    /// Offset: 0x0024
    volatile uint32_t RBAR_A3;

    /// MPU Alias 3 Region Attribute and Size Register
    /// Offset: 0x0028
    volatile uint32_t RASR_A3;
};

static_assert(sizeof(MPU_Registers) >= 44, "MPU_Registers size mismatch");

/// MPU peripheral instance
constexpr MPU_Registers* MPU = 
    reinterpret_cast<MPU_Registers*>(0xE000ED90);

}  // namespace alloy::hal::atmel::same70::atsame70j21b::mpu
