/// Auto-generated bit field definitions for GPBR
/// Device: ATSAM3X8E
/// Vendor: Atmel
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::gpbr {

using namespace alloy::hal::bitfields;

// ============================================================================
// GPBR Bit Field Definitions
// ============================================================================

/// GPBR[8] - General Purpose Backup Register
namespace gpbr[8] {
    /// Value of GPBR x
    /// Position: 0, Width: 32
    /// Access: read-write
    using GPBR_VALUE = BitField<0, 32>;
    constexpr uint32_t GPBR_VALUE_Pos = 0;
    constexpr uint32_t GPBR_VALUE_Msk = GPBR_VALUE::mask;

}  // namespace gpbr[8]

}  // namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::gpbr
