/// Auto-generated bit field definitions for PMC
/// Device: ATSAM3X8E
/// Vendor: Atmel
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::pmc {

using namespace alloy::hal::bitfields;

// ============================================================================
// PMC Bit Field Definitions
// ============================================================================

/// PMC_SCER - System Clock Enable Register
namespace pmc_scer {
    /// Enable USB OTG Clock (48 MHz, USB_48M) for UTMI
    /// Position: 5, Width: 1
    /// Access: write-only
    using UOTGCLK = BitField<5, 1>;
    constexpr uint32_t UOTGCLK_Pos = 5;
    constexpr uint32_t UOTGCLK_Msk = UOTGCLK::mask;

    /// Programmable Clock 0 Output Enable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PCK0 = BitField<8, 1>;
    constexpr uint32_t PCK0_Pos = 8;
    constexpr uint32_t PCK0_Msk = PCK0::mask;

    /// Programmable Clock 1 Output Enable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PCK1 = BitField<9, 1>;
    constexpr uint32_t PCK1_Pos = 9;
    constexpr uint32_t PCK1_Msk = PCK1::mask;

    /// Programmable Clock 2 Output Enable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PCK2 = BitField<10, 1>;
    constexpr uint32_t PCK2_Pos = 10;
    constexpr uint32_t PCK2_Msk = PCK2::mask;

}  // namespace pmc_scer

/// PMC_SCDR - System Clock Disable Register
namespace pmc_scdr {
    /// Disable USB OTG Clock (48 MHz, USB_48M) for UTMI
    /// Position: 5, Width: 1
    /// Access: write-only
    using UOTGCLK = BitField<5, 1>;
    constexpr uint32_t UOTGCLK_Pos = 5;
    constexpr uint32_t UOTGCLK_Msk = UOTGCLK::mask;

    /// Programmable Clock 0 Output Disable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PCK0 = BitField<8, 1>;
    constexpr uint32_t PCK0_Pos = 8;
    constexpr uint32_t PCK0_Msk = PCK0::mask;

    /// Programmable Clock 1 Output Disable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PCK1 = BitField<9, 1>;
    constexpr uint32_t PCK1_Pos = 9;
    constexpr uint32_t PCK1_Msk = PCK1::mask;

    /// Programmable Clock 2 Output Disable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PCK2 = BitField<10, 1>;
    constexpr uint32_t PCK2_Pos = 10;
    constexpr uint32_t PCK2_Msk = PCK2::mask;

}  // namespace pmc_scdr

/// PMC_SCSR - System Clock Status Register
namespace pmc_scsr {
    /// USB OTG Clock (48 MHz, USB_48M) Clock Status
    /// Position: 5, Width: 1
    /// Access: read-only
    using UOTGCLK = BitField<5, 1>;
    constexpr uint32_t UOTGCLK_Pos = 5;
    constexpr uint32_t UOTGCLK_Msk = UOTGCLK::mask;

    /// Programmable Clock 0 Output Status
    /// Position: 8, Width: 1
    /// Access: read-only
    using PCK0 = BitField<8, 1>;
    constexpr uint32_t PCK0_Pos = 8;
    constexpr uint32_t PCK0_Msk = PCK0::mask;

    /// Programmable Clock 1 Output Status
    /// Position: 9, Width: 1
    /// Access: read-only
    using PCK1 = BitField<9, 1>;
    constexpr uint32_t PCK1_Pos = 9;
    constexpr uint32_t PCK1_Msk = PCK1::mask;

    /// Programmable Clock 2 Output Status
    /// Position: 10, Width: 1
    /// Access: read-only
    using PCK2 = BitField<10, 1>;
    constexpr uint32_t PCK2_Pos = 10;
    constexpr uint32_t PCK2_Msk = PCK2::mask;

}  // namespace pmc_scsr

/// PMC_PCER0 - Peripheral Clock Enable Register 0
namespace pmc_pcer0 {
    /// Peripheral Clock 8 Enable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PID8 = BitField<8, 1>;
    constexpr uint32_t PID8_Pos = 8;
    constexpr uint32_t PID8_Msk = PID8::mask;

    /// Peripheral Clock 9 Enable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PID9 = BitField<9, 1>;
    constexpr uint32_t PID9_Pos = 9;
    constexpr uint32_t PID9_Msk = PID9::mask;

    /// Peripheral Clock 10 Enable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PID10 = BitField<10, 1>;
    constexpr uint32_t PID10_Pos = 10;
    constexpr uint32_t PID10_Msk = PID10::mask;

    /// Peripheral Clock 11 Enable
    /// Position: 11, Width: 1
    /// Access: write-only
    using PID11 = BitField<11, 1>;
    constexpr uint32_t PID11_Pos = 11;
    constexpr uint32_t PID11_Msk = PID11::mask;

    /// Peripheral Clock 12 Enable
    /// Position: 12, Width: 1
    /// Access: write-only
    using PID12 = BitField<12, 1>;
    constexpr uint32_t PID12_Pos = 12;
    constexpr uint32_t PID12_Msk = PID12::mask;

    /// Peripheral Clock 13 Enable
    /// Position: 13, Width: 1
    /// Access: write-only
    using PID13 = BitField<13, 1>;
    constexpr uint32_t PID13_Pos = 13;
    constexpr uint32_t PID13_Msk = PID13::mask;

    /// Peripheral Clock 14 Enable
    /// Position: 14, Width: 1
    /// Access: write-only
    using PID14 = BitField<14, 1>;
    constexpr uint32_t PID14_Pos = 14;
    constexpr uint32_t PID14_Msk = PID14::mask;

    /// Peripheral Clock 15 Enable
    /// Position: 15, Width: 1
    /// Access: write-only
    using PID15 = BitField<15, 1>;
    constexpr uint32_t PID15_Pos = 15;
    constexpr uint32_t PID15_Msk = PID15::mask;

    /// Peripheral Clock 16 Enable
    /// Position: 16, Width: 1
    /// Access: write-only
    using PID16 = BitField<16, 1>;
    constexpr uint32_t PID16_Pos = 16;
    constexpr uint32_t PID16_Msk = PID16::mask;

    /// Peripheral Clock 17 Enable
    /// Position: 17, Width: 1
    /// Access: write-only
    using PID17 = BitField<17, 1>;
    constexpr uint32_t PID17_Pos = 17;
    constexpr uint32_t PID17_Msk = PID17::mask;

    /// Peripheral Clock 18 Enable
    /// Position: 18, Width: 1
    /// Access: write-only
    using PID18 = BitField<18, 1>;
    constexpr uint32_t PID18_Pos = 18;
    constexpr uint32_t PID18_Msk = PID18::mask;

    /// Peripheral Clock 19 Enable
    /// Position: 19, Width: 1
    /// Access: write-only
    using PID19 = BitField<19, 1>;
    constexpr uint32_t PID19_Pos = 19;
    constexpr uint32_t PID19_Msk = PID19::mask;

    /// Peripheral Clock 20 Enable
    /// Position: 20, Width: 1
    /// Access: write-only
    using PID20 = BitField<20, 1>;
    constexpr uint32_t PID20_Pos = 20;
    constexpr uint32_t PID20_Msk = PID20::mask;

    /// Peripheral Clock 21 Enable
    /// Position: 21, Width: 1
    /// Access: write-only
    using PID21 = BitField<21, 1>;
    constexpr uint32_t PID21_Pos = 21;
    constexpr uint32_t PID21_Msk = PID21::mask;

    /// Peripheral Clock 22 Enable
    /// Position: 22, Width: 1
    /// Access: write-only
    using PID22 = BitField<22, 1>;
    constexpr uint32_t PID22_Pos = 22;
    constexpr uint32_t PID22_Msk = PID22::mask;

    /// Peripheral Clock 23 Enable
    /// Position: 23, Width: 1
    /// Access: write-only
    using PID23 = BitField<23, 1>;
    constexpr uint32_t PID23_Pos = 23;
    constexpr uint32_t PID23_Msk = PID23::mask;

    /// Peripheral Clock 24 Enable
    /// Position: 24, Width: 1
    /// Access: write-only
    using PID24 = BitField<24, 1>;
    constexpr uint32_t PID24_Pos = 24;
    constexpr uint32_t PID24_Msk = PID24::mask;

    /// Peripheral Clock 25 Enable
    /// Position: 25, Width: 1
    /// Access: write-only
    using PID25 = BitField<25, 1>;
    constexpr uint32_t PID25_Pos = 25;
    constexpr uint32_t PID25_Msk = PID25::mask;

    /// Peripheral Clock 26 Enable
    /// Position: 26, Width: 1
    /// Access: write-only
    using PID26 = BitField<26, 1>;
    constexpr uint32_t PID26_Pos = 26;
    constexpr uint32_t PID26_Msk = PID26::mask;

    /// Peripheral Clock 27 Enable
    /// Position: 27, Width: 1
    /// Access: write-only
    using PID27 = BitField<27, 1>;
    constexpr uint32_t PID27_Pos = 27;
    constexpr uint32_t PID27_Msk = PID27::mask;

    /// Peripheral Clock 28 Enable
    /// Position: 28, Width: 1
    /// Access: write-only
    using PID28 = BitField<28, 1>;
    constexpr uint32_t PID28_Pos = 28;
    constexpr uint32_t PID28_Msk = PID28::mask;

    /// Peripheral Clock 29 Enable
    /// Position: 29, Width: 1
    /// Access: write-only
    using PID29 = BitField<29, 1>;
    constexpr uint32_t PID29_Pos = 29;
    constexpr uint32_t PID29_Msk = PID29::mask;

    /// Peripheral Clock 30 Enable
    /// Position: 30, Width: 1
    /// Access: write-only
    using PID30 = BitField<30, 1>;
    constexpr uint32_t PID30_Pos = 30;
    constexpr uint32_t PID30_Msk = PID30::mask;

    /// Peripheral Clock 31 Enable
    /// Position: 31, Width: 1
    /// Access: write-only
    using PID31 = BitField<31, 1>;
    constexpr uint32_t PID31_Pos = 31;
    constexpr uint32_t PID31_Msk = PID31::mask;

}  // namespace pmc_pcer0

/// PMC_PCDR0 - Peripheral Clock Disable Register 0
namespace pmc_pcdr0 {
    /// Peripheral Clock 8 Disable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PID8 = BitField<8, 1>;
    constexpr uint32_t PID8_Pos = 8;
    constexpr uint32_t PID8_Msk = PID8::mask;

    /// Peripheral Clock 9 Disable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PID9 = BitField<9, 1>;
    constexpr uint32_t PID9_Pos = 9;
    constexpr uint32_t PID9_Msk = PID9::mask;

    /// Peripheral Clock 10 Disable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PID10 = BitField<10, 1>;
    constexpr uint32_t PID10_Pos = 10;
    constexpr uint32_t PID10_Msk = PID10::mask;

    /// Peripheral Clock 11 Disable
    /// Position: 11, Width: 1
    /// Access: write-only
    using PID11 = BitField<11, 1>;
    constexpr uint32_t PID11_Pos = 11;
    constexpr uint32_t PID11_Msk = PID11::mask;

    /// Peripheral Clock 12 Disable
    /// Position: 12, Width: 1
    /// Access: write-only
    using PID12 = BitField<12, 1>;
    constexpr uint32_t PID12_Pos = 12;
    constexpr uint32_t PID12_Msk = PID12::mask;

    /// Peripheral Clock 13 Disable
    /// Position: 13, Width: 1
    /// Access: write-only
    using PID13 = BitField<13, 1>;
    constexpr uint32_t PID13_Pos = 13;
    constexpr uint32_t PID13_Msk = PID13::mask;

    /// Peripheral Clock 14 Disable
    /// Position: 14, Width: 1
    /// Access: write-only
    using PID14 = BitField<14, 1>;
    constexpr uint32_t PID14_Pos = 14;
    constexpr uint32_t PID14_Msk = PID14::mask;

    /// Peripheral Clock 15 Disable
    /// Position: 15, Width: 1
    /// Access: write-only
    using PID15 = BitField<15, 1>;
    constexpr uint32_t PID15_Pos = 15;
    constexpr uint32_t PID15_Msk = PID15::mask;

    /// Peripheral Clock 16 Disable
    /// Position: 16, Width: 1
    /// Access: write-only
    using PID16 = BitField<16, 1>;
    constexpr uint32_t PID16_Pos = 16;
    constexpr uint32_t PID16_Msk = PID16::mask;

    /// Peripheral Clock 17 Disable
    /// Position: 17, Width: 1
    /// Access: write-only
    using PID17 = BitField<17, 1>;
    constexpr uint32_t PID17_Pos = 17;
    constexpr uint32_t PID17_Msk = PID17::mask;

    /// Peripheral Clock 18 Disable
    /// Position: 18, Width: 1
    /// Access: write-only
    using PID18 = BitField<18, 1>;
    constexpr uint32_t PID18_Pos = 18;
    constexpr uint32_t PID18_Msk = PID18::mask;

    /// Peripheral Clock 19 Disable
    /// Position: 19, Width: 1
    /// Access: write-only
    using PID19 = BitField<19, 1>;
    constexpr uint32_t PID19_Pos = 19;
    constexpr uint32_t PID19_Msk = PID19::mask;

    /// Peripheral Clock 20 Disable
    /// Position: 20, Width: 1
    /// Access: write-only
    using PID20 = BitField<20, 1>;
    constexpr uint32_t PID20_Pos = 20;
    constexpr uint32_t PID20_Msk = PID20::mask;

    /// Peripheral Clock 21 Disable
    /// Position: 21, Width: 1
    /// Access: write-only
    using PID21 = BitField<21, 1>;
    constexpr uint32_t PID21_Pos = 21;
    constexpr uint32_t PID21_Msk = PID21::mask;

    /// Peripheral Clock 22 Disable
    /// Position: 22, Width: 1
    /// Access: write-only
    using PID22 = BitField<22, 1>;
    constexpr uint32_t PID22_Pos = 22;
    constexpr uint32_t PID22_Msk = PID22::mask;

    /// Peripheral Clock 23 Disable
    /// Position: 23, Width: 1
    /// Access: write-only
    using PID23 = BitField<23, 1>;
    constexpr uint32_t PID23_Pos = 23;
    constexpr uint32_t PID23_Msk = PID23::mask;

    /// Peripheral Clock 24 Disable
    /// Position: 24, Width: 1
    /// Access: write-only
    using PID24 = BitField<24, 1>;
    constexpr uint32_t PID24_Pos = 24;
    constexpr uint32_t PID24_Msk = PID24::mask;

    /// Peripheral Clock 25 Disable
    /// Position: 25, Width: 1
    /// Access: write-only
    using PID25 = BitField<25, 1>;
    constexpr uint32_t PID25_Pos = 25;
    constexpr uint32_t PID25_Msk = PID25::mask;

    /// Peripheral Clock 26 Disable
    /// Position: 26, Width: 1
    /// Access: write-only
    using PID26 = BitField<26, 1>;
    constexpr uint32_t PID26_Pos = 26;
    constexpr uint32_t PID26_Msk = PID26::mask;

    /// Peripheral Clock 27 Disable
    /// Position: 27, Width: 1
    /// Access: write-only
    using PID27 = BitField<27, 1>;
    constexpr uint32_t PID27_Pos = 27;
    constexpr uint32_t PID27_Msk = PID27::mask;

    /// Peripheral Clock 28 Disable
    /// Position: 28, Width: 1
    /// Access: write-only
    using PID28 = BitField<28, 1>;
    constexpr uint32_t PID28_Pos = 28;
    constexpr uint32_t PID28_Msk = PID28::mask;

    /// Peripheral Clock 29 Disable
    /// Position: 29, Width: 1
    /// Access: write-only
    using PID29 = BitField<29, 1>;
    constexpr uint32_t PID29_Pos = 29;
    constexpr uint32_t PID29_Msk = PID29::mask;

    /// Peripheral Clock 30 Disable
    /// Position: 30, Width: 1
    /// Access: write-only
    using PID30 = BitField<30, 1>;
    constexpr uint32_t PID30_Pos = 30;
    constexpr uint32_t PID30_Msk = PID30::mask;

    /// Peripheral Clock 31 Disable
    /// Position: 31, Width: 1
    /// Access: write-only
    using PID31 = BitField<31, 1>;
    constexpr uint32_t PID31_Pos = 31;
    constexpr uint32_t PID31_Msk = PID31::mask;

}  // namespace pmc_pcdr0

/// PMC_PCSR0 - Peripheral Clock Status Register 0
namespace pmc_pcsr0 {
    /// Peripheral Clock 8 Status
    /// Position: 8, Width: 1
    /// Access: read-only
    using PID8 = BitField<8, 1>;
    constexpr uint32_t PID8_Pos = 8;
    constexpr uint32_t PID8_Msk = PID8::mask;

    /// Peripheral Clock 9 Status
    /// Position: 9, Width: 1
    /// Access: read-only
    using PID9 = BitField<9, 1>;
    constexpr uint32_t PID9_Pos = 9;
    constexpr uint32_t PID9_Msk = PID9::mask;

    /// Peripheral Clock 10 Status
    /// Position: 10, Width: 1
    /// Access: read-only
    using PID10 = BitField<10, 1>;
    constexpr uint32_t PID10_Pos = 10;
    constexpr uint32_t PID10_Msk = PID10::mask;

    /// Peripheral Clock 11 Status
    /// Position: 11, Width: 1
    /// Access: read-only
    using PID11 = BitField<11, 1>;
    constexpr uint32_t PID11_Pos = 11;
    constexpr uint32_t PID11_Msk = PID11::mask;

    /// Peripheral Clock 12 Status
    /// Position: 12, Width: 1
    /// Access: read-only
    using PID12 = BitField<12, 1>;
    constexpr uint32_t PID12_Pos = 12;
    constexpr uint32_t PID12_Msk = PID12::mask;

    /// Peripheral Clock 13 Status
    /// Position: 13, Width: 1
    /// Access: read-only
    using PID13 = BitField<13, 1>;
    constexpr uint32_t PID13_Pos = 13;
    constexpr uint32_t PID13_Msk = PID13::mask;

    /// Peripheral Clock 14 Status
    /// Position: 14, Width: 1
    /// Access: read-only
    using PID14 = BitField<14, 1>;
    constexpr uint32_t PID14_Pos = 14;
    constexpr uint32_t PID14_Msk = PID14::mask;

    /// Peripheral Clock 15 Status
    /// Position: 15, Width: 1
    /// Access: read-only
    using PID15 = BitField<15, 1>;
    constexpr uint32_t PID15_Pos = 15;
    constexpr uint32_t PID15_Msk = PID15::mask;

    /// Peripheral Clock 16 Status
    /// Position: 16, Width: 1
    /// Access: read-only
    using PID16 = BitField<16, 1>;
    constexpr uint32_t PID16_Pos = 16;
    constexpr uint32_t PID16_Msk = PID16::mask;

    /// Peripheral Clock 17 Status
    /// Position: 17, Width: 1
    /// Access: read-only
    using PID17 = BitField<17, 1>;
    constexpr uint32_t PID17_Pos = 17;
    constexpr uint32_t PID17_Msk = PID17::mask;

    /// Peripheral Clock 18 Status
    /// Position: 18, Width: 1
    /// Access: read-only
    using PID18 = BitField<18, 1>;
    constexpr uint32_t PID18_Pos = 18;
    constexpr uint32_t PID18_Msk = PID18::mask;

    /// Peripheral Clock 19 Status
    /// Position: 19, Width: 1
    /// Access: read-only
    using PID19 = BitField<19, 1>;
    constexpr uint32_t PID19_Pos = 19;
    constexpr uint32_t PID19_Msk = PID19::mask;

    /// Peripheral Clock 20 Status
    /// Position: 20, Width: 1
    /// Access: read-only
    using PID20 = BitField<20, 1>;
    constexpr uint32_t PID20_Pos = 20;
    constexpr uint32_t PID20_Msk = PID20::mask;

    /// Peripheral Clock 21 Status
    /// Position: 21, Width: 1
    /// Access: read-only
    using PID21 = BitField<21, 1>;
    constexpr uint32_t PID21_Pos = 21;
    constexpr uint32_t PID21_Msk = PID21::mask;

    /// Peripheral Clock 22 Status
    /// Position: 22, Width: 1
    /// Access: read-only
    using PID22 = BitField<22, 1>;
    constexpr uint32_t PID22_Pos = 22;
    constexpr uint32_t PID22_Msk = PID22::mask;

    /// Peripheral Clock 23 Status
    /// Position: 23, Width: 1
    /// Access: read-only
    using PID23 = BitField<23, 1>;
    constexpr uint32_t PID23_Pos = 23;
    constexpr uint32_t PID23_Msk = PID23::mask;

    /// Peripheral Clock 24 Status
    /// Position: 24, Width: 1
    /// Access: read-only
    using PID24 = BitField<24, 1>;
    constexpr uint32_t PID24_Pos = 24;
    constexpr uint32_t PID24_Msk = PID24::mask;

    /// Peripheral Clock 25 Status
    /// Position: 25, Width: 1
    /// Access: read-only
    using PID25 = BitField<25, 1>;
    constexpr uint32_t PID25_Pos = 25;
    constexpr uint32_t PID25_Msk = PID25::mask;

    /// Peripheral Clock 26 Status
    /// Position: 26, Width: 1
    /// Access: read-only
    using PID26 = BitField<26, 1>;
    constexpr uint32_t PID26_Pos = 26;
    constexpr uint32_t PID26_Msk = PID26::mask;

    /// Peripheral Clock 27 Status
    /// Position: 27, Width: 1
    /// Access: read-only
    using PID27 = BitField<27, 1>;
    constexpr uint32_t PID27_Pos = 27;
    constexpr uint32_t PID27_Msk = PID27::mask;

    /// Peripheral Clock 28 Status
    /// Position: 28, Width: 1
    /// Access: read-only
    using PID28 = BitField<28, 1>;
    constexpr uint32_t PID28_Pos = 28;
    constexpr uint32_t PID28_Msk = PID28::mask;

    /// Peripheral Clock 29 Status
    /// Position: 29, Width: 1
    /// Access: read-only
    using PID29 = BitField<29, 1>;
    constexpr uint32_t PID29_Pos = 29;
    constexpr uint32_t PID29_Msk = PID29::mask;

    /// Peripheral Clock 30 Status
    /// Position: 30, Width: 1
    /// Access: read-only
    using PID30 = BitField<30, 1>;
    constexpr uint32_t PID30_Pos = 30;
    constexpr uint32_t PID30_Msk = PID30::mask;

    /// Peripheral Clock 31 Status
    /// Position: 31, Width: 1
    /// Access: read-only
    using PID31 = BitField<31, 1>;
    constexpr uint32_t PID31_Pos = 31;
    constexpr uint32_t PID31_Msk = PID31::mask;

}  // namespace pmc_pcsr0

/// CKGR_UCKR - UTMI Clock Register
namespace ckgr_uckr {
    /// UTMI PLL Enable
    /// Position: 16, Width: 1
    /// Access: read-write
    using UPLLEN = BitField<16, 1>;
    constexpr uint32_t UPLLEN_Pos = 16;
    constexpr uint32_t UPLLEN_Msk = UPLLEN::mask;

    /// UTMI PLL Start-up Time
    /// Position: 20, Width: 4
    /// Access: read-write
    using UPLLCOUNT = BitField<20, 4>;
    constexpr uint32_t UPLLCOUNT_Pos = 20;
    constexpr uint32_t UPLLCOUNT_Msk = UPLLCOUNT::mask;

}  // namespace ckgr_uckr

/// CKGR_MOR - Main Oscillator Register
namespace ckgr_mor {
    /// Main Crystal Oscillator Enable
    /// Position: 0, Width: 1
    /// Access: read-write
    using MOSCXTEN = BitField<0, 1>;
    constexpr uint32_t MOSCXTEN_Pos = 0;
    constexpr uint32_t MOSCXTEN_Msk = MOSCXTEN::mask;

    /// Main Crystal Oscillator Bypass
    /// Position: 1, Width: 1
    /// Access: read-write
    using MOSCXTBY = BitField<1, 1>;
    constexpr uint32_t MOSCXTBY_Pos = 1;
    constexpr uint32_t MOSCXTBY_Msk = MOSCXTBY::mask;

    /// Main On-Chip RC Oscillator Enable
    /// Position: 3, Width: 1
    /// Access: read-write
    using MOSCRCEN = BitField<3, 1>;
    constexpr uint32_t MOSCRCEN_Pos = 3;
    constexpr uint32_t MOSCRCEN_Msk = MOSCRCEN::mask;

    /// Main On-Chip RC Oscillator Frequency Selection
    /// Position: 4, Width: 3
    /// Access: read-write
    using MOSCRCF = BitField<4, 3>;
    constexpr uint32_t MOSCRCF_Pos = 4;
    constexpr uint32_t MOSCRCF_Msk = MOSCRCF::mask;
    /// Enumerated values for MOSCRCF
    namespace moscrcf {
        constexpr uint32_t 4_MHz = 0;
        constexpr uint32_t 8_MHz = 1;
        constexpr uint32_t 12_MHz = 2;
    }

    /// Main Crystal Oscillator Start-up Time
    /// Position: 8, Width: 8
    /// Access: read-write
    using MOSCXTST = BitField<8, 8>;
    constexpr uint32_t MOSCXTST_Pos = 8;
    constexpr uint32_t MOSCXTST_Msk = MOSCXTST::mask;

    /// Write Access Password
    /// Position: 16, Width: 8
    /// Access: read-write
    using KEY = BitField<16, 8>;
    constexpr uint32_t KEY_Pos = 16;
    constexpr uint32_t KEY_Msk = KEY::mask;
    /// Enumerated values for KEY
    namespace key {
        constexpr uint32_t PASSWD = 55;
    }

    /// Main Oscillator Selection
    /// Position: 24, Width: 1
    /// Access: read-write
    using MOSCSEL = BitField<24, 1>;
    constexpr uint32_t MOSCSEL_Pos = 24;
    constexpr uint32_t MOSCSEL_Msk = MOSCSEL::mask;

    /// Clock Failure Detector Enable
    /// Position: 25, Width: 1
    /// Access: read-write
    using CFDEN = BitField<25, 1>;
    constexpr uint32_t CFDEN_Pos = 25;
    constexpr uint32_t CFDEN_Msk = CFDEN::mask;

}  // namespace ckgr_mor

/// CKGR_MCFR - Main Clock Frequency Register
namespace ckgr_mcfr {
    /// Main Clock Frequency
    /// Position: 0, Width: 16
    /// Access: read-only
    using MAINF = BitField<0, 16>;
    constexpr uint32_t MAINF_Pos = 0;
    constexpr uint32_t MAINF_Msk = MAINF::mask;

    /// Main Clock Ready
    /// Position: 16, Width: 1
    /// Access: read-only
    using MAINFRDY = BitField<16, 1>;
    constexpr uint32_t MAINFRDY_Pos = 16;
    constexpr uint32_t MAINFRDY_Msk = MAINFRDY::mask;

}  // namespace ckgr_mcfr

/// CKGR_PLLAR - PLLA Register
namespace ckgr_pllar {
    /// Divider
    /// Position: 0, Width: 8
    /// Access: read-write
    using DIVA = BitField<0, 8>;
    constexpr uint32_t DIVA_Pos = 0;
    constexpr uint32_t DIVA_Msk = DIVA::mask;

    /// PLLA Counter
    /// Position: 8, Width: 6
    /// Access: read-write
    using PLLACOUNT = BitField<8, 6>;
    constexpr uint32_t PLLACOUNT_Pos = 8;
    constexpr uint32_t PLLACOUNT_Msk = PLLACOUNT::mask;

    /// PLLA Multiplier
    /// Position: 16, Width: 11
    /// Access: read-write
    using MULA = BitField<16, 11>;
    constexpr uint32_t MULA_Pos = 16;
    constexpr uint32_t MULA_Msk = MULA::mask;

    /// Must Be Set to 1
    /// Position: 29, Width: 1
    /// Access: read-write
    using ONE = BitField<29, 1>;
    constexpr uint32_t ONE_Pos = 29;
    constexpr uint32_t ONE_Msk = ONE::mask;

}  // namespace ckgr_pllar

/// PMC_MCKR - Master Clock Register
namespace pmc_mckr {
    /// Master Clock Source Selection
    /// Position: 0, Width: 2
    /// Access: read-write
    using CSS = BitField<0, 2>;
    constexpr uint32_t CSS_Pos = 0;
    constexpr uint32_t CSS_Msk = CSS::mask;
    /// Enumerated values for CSS
    namespace css {
        constexpr uint32_t SLOW_CLK = 0;
        constexpr uint32_t MAIN_CLK = 1;
        constexpr uint32_t PLLA_CLK = 2;
        constexpr uint32_t UPLL_CLK = 3;
    }

    /// Processor Clock Prescaler
    /// Position: 4, Width: 3
    /// Access: read-write
    using PRES = BitField<4, 3>;
    constexpr uint32_t PRES_Pos = 4;
    constexpr uint32_t PRES_Msk = PRES::mask;
    /// Enumerated values for PRES
    namespace pres {
        constexpr uint32_t CLK_1 = 0;
        constexpr uint32_t CLK_2 = 1;
        constexpr uint32_t CLK_4 = 2;
        constexpr uint32_t CLK_8 = 3;
        constexpr uint32_t CLK_16 = 4;
        constexpr uint32_t CLK_32 = 5;
        constexpr uint32_t CLK_64 = 6;
        constexpr uint32_t CLK_3 = 7;
    }

    /// PLLA Divisor by 2
    /// Position: 12, Width: 1
    /// Access: read-write
    using PLLADIV2 = BitField<12, 1>;
    constexpr uint32_t PLLADIV2_Pos = 12;
    constexpr uint32_t PLLADIV2_Msk = PLLADIV2::mask;

    /// Position: 13, Width: 1
    /// Access: read-write
    using UPLLDIV2 = BitField<13, 1>;
    constexpr uint32_t UPLLDIV2_Pos = 13;
    constexpr uint32_t UPLLDIV2_Msk = UPLLDIV2::mask;

}  // namespace pmc_mckr

/// PMC_USB - USB Clock Register
namespace pmc_usb {
    /// USB Input Clock Selection
    /// Position: 0, Width: 1
    /// Access: read-write
    using USBS = BitField<0, 1>;
    constexpr uint32_t USBS_Pos = 0;
    constexpr uint32_t USBS_Msk = USBS::mask;

    /// Divider for USB Clock.
    /// Position: 8, Width: 4
    /// Access: read-write
    using USBDIV = BitField<8, 4>;
    constexpr uint32_t USBDIV_Pos = 8;
    constexpr uint32_t USBDIV_Msk = USBDIV::mask;

}  // namespace pmc_usb

/// PMC_PCK[3] - Programmable Clock 0 Register
namespace pmc_pck[3] {
    /// Master Clock Source Selection
    /// Position: 0, Width: 3
    /// Access: read-write
    using CSS = BitField<0, 3>;
    constexpr uint32_t CSS_Pos = 0;
    constexpr uint32_t CSS_Msk = CSS::mask;
    /// Enumerated values for CSS
    namespace css {
        constexpr uint32_t SLOW_CLK = 0;
        constexpr uint32_t MAIN_CLK = 1;
        constexpr uint32_t PLLA_CLK = 2;
        constexpr uint32_t UPLL_CLK = 3;
        constexpr uint32_t MCK = 4;
    }

    /// Programmable Clock Prescaler
    /// Position: 4, Width: 3
    /// Access: read-write
    using PRES = BitField<4, 3>;
    constexpr uint32_t PRES_Pos = 4;
    constexpr uint32_t PRES_Msk = PRES::mask;
    /// Enumerated values for PRES
    namespace pres {
        constexpr uint32_t CLK_1 = 0;
        constexpr uint32_t CLK_2 = 1;
        constexpr uint32_t CLK_4 = 2;
        constexpr uint32_t CLK_8 = 3;
        constexpr uint32_t CLK_16 = 4;
        constexpr uint32_t CLK_32 = 5;
        constexpr uint32_t CLK_64 = 6;
    }

}  // namespace pmc_pck[3]

/// PMC_IER - Interrupt Enable Register
namespace pmc_ier {
    /// Main Crystal Oscillator Status Interrupt Enable
    /// Position: 0, Width: 1
    /// Access: write-only
    using MOSCXTS = BitField<0, 1>;
    constexpr uint32_t MOSCXTS_Pos = 0;
    constexpr uint32_t MOSCXTS_Msk = MOSCXTS::mask;

    /// PLLA Lock Interrupt Enable
    /// Position: 1, Width: 1
    /// Access: write-only
    using LOCKA = BitField<1, 1>;
    constexpr uint32_t LOCKA_Pos = 1;
    constexpr uint32_t LOCKA_Msk = LOCKA::mask;

    /// Master Clock Ready Interrupt Enable
    /// Position: 3, Width: 1
    /// Access: write-only
    using MCKRDY = BitField<3, 1>;
    constexpr uint32_t MCKRDY_Pos = 3;
    constexpr uint32_t MCKRDY_Msk = MCKRDY::mask;

    /// UTMI PLL Lock Interrupt Enable
    /// Position: 6, Width: 1
    /// Access: write-only
    using LOCKU = BitField<6, 1>;
    constexpr uint32_t LOCKU_Pos = 6;
    constexpr uint32_t LOCKU_Msk = LOCKU::mask;

    /// Programmable Clock Ready 0 Interrupt Enable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PCKRDY0 = BitField<8, 1>;
    constexpr uint32_t PCKRDY0_Pos = 8;
    constexpr uint32_t PCKRDY0_Msk = PCKRDY0::mask;

    /// Programmable Clock Ready 1 Interrupt Enable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PCKRDY1 = BitField<9, 1>;
    constexpr uint32_t PCKRDY1_Pos = 9;
    constexpr uint32_t PCKRDY1_Msk = PCKRDY1::mask;

    /// Programmable Clock Ready 2 Interrupt Enable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PCKRDY2 = BitField<10, 1>;
    constexpr uint32_t PCKRDY2_Pos = 10;
    constexpr uint32_t PCKRDY2_Msk = PCKRDY2::mask;

    /// Main Oscillator Selection Status Interrupt Enable
    /// Position: 16, Width: 1
    /// Access: write-only
    using MOSCSELS = BitField<16, 1>;
    constexpr uint32_t MOSCSELS_Pos = 16;
    constexpr uint32_t MOSCSELS_Msk = MOSCSELS::mask;

    /// Main On-Chip RC Status Interrupt Enable
    /// Position: 17, Width: 1
    /// Access: write-only
    using MOSCRCS = BitField<17, 1>;
    constexpr uint32_t MOSCRCS_Pos = 17;
    constexpr uint32_t MOSCRCS_Msk = MOSCRCS::mask;

    /// Clock Failure Detector Event Interrupt Enable
    /// Position: 18, Width: 1
    /// Access: write-only
    using CFDEV = BitField<18, 1>;
    constexpr uint32_t CFDEV_Pos = 18;
    constexpr uint32_t CFDEV_Msk = CFDEV::mask;

}  // namespace pmc_ier

/// PMC_IDR - Interrupt Disable Register
namespace pmc_idr {
    /// Main Crystal Oscillator Status Interrupt Disable
    /// Position: 0, Width: 1
    /// Access: write-only
    using MOSCXTS = BitField<0, 1>;
    constexpr uint32_t MOSCXTS_Pos = 0;
    constexpr uint32_t MOSCXTS_Msk = MOSCXTS::mask;

    /// PLLA Lock Interrupt Disable
    /// Position: 1, Width: 1
    /// Access: write-only
    using LOCKA = BitField<1, 1>;
    constexpr uint32_t LOCKA_Pos = 1;
    constexpr uint32_t LOCKA_Msk = LOCKA::mask;

    /// Master Clock Ready Interrupt Disable
    /// Position: 3, Width: 1
    /// Access: write-only
    using MCKRDY = BitField<3, 1>;
    constexpr uint32_t MCKRDY_Pos = 3;
    constexpr uint32_t MCKRDY_Msk = MCKRDY::mask;

    /// UTMI PLL Lock Interrupt Disable
    /// Position: 6, Width: 1
    /// Access: write-only
    using LOCKU = BitField<6, 1>;
    constexpr uint32_t LOCKU_Pos = 6;
    constexpr uint32_t LOCKU_Msk = LOCKU::mask;

    /// Programmable Clock Ready 0 Interrupt Disable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PCKRDY0 = BitField<8, 1>;
    constexpr uint32_t PCKRDY0_Pos = 8;
    constexpr uint32_t PCKRDY0_Msk = PCKRDY0::mask;

    /// Programmable Clock Ready 1 Interrupt Disable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PCKRDY1 = BitField<9, 1>;
    constexpr uint32_t PCKRDY1_Pos = 9;
    constexpr uint32_t PCKRDY1_Msk = PCKRDY1::mask;

    /// Programmable Clock Ready 2 Interrupt Disable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PCKRDY2 = BitField<10, 1>;
    constexpr uint32_t PCKRDY2_Pos = 10;
    constexpr uint32_t PCKRDY2_Msk = PCKRDY2::mask;

    /// Main Oscillator Selection Status Interrupt Disable
    /// Position: 16, Width: 1
    /// Access: write-only
    using MOSCSELS = BitField<16, 1>;
    constexpr uint32_t MOSCSELS_Pos = 16;
    constexpr uint32_t MOSCSELS_Msk = MOSCSELS::mask;

    /// Main On-Chip RC Status Interrupt Disable
    /// Position: 17, Width: 1
    /// Access: write-only
    using MOSCRCS = BitField<17, 1>;
    constexpr uint32_t MOSCRCS_Pos = 17;
    constexpr uint32_t MOSCRCS_Msk = MOSCRCS::mask;

    /// Clock Failure Detector Event Interrupt Disable
    /// Position: 18, Width: 1
    /// Access: write-only
    using CFDEV = BitField<18, 1>;
    constexpr uint32_t CFDEV_Pos = 18;
    constexpr uint32_t CFDEV_Msk = CFDEV::mask;

}  // namespace pmc_idr

/// PMC_SR - Status Register
namespace pmc_sr {
    /// Main XTAL Oscillator Status
    /// Position: 0, Width: 1
    /// Access: read-only
    using MOSCXTS = BitField<0, 1>;
    constexpr uint32_t MOSCXTS_Pos = 0;
    constexpr uint32_t MOSCXTS_Msk = MOSCXTS::mask;

    /// PLLA Lock Status
    /// Position: 1, Width: 1
    /// Access: read-only
    using LOCKA = BitField<1, 1>;
    constexpr uint32_t LOCKA_Pos = 1;
    constexpr uint32_t LOCKA_Msk = LOCKA::mask;

    /// Master Clock Status
    /// Position: 3, Width: 1
    /// Access: read-only
    using MCKRDY = BitField<3, 1>;
    constexpr uint32_t MCKRDY_Pos = 3;
    constexpr uint32_t MCKRDY_Msk = MCKRDY::mask;

    /// UTMI PLL Lock Status
    /// Position: 6, Width: 1
    /// Access: read-only
    using LOCKU = BitField<6, 1>;
    constexpr uint32_t LOCKU_Pos = 6;
    constexpr uint32_t LOCKU_Msk = LOCKU::mask;

    /// Slow Clock Oscillator Selection
    /// Position: 7, Width: 1
    /// Access: read-only
    using OSCSELS = BitField<7, 1>;
    constexpr uint32_t OSCSELS_Pos = 7;
    constexpr uint32_t OSCSELS_Msk = OSCSELS::mask;

    /// Programmable Clock Ready Status
    /// Position: 8, Width: 1
    /// Access: read-only
    using PCKRDY0 = BitField<8, 1>;
    constexpr uint32_t PCKRDY0_Pos = 8;
    constexpr uint32_t PCKRDY0_Msk = PCKRDY0::mask;

    /// Programmable Clock Ready Status
    /// Position: 9, Width: 1
    /// Access: read-only
    using PCKRDY1 = BitField<9, 1>;
    constexpr uint32_t PCKRDY1_Pos = 9;
    constexpr uint32_t PCKRDY1_Msk = PCKRDY1::mask;

    /// Programmable Clock Ready Status
    /// Position: 10, Width: 1
    /// Access: read-only
    using PCKRDY2 = BitField<10, 1>;
    constexpr uint32_t PCKRDY2_Pos = 10;
    constexpr uint32_t PCKRDY2_Msk = PCKRDY2::mask;

    /// Main Oscillator Selection Status
    /// Position: 16, Width: 1
    /// Access: read-only
    using MOSCSELS = BitField<16, 1>;
    constexpr uint32_t MOSCSELS_Pos = 16;
    constexpr uint32_t MOSCSELS_Msk = MOSCSELS::mask;

    /// Main On-Chip RC Oscillator Status
    /// Position: 17, Width: 1
    /// Access: read-only
    using MOSCRCS = BitField<17, 1>;
    constexpr uint32_t MOSCRCS_Pos = 17;
    constexpr uint32_t MOSCRCS_Msk = MOSCRCS::mask;

    /// Clock Failure Detector Event
    /// Position: 18, Width: 1
    /// Access: read-only
    using CFDEV = BitField<18, 1>;
    constexpr uint32_t CFDEV_Pos = 18;
    constexpr uint32_t CFDEV_Msk = CFDEV::mask;

    /// Clock Failure Detector Status
    /// Position: 19, Width: 1
    /// Access: read-only
    using CFDS = BitField<19, 1>;
    constexpr uint32_t CFDS_Pos = 19;
    constexpr uint32_t CFDS_Msk = CFDS::mask;

    /// Clock Failure Detector Fault Output Status
    /// Position: 20, Width: 1
    /// Access: read-only
    using FOS = BitField<20, 1>;
    constexpr uint32_t FOS_Pos = 20;
    constexpr uint32_t FOS_Msk = FOS::mask;

}  // namespace pmc_sr

/// PMC_IMR - Interrupt Mask Register
namespace pmc_imr {
    /// Main Crystal Oscillator Status Interrupt Mask
    /// Position: 0, Width: 1
    /// Access: read-only
    using MOSCXTS = BitField<0, 1>;
    constexpr uint32_t MOSCXTS_Pos = 0;
    constexpr uint32_t MOSCXTS_Msk = MOSCXTS::mask;

    /// PLLA Lock Interrupt Mask
    /// Position: 1, Width: 1
    /// Access: read-only
    using LOCKA = BitField<1, 1>;
    constexpr uint32_t LOCKA_Pos = 1;
    constexpr uint32_t LOCKA_Msk = LOCKA::mask;

    /// Master Clock Ready Interrupt Mask
    /// Position: 3, Width: 1
    /// Access: read-only
    using MCKRDY = BitField<3, 1>;
    constexpr uint32_t MCKRDY_Pos = 3;
    constexpr uint32_t MCKRDY_Msk = MCKRDY::mask;

    /// UTMI PLL Lock Interrupt Mask
    /// Position: 6, Width: 1
    /// Access: read-only
    using LOCKU = BitField<6, 1>;
    constexpr uint32_t LOCKU_Pos = 6;
    constexpr uint32_t LOCKU_Msk = LOCKU::mask;

    /// Programmable Clock Ready 0 Interrupt Mask
    /// Position: 8, Width: 1
    /// Access: read-only
    using PCKRDY0 = BitField<8, 1>;
    constexpr uint32_t PCKRDY0_Pos = 8;
    constexpr uint32_t PCKRDY0_Msk = PCKRDY0::mask;

    /// Programmable Clock Ready 1 Interrupt Mask
    /// Position: 9, Width: 1
    /// Access: read-only
    using PCKRDY1 = BitField<9, 1>;
    constexpr uint32_t PCKRDY1_Pos = 9;
    constexpr uint32_t PCKRDY1_Msk = PCKRDY1::mask;

    /// Programmable Clock Ready 2 Interrupt Mask
    /// Position: 10, Width: 1
    /// Access: read-only
    using PCKRDY2 = BitField<10, 1>;
    constexpr uint32_t PCKRDY2_Pos = 10;
    constexpr uint32_t PCKRDY2_Msk = PCKRDY2::mask;

    /// Main Oscillator Selection Status Interrupt Mask
    /// Position: 16, Width: 1
    /// Access: read-only
    using MOSCSELS = BitField<16, 1>;
    constexpr uint32_t MOSCSELS_Pos = 16;
    constexpr uint32_t MOSCSELS_Msk = MOSCSELS::mask;

    /// Main On-Chip RC Status Interrupt Mask
    /// Position: 17, Width: 1
    /// Access: read-only
    using MOSCRCS = BitField<17, 1>;
    constexpr uint32_t MOSCRCS_Pos = 17;
    constexpr uint32_t MOSCRCS_Msk = MOSCRCS::mask;

    /// Clock Failure Detector Event Interrupt Mask
    /// Position: 18, Width: 1
    /// Access: read-only
    using CFDEV = BitField<18, 1>;
    constexpr uint32_t CFDEV_Pos = 18;
    constexpr uint32_t CFDEV_Msk = CFDEV::mask;

}  // namespace pmc_imr

/// PMC_FSMR - Fast Start-up Mode Register
namespace pmc_fsmr {
    /// Fast Start-up Input Enable 0
    /// Position: 0, Width: 1
    /// Access: read-write
    using FSTT0 = BitField<0, 1>;
    constexpr uint32_t FSTT0_Pos = 0;
    constexpr uint32_t FSTT0_Msk = FSTT0::mask;

    /// Fast Start-up Input Enable 1
    /// Position: 1, Width: 1
    /// Access: read-write
    using FSTT1 = BitField<1, 1>;
    constexpr uint32_t FSTT1_Pos = 1;
    constexpr uint32_t FSTT1_Msk = FSTT1::mask;

    /// Fast Start-up Input Enable 2
    /// Position: 2, Width: 1
    /// Access: read-write
    using FSTT2 = BitField<2, 1>;
    constexpr uint32_t FSTT2_Pos = 2;
    constexpr uint32_t FSTT2_Msk = FSTT2::mask;

    /// Fast Start-up Input Enable 3
    /// Position: 3, Width: 1
    /// Access: read-write
    using FSTT3 = BitField<3, 1>;
    constexpr uint32_t FSTT3_Pos = 3;
    constexpr uint32_t FSTT3_Msk = FSTT3::mask;

    /// Fast Start-up Input Enable 4
    /// Position: 4, Width: 1
    /// Access: read-write
    using FSTT4 = BitField<4, 1>;
    constexpr uint32_t FSTT4_Pos = 4;
    constexpr uint32_t FSTT4_Msk = FSTT4::mask;

    /// Fast Start-up Input Enable 5
    /// Position: 5, Width: 1
    /// Access: read-write
    using FSTT5 = BitField<5, 1>;
    constexpr uint32_t FSTT5_Pos = 5;
    constexpr uint32_t FSTT5_Msk = FSTT5::mask;

    /// Fast Start-up Input Enable 6
    /// Position: 6, Width: 1
    /// Access: read-write
    using FSTT6 = BitField<6, 1>;
    constexpr uint32_t FSTT6_Pos = 6;
    constexpr uint32_t FSTT6_Msk = FSTT6::mask;

    /// Fast Start-up Input Enable 7
    /// Position: 7, Width: 1
    /// Access: read-write
    using FSTT7 = BitField<7, 1>;
    constexpr uint32_t FSTT7_Pos = 7;
    constexpr uint32_t FSTT7_Msk = FSTT7::mask;

    /// Fast Start-up Input Enable 8
    /// Position: 8, Width: 1
    /// Access: read-write
    using FSTT8 = BitField<8, 1>;
    constexpr uint32_t FSTT8_Pos = 8;
    constexpr uint32_t FSTT8_Msk = FSTT8::mask;

    /// Fast Start-up Input Enable 9
    /// Position: 9, Width: 1
    /// Access: read-write
    using FSTT9 = BitField<9, 1>;
    constexpr uint32_t FSTT9_Pos = 9;
    constexpr uint32_t FSTT9_Msk = FSTT9::mask;

    /// Fast Start-up Input Enable 10
    /// Position: 10, Width: 1
    /// Access: read-write
    using FSTT10 = BitField<10, 1>;
    constexpr uint32_t FSTT10_Pos = 10;
    constexpr uint32_t FSTT10_Msk = FSTT10::mask;

    /// Fast Start-up Input Enable 11
    /// Position: 11, Width: 1
    /// Access: read-write
    using FSTT11 = BitField<11, 1>;
    constexpr uint32_t FSTT11_Pos = 11;
    constexpr uint32_t FSTT11_Msk = FSTT11::mask;

    /// Fast Start-up Input Enable 12
    /// Position: 12, Width: 1
    /// Access: read-write
    using FSTT12 = BitField<12, 1>;
    constexpr uint32_t FSTT12_Pos = 12;
    constexpr uint32_t FSTT12_Msk = FSTT12::mask;

    /// Fast Start-up Input Enable 13
    /// Position: 13, Width: 1
    /// Access: read-write
    using FSTT13 = BitField<13, 1>;
    constexpr uint32_t FSTT13_Pos = 13;
    constexpr uint32_t FSTT13_Msk = FSTT13::mask;

    /// Fast Start-up Input Enable 14
    /// Position: 14, Width: 1
    /// Access: read-write
    using FSTT14 = BitField<14, 1>;
    constexpr uint32_t FSTT14_Pos = 14;
    constexpr uint32_t FSTT14_Msk = FSTT14::mask;

    /// Fast Start-up Input Enable 15
    /// Position: 15, Width: 1
    /// Access: read-write
    using FSTT15 = BitField<15, 1>;
    constexpr uint32_t FSTT15_Pos = 15;
    constexpr uint32_t FSTT15_Msk = FSTT15::mask;

    /// RTT Alarm Enable
    /// Position: 16, Width: 1
    /// Access: read-write
    using RTTAL = BitField<16, 1>;
    constexpr uint32_t RTTAL_Pos = 16;
    constexpr uint32_t RTTAL_Msk = RTTAL::mask;

    /// RTC Alarm Enable
    /// Position: 17, Width: 1
    /// Access: read-write
    using RTCAL = BitField<17, 1>;
    constexpr uint32_t RTCAL_Pos = 17;
    constexpr uint32_t RTCAL_Msk = RTCAL::mask;

    /// USB Alarm Enable
    /// Position: 18, Width: 1
    /// Access: read-write
    using USBAL = BitField<18, 1>;
    constexpr uint32_t USBAL_Pos = 18;
    constexpr uint32_t USBAL_Msk = USBAL::mask;

    /// Low Power Mode
    /// Position: 20, Width: 1
    /// Access: read-write
    using LPM = BitField<20, 1>;
    constexpr uint32_t LPM_Pos = 20;
    constexpr uint32_t LPM_Msk = LPM::mask;

}  // namespace pmc_fsmr

/// PMC_FSPR - Fast Start-up Polarity Register
namespace pmc_fspr {
    /// Fast Start-up Input Polarityx
    /// Position: 0, Width: 1
    /// Access: read-write
    using FSTP0 = BitField<0, 1>;
    constexpr uint32_t FSTP0_Pos = 0;
    constexpr uint32_t FSTP0_Msk = FSTP0::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 1, Width: 1
    /// Access: read-write
    using FSTP1 = BitField<1, 1>;
    constexpr uint32_t FSTP1_Pos = 1;
    constexpr uint32_t FSTP1_Msk = FSTP1::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 2, Width: 1
    /// Access: read-write
    using FSTP2 = BitField<2, 1>;
    constexpr uint32_t FSTP2_Pos = 2;
    constexpr uint32_t FSTP2_Msk = FSTP2::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 3, Width: 1
    /// Access: read-write
    using FSTP3 = BitField<3, 1>;
    constexpr uint32_t FSTP3_Pos = 3;
    constexpr uint32_t FSTP3_Msk = FSTP3::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 4, Width: 1
    /// Access: read-write
    using FSTP4 = BitField<4, 1>;
    constexpr uint32_t FSTP4_Pos = 4;
    constexpr uint32_t FSTP4_Msk = FSTP4::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 5, Width: 1
    /// Access: read-write
    using FSTP5 = BitField<5, 1>;
    constexpr uint32_t FSTP5_Pos = 5;
    constexpr uint32_t FSTP5_Msk = FSTP5::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 6, Width: 1
    /// Access: read-write
    using FSTP6 = BitField<6, 1>;
    constexpr uint32_t FSTP6_Pos = 6;
    constexpr uint32_t FSTP6_Msk = FSTP6::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 7, Width: 1
    /// Access: read-write
    using FSTP7 = BitField<7, 1>;
    constexpr uint32_t FSTP7_Pos = 7;
    constexpr uint32_t FSTP7_Msk = FSTP7::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 8, Width: 1
    /// Access: read-write
    using FSTP8 = BitField<8, 1>;
    constexpr uint32_t FSTP8_Pos = 8;
    constexpr uint32_t FSTP8_Msk = FSTP8::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 9, Width: 1
    /// Access: read-write
    using FSTP9 = BitField<9, 1>;
    constexpr uint32_t FSTP9_Pos = 9;
    constexpr uint32_t FSTP9_Msk = FSTP9::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 10, Width: 1
    /// Access: read-write
    using FSTP10 = BitField<10, 1>;
    constexpr uint32_t FSTP10_Pos = 10;
    constexpr uint32_t FSTP10_Msk = FSTP10::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 11, Width: 1
    /// Access: read-write
    using FSTP11 = BitField<11, 1>;
    constexpr uint32_t FSTP11_Pos = 11;
    constexpr uint32_t FSTP11_Msk = FSTP11::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 12, Width: 1
    /// Access: read-write
    using FSTP12 = BitField<12, 1>;
    constexpr uint32_t FSTP12_Pos = 12;
    constexpr uint32_t FSTP12_Msk = FSTP12::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 13, Width: 1
    /// Access: read-write
    using FSTP13 = BitField<13, 1>;
    constexpr uint32_t FSTP13_Pos = 13;
    constexpr uint32_t FSTP13_Msk = FSTP13::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 14, Width: 1
    /// Access: read-write
    using FSTP14 = BitField<14, 1>;
    constexpr uint32_t FSTP14_Pos = 14;
    constexpr uint32_t FSTP14_Msk = FSTP14::mask;

    /// Fast Start-up Input Polarityx
    /// Position: 15, Width: 1
    /// Access: read-write
    using FSTP15 = BitField<15, 1>;
    constexpr uint32_t FSTP15_Pos = 15;
    constexpr uint32_t FSTP15_Msk = FSTP15::mask;

}  // namespace pmc_fspr

/// PMC_FOCR - Fault Output Clear Register
namespace pmc_focr {
    /// Fault Output Clear
    /// Position: 0, Width: 1
    /// Access: write-only
    using FOCLR = BitField<0, 1>;
    constexpr uint32_t FOCLR_Pos = 0;
    constexpr uint32_t FOCLR_Msk = FOCLR::mask;

}  // namespace pmc_focr

/// PMC_WPMR - Write Protect Mode Register
namespace pmc_wpmr {
    /// Write Protect Enable
    /// Position: 0, Width: 1
    /// Access: read-write
    using WPEN = BitField<0, 1>;
    constexpr uint32_t WPEN_Pos = 0;
    constexpr uint32_t WPEN_Msk = WPEN::mask;

    /// Write Protect KEY
    /// Position: 8, Width: 24
    /// Access: read-write
    using WPKEY = BitField<8, 24>;
    constexpr uint32_t WPKEY_Pos = 8;
    constexpr uint32_t WPKEY_Msk = WPKEY::mask;
    /// Enumerated values for WPKEY
    namespace wpkey {
        constexpr uint32_t PASSWD = 5262659;
    }

}  // namespace pmc_wpmr

/// PMC_WPSR - Write Protect Status Register
namespace pmc_wpsr {
    /// Write Protect Violation Status
    /// Position: 0, Width: 1
    /// Access: read-only
    using WPVS = BitField<0, 1>;
    constexpr uint32_t WPVS_Pos = 0;
    constexpr uint32_t WPVS_Msk = WPVS::mask;

    /// Write Protect Violation Source
    /// Position: 8, Width: 16
    /// Access: read-only
    using WPVSRC = BitField<8, 16>;
    constexpr uint32_t WPVSRC_Pos = 8;
    constexpr uint32_t WPVSRC_Msk = WPVSRC::mask;

}  // namespace pmc_wpsr

/// PMC_PCER1 - Peripheral Clock Enable Register 1
namespace pmc_pcer1 {
    /// Peripheral Clock 32 Enable
    /// Position: 0, Width: 1
    /// Access: write-only
    using PID32 = BitField<0, 1>;
    constexpr uint32_t PID32_Pos = 0;
    constexpr uint32_t PID32_Msk = PID32::mask;

    /// Peripheral Clock 33 Enable
    /// Position: 1, Width: 1
    /// Access: write-only
    using PID33 = BitField<1, 1>;
    constexpr uint32_t PID33_Pos = 1;
    constexpr uint32_t PID33_Msk = PID33::mask;

    /// Peripheral Clock 34 Enable
    /// Position: 2, Width: 1
    /// Access: write-only
    using PID34 = BitField<2, 1>;
    constexpr uint32_t PID34_Pos = 2;
    constexpr uint32_t PID34_Msk = PID34::mask;

    /// Peripheral Clock 35 Enable
    /// Position: 3, Width: 1
    /// Access: write-only
    using PID35 = BitField<3, 1>;
    constexpr uint32_t PID35_Pos = 3;
    constexpr uint32_t PID35_Msk = PID35::mask;

    /// Peripheral Clock 36 Enable
    /// Position: 4, Width: 1
    /// Access: write-only
    using PID36 = BitField<4, 1>;
    constexpr uint32_t PID36_Pos = 4;
    constexpr uint32_t PID36_Msk = PID36::mask;

    /// Peripheral Clock 37 Enable
    /// Position: 5, Width: 1
    /// Access: write-only
    using PID37 = BitField<5, 1>;
    constexpr uint32_t PID37_Pos = 5;
    constexpr uint32_t PID37_Msk = PID37::mask;

    /// Peripheral Clock 38 Enable
    /// Position: 6, Width: 1
    /// Access: write-only
    using PID38 = BitField<6, 1>;
    constexpr uint32_t PID38_Pos = 6;
    constexpr uint32_t PID38_Msk = PID38::mask;

    /// Peripheral Clock 39 Enable
    /// Position: 7, Width: 1
    /// Access: write-only
    using PID39 = BitField<7, 1>;
    constexpr uint32_t PID39_Pos = 7;
    constexpr uint32_t PID39_Msk = PID39::mask;

    /// Peripheral Clock 40 Enable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PID40 = BitField<8, 1>;
    constexpr uint32_t PID40_Pos = 8;
    constexpr uint32_t PID40_Msk = PID40::mask;

    /// Peripheral Clock 41 Enable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PID41 = BitField<9, 1>;
    constexpr uint32_t PID41_Pos = 9;
    constexpr uint32_t PID41_Msk = PID41::mask;

    /// Peripheral Clock 42 Enable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PID42 = BitField<10, 1>;
    constexpr uint32_t PID42_Pos = 10;
    constexpr uint32_t PID42_Msk = PID42::mask;

    /// Peripheral Clock 43 Enable
    /// Position: 11, Width: 1
    /// Access: write-only
    using PID43 = BitField<11, 1>;
    constexpr uint32_t PID43_Pos = 11;
    constexpr uint32_t PID43_Msk = PID43::mask;

    /// Peripheral Clock 44 Enable
    /// Position: 12, Width: 1
    /// Access: write-only
    using PID44 = BitField<12, 1>;
    constexpr uint32_t PID44_Pos = 12;
    constexpr uint32_t PID44_Msk = PID44::mask;

}  // namespace pmc_pcer1

/// PMC_PCDR1 - Peripheral Clock Disable Register 1
namespace pmc_pcdr1 {
    /// Peripheral Clock 32 Disable
    /// Position: 0, Width: 1
    /// Access: write-only
    using PID32 = BitField<0, 1>;
    constexpr uint32_t PID32_Pos = 0;
    constexpr uint32_t PID32_Msk = PID32::mask;

    /// Peripheral Clock 33 Disable
    /// Position: 1, Width: 1
    /// Access: write-only
    using PID33 = BitField<1, 1>;
    constexpr uint32_t PID33_Pos = 1;
    constexpr uint32_t PID33_Msk = PID33::mask;

    /// Peripheral Clock 34 Disable
    /// Position: 2, Width: 1
    /// Access: write-only
    using PID34 = BitField<2, 1>;
    constexpr uint32_t PID34_Pos = 2;
    constexpr uint32_t PID34_Msk = PID34::mask;

    /// Peripheral Clock 35 Disable
    /// Position: 3, Width: 1
    /// Access: write-only
    using PID35 = BitField<3, 1>;
    constexpr uint32_t PID35_Pos = 3;
    constexpr uint32_t PID35_Msk = PID35::mask;

    /// Peripheral Clock 36 Disable
    /// Position: 4, Width: 1
    /// Access: write-only
    using PID36 = BitField<4, 1>;
    constexpr uint32_t PID36_Pos = 4;
    constexpr uint32_t PID36_Msk = PID36::mask;

    /// Peripheral Clock 37 Disable
    /// Position: 5, Width: 1
    /// Access: write-only
    using PID37 = BitField<5, 1>;
    constexpr uint32_t PID37_Pos = 5;
    constexpr uint32_t PID37_Msk = PID37::mask;

    /// Peripheral Clock 38 Disable
    /// Position: 6, Width: 1
    /// Access: write-only
    using PID38 = BitField<6, 1>;
    constexpr uint32_t PID38_Pos = 6;
    constexpr uint32_t PID38_Msk = PID38::mask;

    /// Peripheral Clock 39 Disable
    /// Position: 7, Width: 1
    /// Access: write-only
    using PID39 = BitField<7, 1>;
    constexpr uint32_t PID39_Pos = 7;
    constexpr uint32_t PID39_Msk = PID39::mask;

    /// Peripheral Clock 40 Disable
    /// Position: 8, Width: 1
    /// Access: write-only
    using PID40 = BitField<8, 1>;
    constexpr uint32_t PID40_Pos = 8;
    constexpr uint32_t PID40_Msk = PID40::mask;

    /// Peripheral Clock 41 Disable
    /// Position: 9, Width: 1
    /// Access: write-only
    using PID41 = BitField<9, 1>;
    constexpr uint32_t PID41_Pos = 9;
    constexpr uint32_t PID41_Msk = PID41::mask;

    /// Peripheral Clock 42 Disable
    /// Position: 10, Width: 1
    /// Access: write-only
    using PID42 = BitField<10, 1>;
    constexpr uint32_t PID42_Pos = 10;
    constexpr uint32_t PID42_Msk = PID42::mask;

    /// Peripheral Clock 43 Disable
    /// Position: 11, Width: 1
    /// Access: write-only
    using PID43 = BitField<11, 1>;
    constexpr uint32_t PID43_Pos = 11;
    constexpr uint32_t PID43_Msk = PID43::mask;

    /// Peripheral Clock 44 Disable
    /// Position: 12, Width: 1
    /// Access: write-only
    using PID44 = BitField<12, 1>;
    constexpr uint32_t PID44_Pos = 12;
    constexpr uint32_t PID44_Msk = PID44::mask;

}  // namespace pmc_pcdr1

/// PMC_PCSR1 - Peripheral Clock Status Register 1
namespace pmc_pcsr1 {
    /// Peripheral Clock 32 Status
    /// Position: 0, Width: 1
    /// Access: read-only
    using PID32 = BitField<0, 1>;
    constexpr uint32_t PID32_Pos = 0;
    constexpr uint32_t PID32_Msk = PID32::mask;

    /// Peripheral Clock 33 Status
    /// Position: 1, Width: 1
    /// Access: read-only
    using PID33 = BitField<1, 1>;
    constexpr uint32_t PID33_Pos = 1;
    constexpr uint32_t PID33_Msk = PID33::mask;

    /// Peripheral Clock 34 Status
    /// Position: 2, Width: 1
    /// Access: read-only
    using PID34 = BitField<2, 1>;
    constexpr uint32_t PID34_Pos = 2;
    constexpr uint32_t PID34_Msk = PID34::mask;

    /// Peripheral Clock 35 Status
    /// Position: 3, Width: 1
    /// Access: read-only
    using PID35 = BitField<3, 1>;
    constexpr uint32_t PID35_Pos = 3;
    constexpr uint32_t PID35_Msk = PID35::mask;

    /// Peripheral Clock 36 Status
    /// Position: 4, Width: 1
    /// Access: read-only
    using PID36 = BitField<4, 1>;
    constexpr uint32_t PID36_Pos = 4;
    constexpr uint32_t PID36_Msk = PID36::mask;

    /// Peripheral Clock 37 Status
    /// Position: 5, Width: 1
    /// Access: read-only
    using PID37 = BitField<5, 1>;
    constexpr uint32_t PID37_Pos = 5;
    constexpr uint32_t PID37_Msk = PID37::mask;

    /// Peripheral Clock 38 Status
    /// Position: 6, Width: 1
    /// Access: read-only
    using PID38 = BitField<6, 1>;
    constexpr uint32_t PID38_Pos = 6;
    constexpr uint32_t PID38_Msk = PID38::mask;

    /// Peripheral Clock 39 Status
    /// Position: 7, Width: 1
    /// Access: read-only
    using PID39 = BitField<7, 1>;
    constexpr uint32_t PID39_Pos = 7;
    constexpr uint32_t PID39_Msk = PID39::mask;

    /// Peripheral Clock 40 Status
    /// Position: 8, Width: 1
    /// Access: read-only
    using PID40 = BitField<8, 1>;
    constexpr uint32_t PID40_Pos = 8;
    constexpr uint32_t PID40_Msk = PID40::mask;

    /// Peripheral Clock 41 Status
    /// Position: 9, Width: 1
    /// Access: read-only
    using PID41 = BitField<9, 1>;
    constexpr uint32_t PID41_Pos = 9;
    constexpr uint32_t PID41_Msk = PID41::mask;

    /// Peripheral Clock 42 Status
    /// Position: 10, Width: 1
    /// Access: read-only
    using PID42 = BitField<10, 1>;
    constexpr uint32_t PID42_Pos = 10;
    constexpr uint32_t PID42_Msk = PID42::mask;

    /// Peripheral Clock 43 Status
    /// Position: 11, Width: 1
    /// Access: read-only
    using PID43 = BitField<11, 1>;
    constexpr uint32_t PID43_Pos = 11;
    constexpr uint32_t PID43_Msk = PID43::mask;

    /// Peripheral Clock 44 Status
    /// Position: 12, Width: 1
    /// Access: read-only
    using PID44 = BitField<12, 1>;
    constexpr uint32_t PID44_Pos = 12;
    constexpr uint32_t PID44_Msk = PID44::mask;

}  // namespace pmc_pcsr1

/// PMC_PCR - Peripheral Control Register
namespace pmc_pcr {
    /// Peripheral ID
    /// Position: 0, Width: 6
    /// Access: read-write
    using PID = BitField<0, 6>;
    constexpr uint32_t PID_Pos = 0;
    constexpr uint32_t PID_Msk = PID::mask;

    /// Command
    /// Position: 12, Width: 1
    /// Access: read-write
    using CMD = BitField<12, 1>;
    constexpr uint32_t CMD_Pos = 12;
    constexpr uint32_t CMD_Msk = CMD::mask;

    /// Divisor Value
    /// Position: 16, Width: 2
    /// Access: read-write
    using DIV = BitField<16, 2>;
    constexpr uint32_t DIV_Pos = 16;
    constexpr uint32_t DIV_Msk = DIV::mask;
    /// Enumerated values for DIV
    namespace div {
        constexpr uint32_t PERIPH_DIV_MCK = 0;
        constexpr uint32_t PERIPH_DIV2_MCK = 1;
        constexpr uint32_t PERIPH_DIV4_MCK = 2;
    }

    /// Enable
    /// Position: 28, Width: 1
    /// Access: read-write
    using EN = BitField<28, 1>;
    constexpr uint32_t EN_Pos = 28;
    constexpr uint32_t EN_Msk = EN::mask;

}  // namespace pmc_pcr

}  // namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::pmc
