/// Auto-generated bit field definitions for SPI0
/// Device: ATSAM3X8E
/// Vendor: Atmel
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::spi0 {

using namespace alloy::hal::bitfields;

// ============================================================================
// SPI0 Bit Field Definitions
// ============================================================================

/// CR - Control Register
namespace cr {
    /// SPI Enable
    /// Position: 0, Width: 1
    /// Access: write-only
    using SPIEN = BitField<0, 1>;
    constexpr uint32_t SPIEN_Pos = 0;
    constexpr uint32_t SPIEN_Msk = SPIEN::mask;

    /// SPI Disable
    /// Position: 1, Width: 1
    /// Access: write-only
    using SPIDIS = BitField<1, 1>;
    constexpr uint32_t SPIDIS_Pos = 1;
    constexpr uint32_t SPIDIS_Msk = SPIDIS::mask;

    /// SPI Software Reset
    /// Position: 7, Width: 1
    /// Access: write-only
    using SWRST = BitField<7, 1>;
    constexpr uint32_t SWRST_Pos = 7;
    constexpr uint32_t SWRST_Msk = SWRST::mask;

    /// Last Transfer
    /// Position: 24, Width: 1
    /// Access: write-only
    using LASTXFER = BitField<24, 1>;
    constexpr uint32_t LASTXFER_Pos = 24;
    constexpr uint32_t LASTXFER_Msk = LASTXFER::mask;

}  // namespace cr

/// MR - Mode Register
namespace mr {
    /// Master/Slave Mode
    /// Position: 0, Width: 1
    /// Access: read-write
    using MSTR = BitField<0, 1>;
    constexpr uint32_t MSTR_Pos = 0;
    constexpr uint32_t MSTR_Msk = MSTR::mask;

    /// Peripheral Select
    /// Position: 1, Width: 1
    /// Access: read-write
    using PS = BitField<1, 1>;
    constexpr uint32_t PS_Pos = 1;
    constexpr uint32_t PS_Msk = PS::mask;

    /// Chip Select Decode
    /// Position: 2, Width: 1
    /// Access: read-write
    using PCSDEC = BitField<2, 1>;
    constexpr uint32_t PCSDEC_Pos = 2;
    constexpr uint32_t PCSDEC_Msk = PCSDEC::mask;

    /// Mode Fault Detection
    /// Position: 4, Width: 1
    /// Access: read-write
    using MODFDIS = BitField<4, 1>;
    constexpr uint32_t MODFDIS_Pos = 4;
    constexpr uint32_t MODFDIS_Msk = MODFDIS::mask;

    /// Wait Data Read Before Transfer
    /// Position: 5, Width: 1
    /// Access: read-write
    using WDRBT = BitField<5, 1>;
    constexpr uint32_t WDRBT_Pos = 5;
    constexpr uint32_t WDRBT_Msk = WDRBT::mask;

    /// Local Loopback Enable
    /// Position: 7, Width: 1
    /// Access: read-write
    using LLB = BitField<7, 1>;
    constexpr uint32_t LLB_Pos = 7;
    constexpr uint32_t LLB_Msk = LLB::mask;

    /// Peripheral Chip Select
    /// Position: 16, Width: 4
    /// Access: read-write
    using PCS = BitField<16, 4>;
    constexpr uint32_t PCS_Pos = 16;
    constexpr uint32_t PCS_Msk = PCS::mask;

    /// Delay Between Chip Selects
    /// Position: 24, Width: 8
    /// Access: read-write
    using DLYBCS = BitField<24, 8>;
    constexpr uint32_t DLYBCS_Pos = 24;
    constexpr uint32_t DLYBCS_Msk = DLYBCS::mask;

}  // namespace mr

/// RDR - Receive Data Register
namespace rdr {
    /// Receive Data
    /// Position: 0, Width: 16
    /// Access: read-only
    using RD = BitField<0, 16>;
    constexpr uint32_t RD_Pos = 0;
    constexpr uint32_t RD_Msk = RD::mask;

    /// Peripheral Chip Select
    /// Position: 16, Width: 4
    /// Access: read-only
    using PCS = BitField<16, 4>;
    constexpr uint32_t PCS_Pos = 16;
    constexpr uint32_t PCS_Msk = PCS::mask;

}  // namespace rdr

/// TDR - Transmit Data Register
namespace tdr {
    /// Transmit Data
    /// Position: 0, Width: 16
    /// Access: write-only
    using TD = BitField<0, 16>;
    constexpr uint32_t TD_Pos = 0;
    constexpr uint32_t TD_Msk = TD::mask;

    /// Peripheral Chip Select
    /// Position: 16, Width: 4
    /// Access: write-only
    using PCS = BitField<16, 4>;
    constexpr uint32_t PCS_Pos = 16;
    constexpr uint32_t PCS_Msk = PCS::mask;

    /// Last Transfer
    /// Position: 24, Width: 1
    /// Access: write-only
    using LASTXFER = BitField<24, 1>;
    constexpr uint32_t LASTXFER_Pos = 24;
    constexpr uint32_t LASTXFER_Msk = LASTXFER::mask;

}  // namespace tdr

/// SR - Status Register
namespace sr {
    /// Receive Data Register Full
    /// Position: 0, Width: 1
    /// Access: read-only
    using RDRF = BitField<0, 1>;
    constexpr uint32_t RDRF_Pos = 0;
    constexpr uint32_t RDRF_Msk = RDRF::mask;

    /// Transmit Data Register Empty
    /// Position: 1, Width: 1
    /// Access: read-only
    using TDRE = BitField<1, 1>;
    constexpr uint32_t TDRE_Pos = 1;
    constexpr uint32_t TDRE_Msk = TDRE::mask;

    /// Mode Fault Error
    /// Position: 2, Width: 1
    /// Access: read-only
    using MODF = BitField<2, 1>;
    constexpr uint32_t MODF_Pos = 2;
    constexpr uint32_t MODF_Msk = MODF::mask;

    /// Overrun Error Status
    /// Position: 3, Width: 1
    /// Access: read-only
    using OVRES = BitField<3, 1>;
    constexpr uint32_t OVRES_Pos = 3;
    constexpr uint32_t OVRES_Msk = OVRES::mask;

    /// NSS Rising
    /// Position: 8, Width: 1
    /// Access: read-only
    using NSSR = BitField<8, 1>;
    constexpr uint32_t NSSR_Pos = 8;
    constexpr uint32_t NSSR_Msk = NSSR::mask;

    /// Transmission Registers Empty
    /// Position: 9, Width: 1
    /// Access: read-only
    using TXEMPTY = BitField<9, 1>;
    constexpr uint32_t TXEMPTY_Pos = 9;
    constexpr uint32_t TXEMPTY_Msk = TXEMPTY::mask;

    /// Underrun Error Status (Slave Mode Only)
    /// Position: 10, Width: 1
    /// Access: read-only
    using UNDES = BitField<10, 1>;
    constexpr uint32_t UNDES_Pos = 10;
    constexpr uint32_t UNDES_Msk = UNDES::mask;

    /// SPI Enable Status
    /// Position: 16, Width: 1
    /// Access: read-only
    using SPIENS = BitField<16, 1>;
    constexpr uint32_t SPIENS_Pos = 16;
    constexpr uint32_t SPIENS_Msk = SPIENS::mask;

}  // namespace sr

/// IER - Interrupt Enable Register
namespace ier {
    /// Receive Data Register Full Interrupt Enable
    /// Position: 0, Width: 1
    /// Access: write-only
    using RDRF = BitField<0, 1>;
    constexpr uint32_t RDRF_Pos = 0;
    constexpr uint32_t RDRF_Msk = RDRF::mask;

    /// SPI Transmit Data Register Empty Interrupt Enable
    /// Position: 1, Width: 1
    /// Access: write-only
    using TDRE = BitField<1, 1>;
    constexpr uint32_t TDRE_Pos = 1;
    constexpr uint32_t TDRE_Msk = TDRE::mask;

    /// Mode Fault Error Interrupt Enable
    /// Position: 2, Width: 1
    /// Access: write-only
    using MODF = BitField<2, 1>;
    constexpr uint32_t MODF_Pos = 2;
    constexpr uint32_t MODF_Msk = MODF::mask;

    /// Overrun Error Interrupt Enable
    /// Position: 3, Width: 1
    /// Access: write-only
    using OVRES = BitField<3, 1>;
    constexpr uint32_t OVRES_Pos = 3;
    constexpr uint32_t OVRES_Msk = OVRES::mask;

    /// NSS Rising Interrupt Enable
    /// Position: 8, Width: 1
    /// Access: write-only
    using NSSR = BitField<8, 1>;
    constexpr uint32_t NSSR_Pos = 8;
    constexpr uint32_t NSSR_Msk = NSSR::mask;

    /// Transmission Registers Empty Enable
    /// Position: 9, Width: 1
    /// Access: write-only
    using TXEMPTY = BitField<9, 1>;
    constexpr uint32_t TXEMPTY_Pos = 9;
    constexpr uint32_t TXEMPTY_Msk = TXEMPTY::mask;

    /// Underrun Error Interrupt Enable
    /// Position: 10, Width: 1
    /// Access: write-only
    using UNDES = BitField<10, 1>;
    constexpr uint32_t UNDES_Pos = 10;
    constexpr uint32_t UNDES_Msk = UNDES::mask;

}  // namespace ier

/// IDR - Interrupt Disable Register
namespace idr {
    /// Receive Data Register Full Interrupt Disable
    /// Position: 0, Width: 1
    /// Access: write-only
    using RDRF = BitField<0, 1>;
    constexpr uint32_t RDRF_Pos = 0;
    constexpr uint32_t RDRF_Msk = RDRF::mask;

    /// SPI Transmit Data Register Empty Interrupt Disable
    /// Position: 1, Width: 1
    /// Access: write-only
    using TDRE = BitField<1, 1>;
    constexpr uint32_t TDRE_Pos = 1;
    constexpr uint32_t TDRE_Msk = TDRE::mask;

    /// Mode Fault Error Interrupt Disable
    /// Position: 2, Width: 1
    /// Access: write-only
    using MODF = BitField<2, 1>;
    constexpr uint32_t MODF_Pos = 2;
    constexpr uint32_t MODF_Msk = MODF::mask;

    /// Overrun Error Interrupt Disable
    /// Position: 3, Width: 1
    /// Access: write-only
    using OVRES = BitField<3, 1>;
    constexpr uint32_t OVRES_Pos = 3;
    constexpr uint32_t OVRES_Msk = OVRES::mask;

    /// NSS Rising Interrupt Disable
    /// Position: 8, Width: 1
    /// Access: write-only
    using NSSR = BitField<8, 1>;
    constexpr uint32_t NSSR_Pos = 8;
    constexpr uint32_t NSSR_Msk = NSSR::mask;

    /// Transmission Registers Empty Disable
    /// Position: 9, Width: 1
    /// Access: write-only
    using TXEMPTY = BitField<9, 1>;
    constexpr uint32_t TXEMPTY_Pos = 9;
    constexpr uint32_t TXEMPTY_Msk = TXEMPTY::mask;

    /// Underrun Error Interrupt Disable
    /// Position: 10, Width: 1
    /// Access: write-only
    using UNDES = BitField<10, 1>;
    constexpr uint32_t UNDES_Pos = 10;
    constexpr uint32_t UNDES_Msk = UNDES::mask;

}  // namespace idr

/// IMR - Interrupt Mask Register
namespace imr {
    /// Receive Data Register Full Interrupt Mask
    /// Position: 0, Width: 1
    /// Access: read-only
    using RDRF = BitField<0, 1>;
    constexpr uint32_t RDRF_Pos = 0;
    constexpr uint32_t RDRF_Msk = RDRF::mask;

    /// SPI Transmit Data Register Empty Interrupt Mask
    /// Position: 1, Width: 1
    /// Access: read-only
    using TDRE = BitField<1, 1>;
    constexpr uint32_t TDRE_Pos = 1;
    constexpr uint32_t TDRE_Msk = TDRE::mask;

    /// Mode Fault Error Interrupt Mask
    /// Position: 2, Width: 1
    /// Access: read-only
    using MODF = BitField<2, 1>;
    constexpr uint32_t MODF_Pos = 2;
    constexpr uint32_t MODF_Msk = MODF::mask;

    /// Overrun Error Interrupt Mask
    /// Position: 3, Width: 1
    /// Access: read-only
    using OVRES = BitField<3, 1>;
    constexpr uint32_t OVRES_Pos = 3;
    constexpr uint32_t OVRES_Msk = OVRES::mask;

    /// NSS Rising Interrupt Mask
    /// Position: 8, Width: 1
    /// Access: read-only
    using NSSR = BitField<8, 1>;
    constexpr uint32_t NSSR_Pos = 8;
    constexpr uint32_t NSSR_Msk = NSSR::mask;

    /// Transmission Registers Empty Mask
    /// Position: 9, Width: 1
    /// Access: read-only
    using TXEMPTY = BitField<9, 1>;
    constexpr uint32_t TXEMPTY_Pos = 9;
    constexpr uint32_t TXEMPTY_Msk = TXEMPTY::mask;

    /// Underrun Error Interrupt Mask
    /// Position: 10, Width: 1
    /// Access: read-only
    using UNDES = BitField<10, 1>;
    constexpr uint32_t UNDES_Pos = 10;
    constexpr uint32_t UNDES_Msk = UNDES::mask;

}  // namespace imr

/// CSR[4] - Chip Select Register
namespace csr[4] {
    /// Clock Polarity
    /// Position: 0, Width: 1
    /// Access: read-write
    using CPOL = BitField<0, 1>;
    constexpr uint32_t CPOL_Pos = 0;
    constexpr uint32_t CPOL_Msk = CPOL::mask;

    /// Clock Phase
    /// Position: 1, Width: 1
    /// Access: read-write
    using NCPHA = BitField<1, 1>;
    constexpr uint32_t NCPHA_Pos = 1;
    constexpr uint32_t NCPHA_Msk = NCPHA::mask;

    /// Chip Select Not Active After Transfer (Ignored if CSAAT = 1)
    /// Position: 2, Width: 1
    /// Access: read-write
    using CSNAAT = BitField<2, 1>;
    constexpr uint32_t CSNAAT_Pos = 2;
    constexpr uint32_t CSNAAT_Msk = CSNAAT::mask;

    /// Chip Select Active After Transfer
    /// Position: 3, Width: 1
    /// Access: read-write
    using CSAAT = BitField<3, 1>;
    constexpr uint32_t CSAAT_Pos = 3;
    constexpr uint32_t CSAAT_Msk = CSAAT::mask;

    /// Bits Per Transfer
    /// Position: 4, Width: 4
    /// Access: read-write
    using BITS = BitField<4, 4>;
    constexpr uint32_t BITS_Pos = 4;
    constexpr uint32_t BITS_Msk = BITS::mask;
    /// Enumerated values for BITS
    namespace bits {
        constexpr uint32_t 8_BIT = 0;
        constexpr uint32_t 9_BIT = 1;
        constexpr uint32_t 10_BIT = 2;
        constexpr uint32_t 11_BIT = 3;
        constexpr uint32_t 12_BIT = 4;
        constexpr uint32_t 13_BIT = 5;
        constexpr uint32_t 14_BIT = 6;
        constexpr uint32_t 15_BIT = 7;
        constexpr uint32_t 16_BIT = 8;
    }

    /// Serial Clock Baud Rate
    /// Position: 8, Width: 8
    /// Access: read-write
    using SCBR = BitField<8, 8>;
    constexpr uint32_t SCBR_Pos = 8;
    constexpr uint32_t SCBR_Msk = SCBR::mask;

    /// Delay Before SPCK
    /// Position: 16, Width: 8
    /// Access: read-write
    using DLYBS = BitField<16, 8>;
    constexpr uint32_t DLYBS_Pos = 16;
    constexpr uint32_t DLYBS_Msk = DLYBS::mask;

    /// Delay Between Consecutive Transfers
    /// Position: 24, Width: 8
    /// Access: read-write
    using DLYBCT = BitField<24, 8>;
    constexpr uint32_t DLYBCT_Pos = 24;
    constexpr uint32_t DLYBCT_Msk = DLYBCT::mask;

}  // namespace csr[4]

/// WPMR - Write Protection Control Register
namespace wpmr {
    /// Write Protect Enable
    /// Position: 0, Width: 1
    /// Access: read-write
    using WPEN = BitField<0, 1>;
    constexpr uint32_t WPEN_Pos = 0;
    constexpr uint32_t WPEN_Msk = WPEN::mask;

    /// Write Protect Key
    /// Position: 8, Width: 24
    /// Access: read-write
    using WPKEY = BitField<8, 24>;
    constexpr uint32_t WPKEY_Pos = 8;
    constexpr uint32_t WPKEY_Msk = WPKEY::mask;
    /// Enumerated values for WPKEY
    namespace wpkey {
        constexpr uint32_t PASSWD = 5460041;
    }

}  // namespace wpmr

/// WPSR - Write Protection Status Register
namespace wpsr {
    /// Write Protection Violation Status
    /// Position: 0, Width: 1
    /// Access: read-only
    using WPVS = BitField<0, 1>;
    constexpr uint32_t WPVS_Pos = 0;
    constexpr uint32_t WPVS_Msk = WPVS::mask;

    /// Write Protection Violation Source
    /// Position: 8, Width: 8
    /// Access: read-only
    using WPVSRC = BitField<8, 8>;
    constexpr uint32_t WPVSRC_Pos = 8;
    constexpr uint32_t WPVSRC_Msk = WPVSRC::mask;

}  // namespace wpsr

}  // namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::spi0
