/// Auto-generated peripheral definitions for STM32G050
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_STM32G050_PERIPHERALS_HPP
#define UCORE_GENERATED_STM32G050_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::stm32g050 {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::stm32g050

#endif  // ALLOY_GENERATED_STM32G050_PERIPHERALS_HPP
