/// Auto-generated register definitions for FLASH
/// Family: stm32f7
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::st::stm32f7::flash {

// ============================================================================
// FLASH - FLASH
// Base Address: 0x40023C00
// ============================================================================

/// FLASH Register Structure
struct FLASH_Registers {

    /// Flash access control register
    /// Offset: 0x0000
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t ACR;

    /// Flash key register
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    /// Access: write-only
    volatile uint32_t KEYR;

    /// Flash option key register
    /// Offset: 0x0008
    /// Reset value: 0x00000000
    /// Access: write-only
    volatile uint32_t OPTKEYR;

    /// Status register
    /// Offset: 0x000C
    /// Reset value: 0x00000000
    volatile uint32_t SR;

    /// Control register
    /// Offset: 0x0010
    /// Reset value: 0x80000000
    /// Access: read-write
    volatile uint32_t CR;

    /// Flash option control register
    /// Offset: 0x0014
    /// Reset value: 0xC0FFAAFD
    /// Access: read-write
    volatile uint32_t OPTCR;

    /// Flash option control register 1
    /// Offset: 0x0018
    /// Reset value: 0x00400080
    /// Access: read-write
    volatile uint32_t OPTCR1;

    /// Flash option control register
    /// Offset: 0x001C
    /// Reset value: 0x800000FF
    /// Access: read-write
    volatile uint32_t OPTCR2;
};

static_assert(sizeof(FLASH_Registers) >= 32, "FLASH_Registers size mismatch");

/// FLASH peripheral instance
inline FLASH_Registers* FLASH() {
    return reinterpret_cast<FLASH_Registers*>(0x40023C00);
}

}  // namespace alloy::hal::st::stm32f7::flash
