"""Render the CMake build tree and drive cmake + ninja.

Users never see CMake: the tree lives in .alloy/build-tree (gitignored,
regenerated every run). `alloy export cmake` will later emit a standalone
copy for people who want to own their build.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

from .emit.common import EmitError
from .project import Project

# Core name -> GCC -mcpu flag; fallback per architecture.
_CPU_BY_CORE = {
    "cm0": "cortex-m0",
    "cm0plus": "cortex-m0plus",
    "cm3": "cortex-m3",
    "cm4": "cortex-m4",
    "cm7": "cortex-m7",
    "cm33": "cortex-m33",
}
_CPU_BY_ARCH = {
    "armv6m": "cortex-m0plus",
    "armv7m": "cortex-m3",
    "armv7em": "cortex-m4",
    "armv8m_base": "cortex-m23",
    "armv8m_main": "cortex-m33",
}


def _arch_ns(chip: dict[str, Any]) -> str:
    arch = chip["cores"][0]["arch"]
    if arch.startswith("armv"):
        return "cortex_m"
    if arch.startswith("xtensa"):
        return "xtensa"
    raise EmitError(f"unsupported architecture {arch}")


def _xtensa_prefix() -> str:
    if found := shutil.which("xtensa-esp-elf-gcc"):
        return str(Path(found).with_name("xtensa-esp-elf-"))
    candidate = Path.home() / ".alloy/tools/xtensa-esp-elf/bin/xtensa-esp-elf-gcc"
    if candidate.exists():
        return str(candidate.with_name("xtensa-esp-elf-"))
    raise EmitError(
        "xtensa-esp-elf toolchain not found — looked on PATH and ~/.alloy/tools/xtensa-esp-elf"
    )


def _cpu_flags(chip: dict[str, Any]) -> str:
    if _arch_ns(chip) == "xtensa":
        # The unified xtensa-esp-elf toolchain is multi-core: -mdynconfig
        # selects the concrete core (ESP32 = LX6 little-endian); without it
        # GCC emits generic BIG-endian objects that esptool rejects. The flag
        # must stay RELATIVE to match the multilib table (esp32/libgcc.a);
        # macOS hardened dlopen then needs XTENSA_GNU_CONFIG (absolute) set
        # in the environment — see _build_env().
        return f"-mdynconfig=xtensa_{chip['family']}.so -mlongcalls"
    core = chip["cores"][0]
    cpu = _CPU_BY_CORE.get(core["name"]) or _CPU_BY_ARCH.get(core["arch"])
    if cpu is None:
        raise EmitError(f"no CPU mapping for core {core['name']} / arch {core['arch']}")
    # Soft-float everywhere for now, even on FPU parts: hard-float needs a
    # CPACR enable in the arch startup before the first FP instruction.
    # TODO(arch): enable CP10/CP11 on armv7em, then honor core.fpu here.
    return f"-mcpu={cpu} -mthumb -mfloat-abi=soft"


def _toolchain_cmake(chip: dict[str, Any], cpu_flags: str) -> str:
    if _arch_ns(chip) == "xtensa":
        prefix = _xtensa_prefix()
        processor = "xtensa"
        cc, cxx = f"{prefix}gcc", f"{prefix}g++"
    else:
        processor = "arm"
        cc, cxx = "arm-none-eabi-gcc", "arm-none-eabi-g++"
    return f"""# GENERATED by alloy — DO NOT EDIT
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR {processor})
set(CMAKE_C_COMPILER "{cc}")
set(CMAKE_CXX_COMPILER "{cxx}")
set(CMAKE_ASM_COMPILER "{cc}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "{cpu_flags}")
set(CMAKE_CXX_FLAGS_INIT "{cpu_flags}")
set(CMAKE_ASM_FLAGS_INIT "{cpu_flags}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "{cpu_flags}")
"""


def _cmakelists(project: Project, chip: dict[str, Any], sources: list[Path],
                runtime_sources: list[Path]) -> str:
    gen = project.gen_dir
    gen_sources = [gen / "board.cpp"]
    for optional in ("vector_table.c", "boot2.c"):
        if (gen / optional).exists():
            gen_sources.append(gen / optional)
    src_list = "\n    ".join(
        f'"{p}"' for p in [*sources, *gen_sources, *runtime_sources]
    )
    # newlib nano/nosys specs are an ARM-newlib convention; the xtensa
    # toolchain links its own newlib without them.
    specs = "" if _arch_ns(chip) == "xtensa" else """
    --specs=nano.specs
    --specs=nosys.specs"""
    return f"""# GENERATED by alloy — DO NOT EDIT
cmake_minimum_required(VERSION 3.25)
project({project.name} C CXX ASM)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable({project.name}.elf
    {src_list}
)

target_include_directories({project.name}.elf PRIVATE
    "{project.alloy_root / 'src'}"
    "{gen}"
)

target_compile_options({project.name}.elf PRIVATE
    -Os -g3
    -ffunction-sections -fdata-sections
    -Wall -Wextra
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-threadsafe-statics>
)

target_link_options({project.name}.elf PRIVATE
    -T "{gen / 'linker.ld'}"
    -nostartfiles
    -Wl,--gc-sections
    -Wl,-Map={project.name}.map{specs}
)
"""


def build(project: Project, chip: dict[str, Any]) -> Path:
    sources = sorted((project.root / "src").rglob("*.cpp")) + \
        sorted((project.root / "src").rglob("*.c"))
    if not sources:
        raise EmitError(f"no sources under {project.root / 'src'}")

    arch_dir = project.alloy_root / "src" / "alloy" / "arch" / _arch_ns(chip)
    runtime_sources = sorted(arch_dir.glob("*.cpp")) + sorted(arch_dir.glob("*.S"))

    tree = project.build_dir
    tree.mkdir(parents=True, exist_ok=True)
    (tree / "toolchain.cmake").write_text(_toolchain_cmake(chip, _cpu_flags(chip)))
    (tree / "CMakeLists.txt").write_text(_cmakelists(project, chip, sources, runtime_sources))

    env = None
    if _arch_ns(chip) == "xtensa":
        import os  # noqa: PLC0415

        dynconfig = (Path(_xtensa_prefix()).parent.parent / "lib" /
                     f"xtensa_{chip['family']}.so")
        if not dynconfig.exists():
            raise EmitError(f"toolchain dynconfig missing: {dynconfig}")
        env = os.environ | {"XTENSA_GNU_CONFIG": str(dynconfig)}

    out = tree / "out"
    subprocess.run(
        ["cmake", "-G", "Ninja", "-S", str(tree), "-B", str(out),
         f"-DCMAKE_TOOLCHAIN_FILE={tree / 'toolchain.cmake'}",
         "-DCMAKE_BUILD_TYPE=MinSizeRel"],
        check=True, env=env,
    )
    subprocess.run(["cmake", "--build", str(out)], check=True, env=env)

    elf = out / f"{project.name}.elf"
    if not elf.exists():
        raise EmitError(f"build finished but {elf} is missing")

    size_tool = (
        f"{_xtensa_prefix()}size" if _arch_ns(chip) == "xtensa"
        else shutil.which("arm-none-eabi-size")
    )
    if size_tool:
        subprocess.run([size_tool, str(elf)], check=False)

    # clangd support out of the box.
    cc_json = out / "compile_commands.json"
    link = project.root / "compile_commands.json"
    if cc_json.exists():
        link.unlink(missing_ok=True)
        link.symlink_to(cc_json)

    return elf
