/// Auto-generated peripheral definitions for STM32F446
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_STM32F446_PERIPHERALS_HPP
#define ALLOY_GENERATED_STM32F446_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::stm32f446 {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace alloy::generated::stm32f446

#endif  // ALLOY_GENERATED_STM32F446_PERIPHERALS_HPP
