/// Auto-generated startup code for STM32F446
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#include <cstdint>
#include <cstring>

// Linker script symbols
extern uint32_t _sidata;  // Start of .data in flash
extern uint32_t _sdata;   // Start of .data in RAM
extern uint32_t _edata;   // End of .data in RAM
extern uint32_t _sbss;    // Start of .bss
extern uint32_t _ebss;    // End of .bss

// Stack top (defined in linker script)
extern uint32_t _estack;

// User application entry point
extern "C" int main();

// System initialization (weak, can be overridden)
extern "C" void SystemInit() __attribute__((weak));
extern "C" void SystemInit() {}

// Default handler for unhandled interrupts
extern "C" [[noreturn]] void Default_Handler() {
    while (true) {
        // Trap
    }
}

// Interrupt handlers (weak, can be overridden)
extern "C" void WWDG_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TAMP_STAMP_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RTC_WKUP_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void FLASH_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RCC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream6_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ADC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_TX_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_RX0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_RX1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_SCE_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI9_5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_BRK_TIM9_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_UP_TIM10_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_TRG_COM_TIM11_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_CC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C1_EV_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C1_ER_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C2_EV_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C2_ER_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI15_10_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RTC_Alarm_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void OTG_FS_WKUP_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM8_BRK_TIM12_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM8_UP_TIM13_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM8_TRG_COM_TIM14_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM8_CC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Stream7_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void FMC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM6_DAC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM7_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ETH_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ETH_WKUP_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_TX_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_RX0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_RX1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_SCE_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void OTG_FS_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream6_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Stream7_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART6_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C3_EV_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C3_ER_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DCMI_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void FPU_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART7_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART8_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void LCD_TFT_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void LCD_TFT_1_Handler() __attribute__((weak, alias("Default_Handler")));

// Reset Handler - Entry point after reset
extern "C" [[noreturn]] void Reset_Handler() {
    // 1. Copy .data section from Flash to RAM
    uint32_t* src = &_sidata;
    uint32_t* dest = &_sdata;
    while (dest < &_edata) {
        *dest++ = *src++;
    }

    // 2. Zero out .bss section
    dest = &_sbss;
    while (dest < &_ebss) {
        *dest++ = 0;
    }

    // 3. Call system initialization
    SystemInit();

    // 4. Call static constructors
    extern void (*__init_array_start[])();
    extern void (*__init_array_end[])();
    for (auto ctor = __init_array_start; ctor < __init_array_end; ++ctor) {
        (*ctor)();
    }

    // 5. Call main
    main();

    // 6. If main returns, loop forever
    while (true) {}
}

// Vector table
__attribute__((section(".isr_vector"), used))
void (* const vector_table[])() = {
    reinterpret_cast<void (*)()>(&_estack),  // Initial stack pointer
    Reset_Handler,                            // Reset handler
    WWDG_Handler,  // IRQ 0: WWDG
    WWDG_Handler,  // IRQ 0: WWDG
    TAMP_STAMP_Handler,  // IRQ 2: TAMP_STAMP
    TAMP_STAMP_Handler,  // IRQ 2: TAMP_STAMP
    RTC_WKUP_Handler,  // IRQ 3: RTC_WKUP
    RTC_WKUP_Handler,  // IRQ 3: RTC_WKUP
    FLASH_Handler,  // IRQ 4: FLASH
    FLASH_Handler,  // IRQ 4: FLASH
    RCC_Handler,  // IRQ 5: RCC
    RCC_Handler,  // IRQ 5: RCC
    EXTI0_Handler,  // IRQ 6: EXTI0
    EXTI0_Handler,  // IRQ 6: EXTI0
    EXTI1_Handler,  // IRQ 7: EXTI1
    EXTI1_Handler,  // IRQ 7: EXTI1
    EXTI2_Handler,  // IRQ 8: EXTI2
    EXTI2_Handler,  // IRQ 8: EXTI2
    EXTI3_Handler,  // IRQ 9: EXTI3
    EXTI3_Handler,  // IRQ 9: EXTI3
    EXTI4_Handler,  // IRQ 10: EXTI4
    EXTI4_Handler,  // IRQ 10: EXTI4
    DMA1_Stream0_Handler,  // IRQ 11: DMA1_Stream0
    DMA1_Stream0_Handler,  // IRQ 11: DMA1_Stream0
    DMA1_Stream1_Handler,  // IRQ 12: DMA1_Stream1
    DMA1_Stream1_Handler,  // IRQ 12: DMA1_Stream1
    DMA1_Stream2_Handler,  // IRQ 13: DMA1_Stream2
    DMA1_Stream2_Handler,  // IRQ 13: DMA1_Stream2
    DMA1_Stream3_Handler,  // IRQ 14: DMA1_Stream3
    DMA1_Stream3_Handler,  // IRQ 14: DMA1_Stream3
    DMA1_Stream4_Handler,  // IRQ 15: DMA1_Stream4
    DMA1_Stream4_Handler,  // IRQ 15: DMA1_Stream4
    DMA1_Stream5_Handler,  // IRQ 16: DMA1_Stream5
    DMA1_Stream5_Handler,  // IRQ 16: DMA1_Stream5
    DMA1_Stream6_Handler,  // IRQ 17: DMA1_Stream6
    DMA1_Stream6_Handler,  // IRQ 17: DMA1_Stream6
    ADC_Handler,  // IRQ 18: ADC
    ADC_Handler,  // IRQ 18: ADC
    ADC_Handler,  // IRQ 18: ADC
    ADC_Handler,  // IRQ 18: ADC
    ADC_Handler,  // IRQ 18: ADC
    ADC_Handler,  // IRQ 18: ADC
    CAN1_TX_Handler,  // IRQ 19: CAN1_TX
    CAN1_TX_Handler,  // IRQ 19: CAN1_TX
    CAN1_RX0_Handler,  // IRQ 20: CAN1_RX0
    CAN1_RX0_Handler,  // IRQ 20: CAN1_RX0
    CAN1_RX1_Handler,  // IRQ 21: CAN1_RX1
    CAN1_RX1_Handler,  // IRQ 21: CAN1_RX1
    CAN1_SCE_Handler,  // IRQ 22: CAN1_SCE
    CAN1_SCE_Handler,  // IRQ 22: CAN1_SCE
    EXTI9_5_Handler,  // IRQ 23: EXTI9_5
    EXTI9_5_Handler,  // IRQ 23: EXTI9_5
    TIM1_BRK_TIM9_Handler,  // IRQ 24: TIM1_BRK_TIM9
    TIM1_BRK_TIM9_Handler,  // IRQ 24: TIM1_BRK_TIM9
    TIM1_UP_TIM10_Handler,  // IRQ 25: TIM1_UP_TIM10
    TIM1_UP_TIM10_Handler,  // IRQ 25: TIM1_UP_TIM10
    TIM1_TRG_COM_TIM11_Handler,  // IRQ 26: TIM1_TRG_COM_TIM11
    TIM1_TRG_COM_TIM11_Handler,  // IRQ 26: TIM1_TRG_COM_TIM11
    TIM1_CC_Handler,  // IRQ 27: TIM1_CC
    TIM1_CC_Handler,  // IRQ 27: TIM1_CC
    TIM2_Handler,  // IRQ 28: TIM2
    TIM2_Handler,  // IRQ 28: TIM2
    TIM3_Handler,  // IRQ 29: TIM3
    TIM3_Handler,  // IRQ 29: TIM3
    TIM4_Handler,  // IRQ 30: TIM4
    TIM4_Handler,  // IRQ 30: TIM4
    I2C1_EV_Handler,  // IRQ 31: I2C1_EV
    I2C1_EV_Handler,  // IRQ 31: I2C1_EV
    I2C1_ER_Handler,  // IRQ 32: I2C1_ER
    I2C1_ER_Handler,  // IRQ 32: I2C1_ER
    I2C2_EV_Handler,  // IRQ 33: I2C2_EV
    I2C2_EV_Handler,  // IRQ 33: I2C2_EV
    I2C2_ER_Handler,  // IRQ 34: I2C2_ER
    I2C2_ER_Handler,  // IRQ 34: I2C2_ER
    SPI1_Handler,  // IRQ 35: SPI1
    SPI1_Handler,  // IRQ 35: SPI1
    SPI2_Handler,  // IRQ 36: SPI2
    SPI2_Handler,  // IRQ 36: SPI2
    USART1_Handler,  // IRQ 37: USART1
    USART1_Handler,  // IRQ 37: USART1
    USART2_Handler,  // IRQ 38: USART2
    USART2_Handler,  // IRQ 38: USART2
    USART3_Handler,  // IRQ 39: USART3
    USART3_Handler,  // IRQ 39: USART3
    EXTI15_10_Handler,  // IRQ 40: EXTI15_10
    EXTI15_10_Handler,  // IRQ 40: EXTI15_10
    RTC_Alarm_Handler,  // IRQ 41: RTC_Alarm
    RTC_Alarm_Handler,  // IRQ 41: RTC_Alarm
    OTG_FS_WKUP_Handler,  // IRQ 42: OTG_FS_WKUP
    OTG_FS_WKUP_Handler,  // IRQ 42: OTG_FS_WKUP
    TIM8_BRK_TIM12_Handler,  // IRQ 43: TIM8_BRK_TIM12
    TIM8_BRK_TIM12_Handler,  // IRQ 43: TIM8_BRK_TIM12
    TIM8_UP_TIM13_Handler,  // IRQ 44: TIM8_UP_TIM13
    TIM8_UP_TIM13_Handler,  // IRQ 44: TIM8_UP_TIM13
    TIM8_TRG_COM_TIM14_Handler,  // IRQ 45: TIM8_TRG_COM_TIM14
    TIM8_TRG_COM_TIM14_Handler,  // IRQ 45: TIM8_TRG_COM_TIM14
    TIM8_CC_Handler,  // IRQ 46: TIM8_CC
    TIM8_CC_Handler,  // IRQ 46: TIM8_CC
    DMA1_Stream7_Handler,  // IRQ 47: DMA1_Stream7
    DMA1_Stream7_Handler,  // IRQ 47: DMA1_Stream7
    FMC_Handler,  // IRQ 48: FMC
    FMC_Handler,  // IRQ 48: FMC
    TIM5_Handler,  // IRQ 50: TIM5
    TIM5_Handler,  // IRQ 50: TIM5
    SPI3_Handler,  // IRQ 51: SPI3
    SPI3_Handler,  // IRQ 51: SPI3
    UART4_Handler,  // IRQ 52: UART4
    UART4_Handler,  // IRQ 52: UART4
    UART5_Handler,  // IRQ 53: UART5
    UART5_Handler,  // IRQ 53: UART5
    TIM6_DAC_Handler,  // IRQ 54: TIM6_DAC
    TIM6_DAC_Handler,  // IRQ 54: TIM6_DAC
    TIM7_Handler,  // IRQ 55: TIM7
    TIM7_Handler,  // IRQ 55: TIM7
    DMA2_Stream0_Handler,  // IRQ 56: DMA2_Stream0
    DMA2_Stream0_Handler,  // IRQ 56: DMA2_Stream0
    DMA2_Stream1_Handler,  // IRQ 57: DMA2_Stream1
    DMA2_Stream1_Handler,  // IRQ 57: DMA2_Stream1
    DMA2_Stream2_Handler,  // IRQ 58: DMA2_Stream2
    DMA2_Stream2_Handler,  // IRQ 58: DMA2_Stream2
    DMA2_Stream3_Handler,  // IRQ 59: DMA2_Stream3
    DMA2_Stream3_Handler,  // IRQ 59: DMA2_Stream3
    DMA2_Stream4_Handler,  // IRQ 60: DMA2_Stream4
    DMA2_Stream4_Handler,  // IRQ 60: DMA2_Stream4
    ETH_Handler,  // IRQ 61: ETH
    ETH_Handler,  // IRQ 61: ETH
    ETH_WKUP_Handler,  // IRQ 62: ETH_WKUP
    ETH_WKUP_Handler,  // IRQ 62: ETH_WKUP
    CAN2_TX_Handler,  // IRQ 63: CAN2_TX
    CAN2_TX_Handler,  // IRQ 63: CAN2_TX
    CAN2_RX0_Handler,  // IRQ 64: CAN2_RX0
    CAN2_RX0_Handler,  // IRQ 64: CAN2_RX0
    CAN2_RX1_Handler,  // IRQ 65: CAN2_RX1
    CAN2_RX1_Handler,  // IRQ 65: CAN2_RX1
    CAN2_SCE_Handler,  // IRQ 66: CAN2_SCE
    CAN2_SCE_Handler,  // IRQ 66: CAN2_SCE
    OTG_FS_Handler,  // IRQ 67: OTG_FS
    OTG_FS_Handler,  // IRQ 67: OTG_FS
    DMA2_Stream5_Handler,  // IRQ 68: DMA2_Stream5
    DMA2_Stream5_Handler,  // IRQ 68: DMA2_Stream5
    DMA2_Stream6_Handler,  // IRQ 69: DMA2_Stream6
    DMA2_Stream6_Handler,  // IRQ 69: DMA2_Stream6
    DMA2_Stream7_Handler,  // IRQ 70: DMA2_Stream7
    DMA2_Stream7_Handler,  // IRQ 70: DMA2_Stream7
    USART6_Handler,  // IRQ 71: USART6
    USART6_Handler,  // IRQ 71: USART6
    I2C3_EV_Handler,  // IRQ 72: I2C3_EV
    I2C3_EV_Handler,  // IRQ 72: I2C3_EV
    I2C3_ER_Handler,  // IRQ 73: I2C3_ER
    I2C3_ER_Handler,  // IRQ 73: I2C3_ER
    DCMI_Handler,  // IRQ 78: DCMI
    DCMI_Handler,  // IRQ 78: DCMI
    FPU_Handler,  // IRQ 81: FPU
    FPU_Handler,  // IRQ 81: FPU
    UART7_Handler,  // IRQ 82: UART7
    UART7_Handler,  // IRQ 82: UART7
    UART8_Handler,  // IRQ 83: UART8
    UART8_Handler,  // IRQ 83: UART8
    SPI4_Handler,  // IRQ 84: SPI4
    SPI4_Handler,  // IRQ 84: SPI4
    LCD_TFT_Handler,  // IRQ 88: LCD_TFT
    LCD_TFT_Handler,  // IRQ 88: LCD_TFT
    LCD_TFT_1_Handler,  // IRQ 89: LCD_TFT_1
    LCD_TFT_1_Handler,  // IRQ 89: LCD_TFT_1
};
