/// Auto-generated bit field definitions for QUADSPI
/// Family: stm32f7
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>
#include "hal/utils/bitfield.hpp"

namespace alloy::hal::st::stm32f7::quadspi {

using namespace alloy::hal::bitfields;

// ============================================================================
// QUADSPI Bit Field Definitions
// ============================================================================

/// CR - control register
namespace cr {
    /// Enable
    /// Position: 0, Width: 1
    using EN = BitField<0, 1>;
    constexpr uint32_t EN_Pos = 0;
    constexpr uint32_t EN_Msk = EN::mask;

    /// Abort request
    /// Position: 1, Width: 1
    using ABORT = BitField<1, 1>;
    constexpr uint32_t ABORT_Pos = 1;
    constexpr uint32_t ABORT_Msk = ABORT::mask;

    /// DMA enable
    /// Position: 2, Width: 1
    using DMAEN = BitField<2, 1>;
    constexpr uint32_t DMAEN_Pos = 2;
    constexpr uint32_t DMAEN_Msk = DMAEN::mask;

    /// Timeout counter enable
    /// Position: 3, Width: 1
    using TCEN = BitField<3, 1>;
    constexpr uint32_t TCEN_Pos = 3;
    constexpr uint32_t TCEN_Msk = TCEN::mask;

    /// Sample shift
    /// Position: 4, Width: 1
    using SSHIFT = BitField<4, 1>;
    constexpr uint32_t SSHIFT_Pos = 4;
    constexpr uint32_t SSHIFT_Msk = SSHIFT::mask;

    /// Dual-flash mode
    /// Position: 6, Width: 1
    using DFM = BitField<6, 1>;
    constexpr uint32_t DFM_Pos = 6;
    constexpr uint32_t DFM_Msk = DFM::mask;

    /// FLASH memory selection
    /// Position: 7, Width: 1
    using FSEL = BitField<7, 1>;
    constexpr uint32_t FSEL_Pos = 7;
    constexpr uint32_t FSEL_Msk = FSEL::mask;

    /// IFO threshold level
    /// Position: 8, Width: 5
    using FTHRES = BitField<8, 5>;
    constexpr uint32_t FTHRES_Pos = 8;
    constexpr uint32_t FTHRES_Msk = FTHRES::mask;

    /// Transfer error interrupt enable
    /// Position: 16, Width: 1
    using TEIE = BitField<16, 1>;
    constexpr uint32_t TEIE_Pos = 16;
    constexpr uint32_t TEIE_Msk = TEIE::mask;

    /// Transfer complete interrupt enable
    /// Position: 17, Width: 1
    using TCIE = BitField<17, 1>;
    constexpr uint32_t TCIE_Pos = 17;
    constexpr uint32_t TCIE_Msk = TCIE::mask;

    /// FIFO threshold interrupt enable
    /// Position: 18, Width: 1
    using FTIE = BitField<18, 1>;
    constexpr uint32_t FTIE_Pos = 18;
    constexpr uint32_t FTIE_Msk = FTIE::mask;

    /// Status match interrupt enable
    /// Position: 19, Width: 1
    using SMIE = BitField<19, 1>;
    constexpr uint32_t SMIE_Pos = 19;
    constexpr uint32_t SMIE_Msk = SMIE::mask;

    /// TimeOut interrupt enable
    /// Position: 20, Width: 1
    using TOIE = BitField<20, 1>;
    constexpr uint32_t TOIE_Pos = 20;
    constexpr uint32_t TOIE_Msk = TOIE::mask;

    /// Automatic poll mode stop
    /// Position: 22, Width: 1
    using APMS = BitField<22, 1>;
    constexpr uint32_t APMS_Pos = 22;
    constexpr uint32_t APMS_Msk = APMS::mask;

    /// Polling match mode
    /// Position: 23, Width: 1
    using PMM = BitField<23, 1>;
    constexpr uint32_t PMM_Pos = 23;
    constexpr uint32_t PMM_Msk = PMM::mask;

    /// Clock prescaler
    /// Position: 24, Width: 8
    using PRESCALER = BitField<24, 8>;
    constexpr uint32_t PRESCALER_Pos = 24;
    constexpr uint32_t PRESCALER_Msk = PRESCALER::mask;

}  // namespace cr

/// DCR - device configuration register
namespace dcr {
    /// Mode 0 / mode 3
    /// Position: 0, Width: 1
    using CKMODE = BitField<0, 1>;
    constexpr uint32_t CKMODE_Pos = 0;
    constexpr uint32_t CKMODE_Msk = CKMODE::mask;

    /// Chip select high time
    /// Position: 8, Width: 3
    using CSHT = BitField<8, 3>;
    constexpr uint32_t CSHT_Pos = 8;
    constexpr uint32_t CSHT_Msk = CSHT::mask;

    /// FLASH memory size
    /// Position: 16, Width: 5
    using FSIZE = BitField<16, 5>;
    constexpr uint32_t FSIZE_Pos = 16;
    constexpr uint32_t FSIZE_Msk = FSIZE::mask;

}  // namespace dcr

/// SR - status register
namespace sr {
    /// Transfer error flag
    /// Position: 0, Width: 1
    using TEF = BitField<0, 1>;
    constexpr uint32_t TEF_Pos = 0;
    constexpr uint32_t TEF_Msk = TEF::mask;

    /// Transfer complete flag
    /// Position: 1, Width: 1
    using TCF = BitField<1, 1>;
    constexpr uint32_t TCF_Pos = 1;
    constexpr uint32_t TCF_Msk = TCF::mask;

    /// FIFO threshold flag
    /// Position: 2, Width: 1
    using FTF = BitField<2, 1>;
    constexpr uint32_t FTF_Pos = 2;
    constexpr uint32_t FTF_Msk = FTF::mask;

    /// Status match flag
    /// Position: 3, Width: 1
    using SMF = BitField<3, 1>;
    constexpr uint32_t SMF_Pos = 3;
    constexpr uint32_t SMF_Msk = SMF::mask;

    /// Timeout flag
    /// Position: 4, Width: 1
    using TOF = BitField<4, 1>;
    constexpr uint32_t TOF_Pos = 4;
    constexpr uint32_t TOF_Msk = TOF::mask;

    /// Busy
    /// Position: 5, Width: 1
    using BUSY = BitField<5, 1>;
    constexpr uint32_t BUSY_Pos = 5;
    constexpr uint32_t BUSY_Msk = BUSY::mask;

    /// FIFO level
    /// Position: 8, Width: 7
    using FLEVEL = BitField<8, 7>;
    constexpr uint32_t FLEVEL_Pos = 8;
    constexpr uint32_t FLEVEL_Msk = FLEVEL::mask;

}  // namespace sr

/// FCR - flag clear register
namespace fcr {
    /// Clear transfer error flag
    /// Position: 0, Width: 1
    using CTEF = BitField<0, 1>;
    constexpr uint32_t CTEF_Pos = 0;
    constexpr uint32_t CTEF_Msk = CTEF::mask;

    /// Clear transfer complete flag
    /// Position: 1, Width: 1
    using CTCF = BitField<1, 1>;
    constexpr uint32_t CTCF_Pos = 1;
    constexpr uint32_t CTCF_Msk = CTCF::mask;

    /// Clear status match flag
    /// Position: 3, Width: 1
    using CSMF = BitField<3, 1>;
    constexpr uint32_t CSMF_Pos = 3;
    constexpr uint32_t CSMF_Msk = CSMF::mask;

    /// Clear timeout flag
    /// Position: 4, Width: 1
    using CTOF = BitField<4, 1>;
    constexpr uint32_t CTOF_Pos = 4;
    constexpr uint32_t CTOF_Msk = CTOF::mask;

}  // namespace fcr

/// DLR - data length register
namespace dlr {
    /// Data length
    /// Position: 0, Width: 32
    using DL = BitField<0, 32>;
    constexpr uint32_t DL_Pos = 0;
    constexpr uint32_t DL_Msk = DL::mask;

}  // namespace dlr

/// CCR - communication configuration register
namespace ccr {
    /// Instruction
    /// Position: 0, Width: 8
    using INSTRUCTION = BitField<0, 8>;
    constexpr uint32_t INSTRUCTION_Pos = 0;
    constexpr uint32_t INSTRUCTION_Msk = INSTRUCTION::mask;

    /// Instruction mode
    /// Position: 8, Width: 2
    using IMODE = BitField<8, 2>;
    constexpr uint32_t IMODE_Pos = 8;
    constexpr uint32_t IMODE_Msk = IMODE::mask;

    /// Address mode
    /// Position: 10, Width: 2
    using ADMODE = BitField<10, 2>;
    constexpr uint32_t ADMODE_Pos = 10;
    constexpr uint32_t ADMODE_Msk = ADMODE::mask;

    /// Address size
    /// Position: 12, Width: 2
    using ADSIZE = BitField<12, 2>;
    constexpr uint32_t ADSIZE_Pos = 12;
    constexpr uint32_t ADSIZE_Msk = ADSIZE::mask;

    /// Alternate bytes mode
    /// Position: 14, Width: 2
    using ABMODE = BitField<14, 2>;
    constexpr uint32_t ABMODE_Pos = 14;
    constexpr uint32_t ABMODE_Msk = ABMODE::mask;

    /// Alternate bytes size
    /// Position: 16, Width: 2
    using ABSIZE = BitField<16, 2>;
    constexpr uint32_t ABSIZE_Pos = 16;
    constexpr uint32_t ABSIZE_Msk = ABSIZE::mask;

    /// Number of dummy cycles
    /// Position: 18, Width: 5
    using DCYC = BitField<18, 5>;
    constexpr uint32_t DCYC_Pos = 18;
    constexpr uint32_t DCYC_Msk = DCYC::mask;

    /// Data mode
    /// Position: 24, Width: 2
    using DMODE = BitField<24, 2>;
    constexpr uint32_t DMODE_Pos = 24;
    constexpr uint32_t DMODE_Msk = DMODE::mask;

    /// Functional mode
    /// Position: 26, Width: 2
    using FMODE = BitField<26, 2>;
    constexpr uint32_t FMODE_Pos = 26;
    constexpr uint32_t FMODE_Msk = FMODE::mask;

    /// Send instruction only once mode
    /// Position: 28, Width: 1
    using SIOO = BitField<28, 1>;
    constexpr uint32_t SIOO_Pos = 28;
    constexpr uint32_t SIOO_Msk = SIOO::mask;

    /// DDR hold half cycle
    /// Position: 30, Width: 1
    using DHHC = BitField<30, 1>;
    constexpr uint32_t DHHC_Pos = 30;
    constexpr uint32_t DHHC_Msk = DHHC::mask;

    /// Double data rate mode
    /// Position: 31, Width: 1
    using DDRM = BitField<31, 1>;
    constexpr uint32_t DDRM_Pos = 31;
    constexpr uint32_t DDRM_Msk = DDRM::mask;

}  // namespace ccr

/// AR - address register
namespace ar {
    /// Address
    /// Position: 0, Width: 32
    using ADDRESS = BitField<0, 32>;
    constexpr uint32_t ADDRESS_Pos = 0;
    constexpr uint32_t ADDRESS_Msk = ADDRESS::mask;

}  // namespace ar

/// ABR - ABR
namespace abr {
    /// ALTERNATE
    /// Position: 0, Width: 32
    using ALTERNATE = BitField<0, 32>;
    constexpr uint32_t ALTERNATE_Pos = 0;
    constexpr uint32_t ALTERNATE_Msk = ALTERNATE::mask;

}  // namespace abr

/// DR - data register
namespace dr {
    /// Data
    /// Position: 0, Width: 32
    using DATA = BitField<0, 32>;
    constexpr uint32_t DATA_Pos = 0;
    constexpr uint32_t DATA_Msk = DATA::mask;

}  // namespace dr

/// PSMKR - polling status mask register
namespace psmkr {
    /// Status mask
    /// Position: 0, Width: 32
    using MASK = BitField<0, 32>;
    constexpr uint32_t MASK_Pos = 0;
    constexpr uint32_t MASK_Msk = MASK::mask;

}  // namespace psmkr

/// PSMAR - polling status match register
namespace psmar {
    /// Status match
    /// Position: 0, Width: 32
    using MATCH = BitField<0, 32>;
    constexpr uint32_t MATCH_Pos = 0;
    constexpr uint32_t MATCH_Msk = MATCH::mask;

}  // namespace psmar

/// PIR - polling interval register
namespace pir {
    /// Polling interval
    /// Position: 0, Width: 16
    using INTERVAL = BitField<0, 16>;
    constexpr uint32_t INTERVAL_Pos = 0;
    constexpr uint32_t INTERVAL_Msk = INTERVAL::mask;

}  // namespace pir

/// LPTR - low-power timeout register
namespace lptr {
    /// Timeout period
    /// Position: 0, Width: 16
    using TIMEOUT = BitField<0, 16>;
    constexpr uint32_t TIMEOUT_Pos = 0;
    constexpr uint32_t TIMEOUT_Msk = TIMEOUT::mask;

}  // namespace lptr

}  // namespace alloy::hal::st::stm32f7::quadspi
