/// Auto-generated peripheral definitions for STM32G441xx
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_STM32G441XX_PERIPHERALS_HPP
#define ALLOY_GENERATED_STM32G441XX_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::stm32g441xx {

/// Basic peripheral base addresses
namespace peripherals {
    // Peripheral addresses will be added here
    // This is a minimal implementation
}

} // namespace alloy::generated::stm32g441xx

#endif // ALLOY_GENERATED_STM32G441XX_PERIPHERALS_HPP
