/// Auto-generated peripheral definitions for STM32F101xx
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_STM32F101XX_PERIPHERALS_HPP
#define UCORE_GENERATED_STM32F101XX_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::stm32f101xx {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::stm32f101xx

#endif  // ALLOY_GENERATED_STM32F101XX_PERIPHERALS_HPP
