/// Auto-generated register definitions for PMC
/// Device: ATSAM3X8E
/// Vendor: Atmel
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::pmc {

// ============================================================================
// PMC - Power Management Controller
// Base Address: 0x400E0600
// ============================================================================

/// PMC Register Structure
struct PMC_Registers {

    /// System Clock Enable Register
    /// Offset: 0x0000
    /// Access: write-only
    volatile uint32_t PMC_SCER;

    /// System Clock Disable Register
    /// Offset: 0x0004
    /// Access: write-only
    volatile uint32_t PMC_SCDR;

    /// System Clock Status Register
    /// Offset: 0x0008
    /// Reset value: 0x00000001
    /// Access: read-only
    volatile uint32_t PMC_SCSR;
    uint8_t RESERVED_000C[4]; ///< Reserved

    /// Peripheral Clock Enable Register 0
    /// Offset: 0x0010
    /// Access: write-only
    volatile uint32_t PMC_PCER0;

    /// Peripheral Clock Disable Register 0
    /// Offset: 0x0014
    /// Access: write-only
    volatile uint32_t PMC_PCDR0;

    /// Peripheral Clock Status Register 0
    /// Offset: 0x0018
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PMC_PCSR0;

    /// UTMI Clock Register
    /// Offset: 0x001C
    /// Reset value: 0x10200800
    /// Access: read-write
    volatile uint32_t CKGR_UCKR;

    /// Main Oscillator Register
    /// Offset: 0x0020
    /// Reset value: 0x00000008
    /// Access: read-write
    volatile uint32_t CKGR_MOR;

    /// Main Clock Frequency Register
    /// Offset: 0x0024
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t CKGR_MCFR;

    /// PLLA Register
    /// Offset: 0x0028
    /// Reset value: 0x00003F00
    /// Access: read-write
    volatile uint32_t CKGR_PLLAR;
    uint8_t RESERVED_002C[4]; ///< Reserved

    /// Master Clock Register
    /// Offset: 0x0030
    /// Reset value: 0x00000001
    /// Access: read-write
    volatile uint32_t PMC_MCKR;
    uint8_t RESERVED_0034[4]; ///< Reserved

    /// USB Clock Register
    /// Offset: 0x0038
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PMC_USB;
    uint8_t RESERVED_003C[4]; ///< Reserved

    /// Programmable Clock 0 Register
    /// Offset: 0x0040
    /// Access: read-write
    volatile uint32_t PMC_PCK[3];
    uint8_t RESERVED_0044[28]; ///< Reserved

    /// Interrupt Enable Register
    /// Offset: 0x0060
    /// Access: write-only
    volatile uint32_t PMC_IER;

    /// Interrupt Disable Register
    /// Offset: 0x0064
    /// Access: write-only
    volatile uint32_t PMC_IDR;

    /// Status Register
    /// Offset: 0x0068
    /// Reset value: 0x00010008
    /// Access: read-only
    volatile uint32_t PMC_SR;

    /// Interrupt Mask Register
    /// Offset: 0x006C
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PMC_IMR;

    /// Fast Start-up Mode Register
    /// Offset: 0x0070
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PMC_FSMR;

    /// Fast Start-up Polarity Register
    /// Offset: 0x0074
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PMC_FSPR;

    /// Fault Output Clear Register
    /// Offset: 0x0078
    /// Access: write-only
    volatile uint32_t PMC_FOCR;
    uint8_t RESERVED_007C[104]; ///< Reserved

    /// Write Protect Mode Register
    /// Offset: 0x00E4
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PMC_WPMR;

    /// Write Protect Status Register
    /// Offset: 0x00E8
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PMC_WPSR;
    uint8_t RESERVED_00EC[20]; ///< Reserved

    /// Peripheral Clock Enable Register 1
    /// Offset: 0x0100
    /// Access: write-only
    volatile uint32_t PMC_PCER1;

    /// Peripheral Clock Disable Register 1
    /// Offset: 0x0104
    /// Access: write-only
    volatile uint32_t PMC_PCDR1;

    /// Peripheral Clock Status Register 1
    /// Offset: 0x0108
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PMC_PCSR1;

    /// Peripheral Control Register
    /// Offset: 0x010C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PMC_PCR;
};

static_assert(sizeof(PMC_Registers) >= 272, "PMC_Registers size mismatch");

/// PMC peripheral instance
constexpr PMC_Registers* PMC = 
    reinterpret_cast<PMC_Registers*>(0x400E0600);

}  // namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::pmc
