/// Auto-generated register definitions for TWI1
/// Device: ATSAM3X8E
/// Vendor: Atmel
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::twi1 {

// ============================================================================
// TWI1 - Two-wire Interface 1
// Base Address: 0x40090000
// ============================================================================

/// TWI1 Register Structure
struct TWI1_Registers {

    /// Control Register
    /// Offset: 0x0000
    /// Access: write-only
    volatile uint32_t CR;

    /// Master Mode Register
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t MMR;

    /// Slave Mode Register
    /// Offset: 0x0008
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t SMR;

    /// Internal Address Register
    /// Offset: 0x000C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t IADR;

    /// Clock Waveform Generator Register
    /// Offset: 0x0010
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t CWGR;
    uint8_t RESERVED_0014[12]; ///< Reserved

    /// Status Register
    /// Offset: 0x0020
    /// Reset value: 0x0000F009
    /// Access: read-only
    volatile uint32_t SR;

    /// Interrupt Enable Register
    /// Offset: 0x0024
    /// Access: write-only
    volatile uint32_t IER;

    /// Interrupt Disable Register
    /// Offset: 0x0028
    /// Access: write-only
    volatile uint32_t IDR;

    /// Interrupt Mask Register
    /// Offset: 0x002C
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t IMR;

    /// Receive Holding Register
    /// Offset: 0x0030
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t RHR;

    /// Transmit Holding Register
    /// Offset: 0x0034
    /// Reset value: 0x00000000
    /// Access: write-only
    volatile uint32_t THR;
    uint8_t RESERVED_0038[200]; ///< Reserved

    /// Receive Pointer Register
    /// Offset: 0x0100
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t RPR;

    /// Receive Counter Register
    /// Offset: 0x0104
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t RCR;

    /// Transmit Pointer Register
    /// Offset: 0x0108
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t TPR;

    /// Transmit Counter Register
    /// Offset: 0x010C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t TCR;

    /// Receive Next Pointer Register
    /// Offset: 0x0110
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t RNPR;

    /// Receive Next Counter Register
    /// Offset: 0x0114
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t RNCR;

    /// Transmit Next Pointer Register
    /// Offset: 0x0118
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t TNPR;

    /// Transmit Next Counter Register
    /// Offset: 0x011C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t TNCR;

    /// Transfer Control Register
    /// Offset: 0x0120
    /// Reset value: 0x00000000
    /// Access: write-only
    volatile uint32_t PTCR;

    /// Transfer Status Register
    /// Offset: 0x0124
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PTSR;
};

static_assert(sizeof(TWI1_Registers) >= 296, "TWI1_Registers size mismatch");

/// TWI1 peripheral instance
constexpr TWI1_Registers* TWI1 = 
    reinterpret_cast<TWI1_Registers*>(0x40090000);

}  // namespace alloy::hal::atmel::atsam3x8e::atsam3x8e::twi1
