/// Auto-generated register definitions for UART5
/// Family: stm32f1
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>

namespace alloy::hal::st::stm32f1::uart5 {

// ============================================================================
// UART5 - Universal asynchronous receiver transmitter
// Base Address: 0x40005000
// ============================================================================

/// UART5 Register Structure
struct UART5_Registers {
    /// UART4_SR
    /// Offset: 0x0000
    /// Reset value: 0x00000000
    volatile uint32_t SR;

    /// UART4_DR
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t DR;

    /// UART4_BRR
    /// Offset: 0x0008
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t BRR;

    /// UART4_CR1
    /// Offset: 0x000C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t CR1;

    /// UART4_CR2
    /// Offset: 0x0010
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t CR2;

    /// UART4_CR3
    /// Offset: 0x0014
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t CR3;
};

static_assert(sizeof(UART5_Registers) >= 24, "UART5_Registers size mismatch");

/// UART5 peripheral instance
inline UART5_Registers* UART5() {
    return reinterpret_cast<UART5_Registers*>(0x40005000);
}

}  // namespace alloy::hal::st::stm32f1::uart5
