/// Auto-generated startup code for STM32F105xx
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#include <cstdint>
#include <cstring>

// Linker script symbols
extern uint32_t _sidata;  // Start of .data in flash
extern uint32_t _sdata;   // Start of .data in RAM
extern uint32_t _edata;   // End of .data in RAM
extern uint32_t _sbss;    // Start of .bss
extern uint32_t _ebss;    // End of .bss

// Stack top (defined in linker script)
extern uint32_t _estack;

// User application entry point
extern "C" int main();

// System initialization (weak, can be overridden)
extern "C" void SystemInit() __attribute__((weak));
extern "C" void SystemInit() {}

// Default handler for unhandled interrupts
extern "C" [[noreturn]] void Default_Handler() {
    while (true) {
        // Trap
    }
}

// Interrupt handlers (weak, can be overridden)
extern "C" void WWDG_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void PVD_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TAMPER_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RTC_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void FLASH_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RCC_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI0_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI4_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel4_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel5_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel6_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA1_Channel7_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ADC_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_TX_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_RX0_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_RX1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_SCE_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI9_5_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_BRK_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_UP_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_TRG_COM_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM1_CC_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM4_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C1_EV_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C1_ER_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C2_EV_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void I2C2_ER_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EXTI15_10_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void RTCAlarm_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM5_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART4_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART5_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM6_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TIM7_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Channel1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Channel2_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Channel3_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Channel4_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMA2_Channel5_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_TX_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_RX0_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_RX1_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN2_SCE_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void OTG_FS_IRQ_Handler() __attribute__((weak, alias("Default_Handler")));

// Reset Handler - Entry point after reset
extern "C" [[noreturn]] void Reset_Handler() {
    // 1. Copy .data section from Flash to RAM
    uint32_t* src = &_sidata;
    uint32_t* dest = &_sdata;
    while (dest < &_edata) {
        *dest++ = *src++;
    }

    // 2. Zero out .bss section
    dest = &_sbss;
    while (dest < &_ebss) {
        *dest++ = 0;
    }

    // 3. Call system initialization
    SystemInit();

    // 4. Call static constructors
    extern void (*__init_array_start[])();
    extern void (*__init_array_end[])();
    for (auto ctor = __init_array_start; ctor < __init_array_end; ++ctor) {
        (*ctor)();
    }

    // 5. Call main
    main();

    // 6. If main returns, loop forever
    while (true) {}
}

// Vector table
__attribute__((section(".isr_vector"), used)) void (*const vector_table[])() = {
    reinterpret_cast<void (*)()>(&_estack),  // Initial stack pointer
    Reset_Handler,                           // Reset handler
    WWDG_IRQ_Handler,                        // IRQ 0: WWDG_IRQ
    PVD_IRQ_Handler,                         // IRQ 1: PVD_IRQ
    TAMPER_IRQ_Handler,                      // IRQ 2: TAMPER_IRQ
    RTC_IRQ_Handler,                         // IRQ 3: RTC_IRQ
    FLASH_IRQ_Handler,                       // IRQ 4: FLASH_IRQ
    RCC_IRQ_Handler,                         // IRQ 5: RCC_IRQ
    RCC_IRQ_Handler,                         // IRQ 5: RCC_IRQ
    EXTI0_IRQ_Handler,                       // IRQ 6: EXTI0_IRQ
    EXTI1_IRQ_Handler,                       // IRQ 7: EXTI1_IRQ
    EXTI2_IRQ_Handler,                       // IRQ 8: EXTI2_IRQ
    EXTI3_IRQ_Handler,                       // IRQ 9: EXTI3_IRQ
    EXTI4_IRQ_Handler,                       // IRQ 10: EXTI4_IRQ
    DMA1_Channel1_IRQ_Handler,               // IRQ 11: DMA1_Channel1_IRQ
    DMA1_Channel2_IRQ_Handler,               // IRQ 12: DMA1_Channel2_IRQ
    DMA1_Channel3_IRQ_Handler,               // IRQ 13: DMA1_Channel3_IRQ
    DMA1_Channel4_IRQ_Handler,               // IRQ 14: DMA1_Channel4_IRQ
    DMA1_Channel5_IRQ_Handler,               // IRQ 15: DMA1_Channel5_IRQ
    DMA1_Channel6_IRQ_Handler,               // IRQ 16: DMA1_Channel6_IRQ
    DMA1_Channel7_IRQ_Handler,               // IRQ 17: DMA1_Channel7_IRQ
    ADC_IRQ_Handler,                         // IRQ 18: ADC_IRQ
    ADC_IRQ_Handler,                         // IRQ 18: ADC_IRQ
    CAN1_TX_IRQ_Handler,                     // IRQ 19: CAN1_TX_IRQ
    CAN1_RX0_IRQ_Handler,                    // IRQ 20: CAN1_RX0_IRQ
    CAN1_RX1_IRQ_Handler,                    // IRQ 21: CAN1_RX1_IRQ
    CAN1_SCE_IRQ_Handler,                    // IRQ 22: CAN1_SCE_IRQ
    EXTI9_5_IRQ_Handler,                     // IRQ 23: EXTI9_5_IRQ
    TIM1_BRK_IRQ_Handler,                    // IRQ 24: TIM1_BRK_IRQ
    TIM1_UP_IRQ_Handler,                     // IRQ 25: TIM1_UP_IRQ
    TIM1_TRG_COM_IRQ_Handler,                // IRQ 26: TIM1_TRG_COM_IRQ
    TIM1_CC_IRQ_Handler,                     // IRQ 27: TIM1_CC_IRQ
    TIM2_IRQ_Handler,                        // IRQ 28: TIM2_IRQ
    TIM3_IRQ_Handler,                        // IRQ 29: TIM3_IRQ
    TIM4_IRQ_Handler,                        // IRQ 30: TIM4_IRQ
    I2C1_EV_IRQ_Handler,                     // IRQ 31: I2C1_EV_IRQ
    I2C1_ER_IRQ_Handler,                     // IRQ 32: I2C1_ER_IRQ
    I2C2_EV_IRQ_Handler,                     // IRQ 33: I2C2_EV_IRQ
    I2C2_ER_IRQ_Handler,                     // IRQ 34: I2C2_ER_IRQ
    SPI1_IRQ_Handler,                        // IRQ 35: SPI1_IRQ
    SPI2_IRQ_Handler,                        // IRQ 36: SPI2_IRQ
    USART1_IRQ_Handler,                      // IRQ 37: USART1_IRQ
    USART2_IRQ_Handler,                      // IRQ 38: USART2_IRQ
    USART3_IRQ_Handler,                      // IRQ 39: USART3_IRQ
    EXTI15_10_IRQ_Handler,                   // IRQ 40: EXTI15_10_IRQ
    RTCAlarm_IRQ_Handler,                    // IRQ 41: RTCAlarm_IRQ
    TIM5_IRQ_Handler,                        // IRQ 50: TIM5_IRQ
    SPI3_IRQ_Handler,                        // IRQ 51: SPI3_IRQ
    UART4_IRQ_Handler,                       // IRQ 52: UART4_IRQ
    UART5_IRQ_Handler,                       // IRQ 53: UART5_IRQ
    TIM6_IRQ_Handler,                        // IRQ 54: TIM6_IRQ
    TIM7_IRQ_Handler,                        // IRQ 55: TIM7_IRQ
    DMA2_Channel1_IRQ_Handler,               // IRQ 56: DMA2_Channel1_IRQ
    DMA2_Channel2_IRQ_Handler,               // IRQ 57: DMA2_Channel2_IRQ
    DMA2_Channel3_IRQ_Handler,               // IRQ 58: DMA2_Channel3_IRQ
    DMA2_Channel4_IRQ_Handler,               // IRQ 59: DMA2_Channel4_IRQ
    DMA2_Channel5_IRQ_Handler,               // IRQ 60: DMA2_Channel5_IRQ
    CAN2_TX_IRQ_Handler,                     // IRQ 63: CAN2_TX_IRQ
    CAN2_RX0_IRQ_Handler,                    // IRQ 64: CAN2_RX0_IRQ
    CAN2_RX1_IRQ_Handler,                    // IRQ 65: CAN2_RX1_IRQ
    CAN2_SCE_IRQ_Handler,                    // IRQ 66: CAN2_SCE_IRQ
    OTG_FS_IRQ_Handler,                      // IRQ 67: OTG_FS_IRQ
};
