/// Auto-generated register definitions for AES
/// Device: ATSAMV71J20B
/// Vendor: Microchip Technology
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <stdint.h>

namespace alloy::hal::atmel::samv71::atsamv71j20b::aes {

// ============================================================================
// AES - Advanced Encryption Standard
// Base Address: 0x4006C000
// ============================================================================

/// AES Register Structure
struct AES_Registers {

    /// Control Register
    /// Offset: 0x0000
    /// Access: write-only
    volatile uint32_t CR;

    /// Mode Register
    /// Offset: 0x0004
    volatile uint32_t MR;
    uint8_t RESERVED_0008[8]; ///< Reserved

    /// Interrupt Enable Register
    /// Offset: 0x0010
    /// Access: write-only
    volatile uint32_t IER;

    /// Interrupt Disable Register
    /// Offset: 0x0014
    /// Access: write-only
    volatile uint32_t IDR;

    /// Interrupt Mask Register
    /// Offset: 0x0018
    /// Access: read-only
    volatile uint32_t IMR;

    /// Interrupt Status Register
    /// Offset: 0x001C
    /// Access: read-only
    volatile uint32_t ISR;

    /// Key Word Register
    /// Offset: 0x0020
    /// Access: write-only
    volatile uint32_t KEYWR[8][8];

    /// Input Data Register
    /// Offset: 0x0040
    /// Access: write-only
    volatile uint32_t IDATAR[4][4];

    /// Output Data Register
    /// Offset: 0x0050
    /// Access: read-only
    volatile uint32_t ODATAR[4][4];

    /// Initialization Vector Register
    /// Offset: 0x0060
    /// Access: write-only
    volatile uint32_t IVR[4][4];

    /// Additional Authenticated Data Length Register
    /// Offset: 0x0070
    volatile uint32_t AADLENR;

    /// Plaintext/Ciphertext Length Register
    /// Offset: 0x0074
    volatile uint32_t CLENR;

    /// GCM Intermediate Hash Word Register
    /// Offset: 0x0078
    volatile uint32_t GHASHR[4][4];

    /// GCM Authentication Tag Word Register
    /// Offset: 0x0088
    /// Access: read-only
    volatile uint32_t TAGR[4][4];

    /// GCM Encryption Counter Value Register
    /// Offset: 0x0098
    /// Access: read-only
    volatile uint32_t CTRR;

    /// GCM H Word Register
    /// Offset: 0x009C
    volatile uint32_t GCMHR[4][4];
};

static_assert(sizeof(AES_Registers) >= 172, "AES_Registers size mismatch");

/// AES peripheral instance
inline AES_Registers* AES() {
    return reinterpret_cast<AES_Registers*>(0x4006C000);
}

}  // namespace alloy::hal::atmel::samv71::atsamv71j20b::aes
