/// Auto-generated peripheral definitions for ATSAME53N20A
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_ATSAME53N20A_PERIPHERALS_HPP
#define UCORE_GENERATED_ATSAME53N20A_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::atsame53n20a {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::atsame53n20a

#endif  // ALLOY_GENERATED_ATSAME53N20A_PERIPHERALS_HPP
