/// Auto-generated startup code for ATSAM3X8C
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#include <cstdint>
#include <cstring>

// Linker script symbols
extern uint32_t _sidata;  // Start of .data in flash
extern uint32_t _sdata;   // Start of .data in RAM
extern uint32_t _edata;   // End of .data in RAM
extern uint32_t _sbss;    // Start of .bss
extern uint32_t _ebss;    // End of .bss

// Stack top (defined in linker script)
extern uint32_t _estack;

// User application entry point
extern "C" int main();

// System initialization (weak, can be overridden)
extern "C" void SystemInit() __attribute__((weak));
extern "C" void SystemInit() {}

// Default handler for unhandled interrupts
extern "C" [[noreturn]] void Default_Handler() {
    while (true) {
        // Trap
    }
}

// Interrupt handlers (weak, can be overridden)
extern "C" void PMC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EFC0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EFC1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UART_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void PIOA_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void PIOB_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void USART2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void HSMCI_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TWI0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TWI1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SPI0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void SSC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC1_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC2_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC3_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC4_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TC5_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void PWM_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void ADC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DACC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void DMAC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void UOTGHS_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void TRNG_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void EMAC_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN0_Handler() __attribute__((weak, alias("Default_Handler")));
extern "C" void CAN1_Handler() __attribute__((weak, alias("Default_Handler")));

// Reset Handler - Entry point after reset
extern "C" [[noreturn]] void Reset_Handler() {
    // 1. Copy .data section from Flash to RAM
    uint32_t* src = &_sidata;
    uint32_t* dest = &_sdata;
    while (dest < &_edata) {
        *dest++ = *src++;
    }

    // 2. Zero out .bss section
    dest = &_sbss;
    while (dest < &_ebss) {
        *dest++ = 0;
    }

    // 3. Call system initialization
    SystemInit();

    // 4. Call static constructors
    extern void (*__init_array_start[])();
    extern void (*__init_array_end[])();
    for (auto ctor = __init_array_start; ctor < __init_array_end; ++ctor) {
        (*ctor)();
    }

    // 5. Call main
    main();

    // 6. If main returns, loop forever
    while (true) {}
}

// Vector table
__attribute__((section(".isr_vector"), used)) void (*const vector_table[])() = {
    reinterpret_cast<void (*)()>(&_estack),  // Initial stack pointer
    Reset_Handler,                           // Reset handler
    PMC_Handler,                             // IRQ 5: PMC
    EFC0_Handler,                            // IRQ 6: EFC0
    EFC1_Handler,                            // IRQ 7: EFC1
    UART_Handler,                            // IRQ 8: UART
    PIOA_Handler,                            // IRQ 11: PIOA
    PIOB_Handler,                            // IRQ 12: PIOB
    USART0_Handler,                          // IRQ 17: USART0
    USART1_Handler,                          // IRQ 18: USART1
    USART2_Handler,                          // IRQ 19: USART2
    HSMCI_Handler,                           // IRQ 21: HSMCI
    TWI0_Handler,                            // IRQ 22: TWI0
    TWI1_Handler,                            // IRQ 23: TWI1
    SPI0_Handler,                            // IRQ 24: SPI0
    SSC_Handler,                             // IRQ 26: SSC
    TC0_Handler,                             // IRQ 27: TC0
    TC1_Handler,                             // IRQ 28: TC1
    TC2_Handler,                             // IRQ 29: TC2
    TC3_Handler,                             // IRQ 30: TC3
    TC4_Handler,                             // IRQ 31: TC4
    TC5_Handler,                             // IRQ 32: TC5
    PWM_Handler,                             // IRQ 36: PWM
    ADC_Handler,                             // IRQ 37: ADC
    DACC_Handler,                            // IRQ 38: DACC
    DMAC_Handler,                            // IRQ 39: DMAC
    UOTGHS_Handler,                          // IRQ 40: UOTGHS
    TRNG_Handler,                            // IRQ 41: TRNG
    EMAC_Handler,                            // IRQ 42: EMAC
    CAN0_Handler,                            // IRQ 43: CAN0
    CAN1_Handler,                            // IRQ 44: CAN1
};
