/// Auto-generated register definitions for Ethernet_PTP
/// Device: STM32F407
/// Vendor: STMicro
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::st::stm32f4::stm32f407::ethernet_ptp {

// ============================================================================
// Ethernet_PTP - Ethernet: Precision time protocol
// Base Address: 0x40028700
// ============================================================================

/// Ethernet_PTP Register Structure
struct Ethernet_PTP_Registers {

    /// Ethernet PTP time stamp control
          register
    /// Offset: 0x0000
    /// Reset value: 0x00002000
    /// Access: read-write
    volatile uint32_t PTPTSCR;

    /// Ethernet PTP subsecond increment
          register
    /// Offset: 0x0004
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPSSIR;

    /// Ethernet PTP time stamp high
          register
    /// Offset: 0x0008
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PTPTSHR;

    /// Ethernet PTP time stamp low
          register
    /// Offset: 0x000C
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PTPTSLR;

    /// Ethernet PTP time stamp high update
          register
    /// Offset: 0x0010
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPTSHUR;

    /// Ethernet PTP time stamp low update
          register
    /// Offset: 0x0014
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPTSLUR;

    /// Ethernet PTP time stamp addend
          register
    /// Offset: 0x0018
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPTSAR;

    /// Ethernet PTP target time high
          register
    /// Offset: 0x001C
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPTTHR;

    /// Ethernet PTP target time low
          register
    /// Offset: 0x0020
    /// Reset value: 0x00000000
    /// Access: read-write
    volatile uint32_t PTPTTLR;
    uint8_t RESERVED_0024[4]; ///< Reserved

    /// Ethernet PTP time stamp status
          register
    /// Offset: 0x0028
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PTPTSSR;

    /// Ethernet PTP PPS control
          register
    /// Offset: 0x002C
    /// Reset value: 0x00000000
    /// Access: read-only
    volatile uint32_t PTPPPSCR;
};

static_assert(sizeof(Ethernet_PTP_Registers) >= 48, "Ethernet_PTP_Registers size mismatch");

/// Ethernet_PTP peripheral instance
constexpr Ethernet_PTP_Registers* Ethernet_PTP = 
    reinterpret_cast<Ethernet_PTP_Registers*>(0x40028700);

}  // namespace alloy::hal::st::stm32f4::stm32f407::ethernet_ptp
