/// Complete Register Map for ATSAMV71N21B
/// Generated by Alloy Code Generator from CMSIS-SVD
///
/// Device:  ATSAMV71N21B
/// Vendor:  Microchip Technology
/// Family:  samv71
/// CPU:     CM7
///
/// This is the main convenience header that includes all generated
/// register definitions, bit fields, enumerations, and utilities.
///
/// Usage:
///   #include <hal/atmel/samv71/atsamv71n21b/register_map.hpp>
///
///   using namespace alloy::hal::atmel::samv71::atsamv71n21b;
///
///   // Access registers
///   rcc::RCC->CR = rcc::cr::HSEON::set(rcc::RCC->CR);
///
/// DO NOT EDIT - Regenerate if SVD file changes

#pragma once

// ============================================================================
// Core utilities
// ============================================================================

// ============================================================================
// Peripheral Register Structures (Family Level)
// ============================================================================

#include "../registers/acc_registers.hpp"
#include "../registers/aes_registers.hpp"
#include "../registers/afec0_registers.hpp"
#include "../registers/chipid_registers.hpp"
#include "../registers/dacc_registers.hpp"
#include "../registers/efc_registers.hpp"
#include "../registers/fpu_registers.hpp"
#include "../registers/gmac_registers.hpp"
#include "../registers/gpbr_registers.hpp"
#include "../registers/hsmci_registers.hpp"
#include "../registers/i2sc0_registers.hpp"
#include "../registers/icm_registers.hpp"
#include "../registers/isi_registers.hpp"
#include "../registers/lockbit_registers.hpp"
#include "../registers/matrix_registers.hpp"
#include "../registers/mcan0_registers.hpp"
#include "../registers/mlb_registers.hpp"
#include "../registers/mpu_registers.hpp"
#include "../registers/nvic_registers.hpp"
#include "../registers/pioa_registers.hpp"
#include "../registers/pmc_registers.hpp"
#include "../registers/pwm0_registers.hpp"
#include "../registers/qspi_registers.hpp"
#include "../registers/rstc_registers.hpp"
#include "../registers/rswdt_registers.hpp"
#include "../registers/rtc_registers.hpp"
#include "../registers/rtt_registers.hpp"
#include "../registers/scb_registers.hpp"
#include "../registers/scnscb_registers.hpp"
#include "../registers/spi0_registers.hpp"
#include "../registers/ssc_registers.hpp"
#include "../registers/supc_registers.hpp"
#include "../registers/systick_registers.hpp"
#include "../registers/tc0_registers.hpp"
#include "../registers/trng_registers.hpp"
#include "../registers/twihs0_registers.hpp"
#include "../registers/uart0_registers.hpp"
#include "../registers/usart0_registers.hpp"
#include "../registers/usbhs_registers.hpp"
#include "../registers/utmi_registers.hpp"
#include "../registers/wdt_registers.hpp"
#include "../registers/xdmac_registers.hpp"

// ============================================================================
// Peripheral Bit Field Definitions (Family Level)
// ============================================================================

#include "../bitfields/acc_bitfields.hpp"
#include "../bitfields/aes_bitfields.hpp"
#include "../bitfields/afec0_bitfields.hpp"
#include "../bitfields/chipid_bitfields.hpp"
#include "../bitfields/dacc_bitfields.hpp"
#include "../bitfields/efc_bitfields.hpp"
#include "../bitfields/fpu_bitfields.hpp"
#include "../bitfields/gmac_bitfields.hpp"
#include "../bitfields/gpbr_bitfields.hpp"
#include "../bitfields/hsmci_bitfields.hpp"
#include "../bitfields/i2sc0_bitfields.hpp"
#include "../bitfields/icm_bitfields.hpp"
#include "../bitfields/isi_bitfields.hpp"
#include "../bitfields/lockbit_bitfields.hpp"
#include "../bitfields/matrix_bitfields.hpp"
#include "../bitfields/mcan0_bitfields.hpp"
#include "../bitfields/mlb_bitfields.hpp"
#include "../bitfields/mpu_bitfields.hpp"
#include "../bitfields/nvic_bitfields.hpp"
#include "../bitfields/pioa_bitfields.hpp"
#include "../bitfields/pmc_bitfields.hpp"
#include "../bitfields/pwm0_bitfields.hpp"
#include "../bitfields/qspi_bitfields.hpp"
#include "../bitfields/rstc_bitfields.hpp"
#include "../bitfields/rswdt_bitfields.hpp"
#include "../bitfields/rtc_bitfields.hpp"
#include "../bitfields/rtt_bitfields.hpp"
#include "../bitfields/scb_bitfields.hpp"
#include "../bitfields/scnscb_bitfields.hpp"
#include "../bitfields/spi0_bitfields.hpp"
#include "../bitfields/ssc_bitfields.hpp"
#include "../bitfields/supc_bitfields.hpp"
#include "../bitfields/systick_bitfields.hpp"
#include "../bitfields/tc0_bitfields.hpp"
#include "../bitfields/trng_bitfields.hpp"
#include "../bitfields/twihs0_bitfields.hpp"
#include "../bitfields/uart0_bitfields.hpp"
#include "../bitfields/usart0_bitfields.hpp"
#include "../bitfields/usbhs_bitfields.hpp"
#include "../bitfields/utmi_bitfields.hpp"
#include "../bitfields/wdt_bitfields.hpp"
#include "../bitfields/xdmac_bitfields.hpp"

// ============================================================================
// Enumerated Value Definitions
// ============================================================================

#include "enums.hpp"

// ============================================================================
// Pin Alternate Function Mappings
// ============================================================================

#include "pin_functions.hpp"

// ============================================================================
// Namespace Convenience Aliases
// ============================================================================

namespace alloy::hal::atmel::samv71::atsamv71n21b {

/// Main namespace alias for this MCU
///
/// Usage:
///   using namespace alloy::hal::atmel::samv71::atsamv71n21b;
///   // Now you can use rcc::RCC, gpio::GPIOA, etc.

}  // namespace alloy::hal::atmel::samv71::atsamv71n21b

// ============================================================================
// Global Namespace Aliases (Optional)
// ============================================================================

/// You can define shorter aliases if desired:
///
/// namespace mcu = alloy::hal::atmel::samv71::atsamv71n21b;
///
/// Then use:
///   mcu::rcc::RCC->CR = ...

// ============================================================================
// Generated File Summary
// ============================================================================
//
// This header includes:
//   - 42 peripheral register structures
//   - 42 peripheral bit field definitions
//   - Enumeration definitions
//   - Pin alternate function mappings
//
// Total peripherals with registers: 42
//
// For detailed documentation, see:
//   - REGISTER_USAGE.md (register access patterns)
//   - BITFIELD_USAGE.md (bit field operations)
//   - ENUM_USAGE.md (enumeration usage)
//   - PIN_FUNCTIONS_USAGE.md (pin configuration)
//
