/// Auto-generated register definitions for PADS_BANK0
/// Family: rp2040
/// Vendor: Raspberry Pi
///
/// DO NOT EDIT - Generated by Alloy Code Generator from CMSIS-SVD

#pragma once

#include <cstdint>

namespace alloy::hal::raspberrypi::rp2040::pads_bank0 {

// ============================================================================
// PADS_BANK0 - Peripheral Registers
// Base Address: 0x4001C000
// ============================================================================

/// PADS_BANK0 Register Structure
struct PADS_BANK0_Registers {
    /// Voltage select. Per bank control
    /// Offset: 0x0000
    /// Reset value: 0x00000000
    volatile uint32_t VOLTAGE_SELECT;

    /// Pad control register
    /// Offset: 0x0004
    /// Reset value: 0x00000056
    volatile uint32_t GPIO0;

    /// Pad control register
    /// Offset: 0x0008
    /// Reset value: 0x00000056
    volatile uint32_t GPIO1;

    /// Pad control register
    /// Offset: 0x000C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO2;

    /// Pad control register
    /// Offset: 0x0010
    /// Reset value: 0x00000056
    volatile uint32_t GPIO3;

    /// Pad control register
    /// Offset: 0x0014
    /// Reset value: 0x00000056
    volatile uint32_t GPIO4;

    /// Pad control register
    /// Offset: 0x0018
    /// Reset value: 0x00000056
    volatile uint32_t GPIO5;

    /// Pad control register
    /// Offset: 0x001C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO6;

    /// Pad control register
    /// Offset: 0x0020
    /// Reset value: 0x00000056
    volatile uint32_t GPIO7;

    /// Pad control register
    /// Offset: 0x0024
    /// Reset value: 0x00000056
    volatile uint32_t GPIO8;

    /// Pad control register
    /// Offset: 0x0028
    /// Reset value: 0x00000056
    volatile uint32_t GPIO9;

    /// Pad control register
    /// Offset: 0x002C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO10;

    /// Pad control register
    /// Offset: 0x0030
    /// Reset value: 0x00000056
    volatile uint32_t GPIO11;

    /// Pad control register
    /// Offset: 0x0034
    /// Reset value: 0x00000056
    volatile uint32_t GPIO12;

    /// Pad control register
    /// Offset: 0x0038
    /// Reset value: 0x00000056
    volatile uint32_t GPIO13;

    /// Pad control register
    /// Offset: 0x003C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO14;

    /// Pad control register
    /// Offset: 0x0040
    /// Reset value: 0x00000056
    volatile uint32_t GPIO15;

    /// Pad control register
    /// Offset: 0x0044
    /// Reset value: 0x00000056
    volatile uint32_t GPIO16;

    /// Pad control register
    /// Offset: 0x0048
    /// Reset value: 0x00000056
    volatile uint32_t GPIO17;

    /// Pad control register
    /// Offset: 0x004C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO18;

    /// Pad control register
    /// Offset: 0x0050
    /// Reset value: 0x00000056
    volatile uint32_t GPIO19;

    /// Pad control register
    /// Offset: 0x0054
    /// Reset value: 0x00000056
    volatile uint32_t GPIO20;

    /// Pad control register
    /// Offset: 0x0058
    /// Reset value: 0x00000056
    volatile uint32_t GPIO21;

    /// Pad control register
    /// Offset: 0x005C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO22;

    /// Pad control register
    /// Offset: 0x0060
    /// Reset value: 0x00000056
    volatile uint32_t GPIO23;

    /// Pad control register
    /// Offset: 0x0064
    /// Reset value: 0x00000056
    volatile uint32_t GPIO24;

    /// Pad control register
    /// Offset: 0x0068
    /// Reset value: 0x00000056
    volatile uint32_t GPIO25;

    /// Pad control register
    /// Offset: 0x006C
    /// Reset value: 0x00000056
    volatile uint32_t GPIO26;

    /// Pad control register
    /// Offset: 0x0070
    /// Reset value: 0x00000056
    volatile uint32_t GPIO27;

    /// Pad control register
    /// Offset: 0x0074
    /// Reset value: 0x00000056
    volatile uint32_t GPIO28;

    /// Pad control register
    /// Offset: 0x0078
    /// Reset value: 0x00000056
    volatile uint32_t GPIO29;

    /// Pad control register
    /// Offset: 0x007C
    /// Reset value: 0x000000DA
    volatile uint32_t SWCLK;

    /// Pad control register
    /// Offset: 0x0080
    /// Reset value: 0x0000005A
    volatile uint32_t SWD;
};

static_assert(sizeof(PADS_BANK0_Registers) >= 132, "PADS_BANK0_Registers size mismatch");

/// PADS_BANK0 peripheral instance
inline PADS_BANK0_Registers* PADS_BANK0() {
    return reinterpret_cast<PADS_BANK0_Registers*>(0x4001C000);
}

}  // namespace alloy::hal::raspberrypi::rp2040::pads_bank0
