/// Auto-generated peripheral definitions for STM32GBK1CBT6
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef ALLOY_GENERATED_STM32GBK1CBT6_PERIPHERALS_HPP
#define ALLOY_GENERATED_STM32GBK1CBT6_PERIPHERALS_HPP

#include <cstdint>

namespace alloy::generated::stm32gbk1cbt6 {

/// Basic peripheral base addresses
namespace peripherals {
    // Peripheral addresses will be added here
    // This is a minimal implementation
}

} // namespace alloy::generated::stm32gbk1cbt6

#endif // ALLOY_GENERATED_STM32GBK1CBT6_PERIPHERALS_HPP
