# ==============================================================================
# Board Manifest
# ==============================================================================
#
# Compact board metadata used by the descriptor-driven runtime path. The goal is
# to keep board selection data in one place instead of spreading it across large
# handwritten switches in the top-level build.
#

function(
    alloy_resolve_board_manifest
    BOARD_NAME
    OUT_FOUND
    OUT_BOARD_HEADER
    OUT_LINKER_SCRIPT
    OUT_VENDOR
    OUT_FAMILY
    OUT_DEVICE
    OUT_ARCH
    OUT_MCU
    OUT_FLASH_SIZE_BYTES
    OUT_SUPPORTS_PERIPHERAL_EXAMPLES
    OUT_SUPPORTS_UART_LOGGER
    OUT_SUPPORTS_DMA_PROBE
)
    set(_found FALSE)
    set(_board_header "")
    set(_linker_script "")
    set(_vendor "")
    set(_family "")
    set(_device "")
    set(_arch "")
    set(_mcu "")
    set(_flash_size_bytes 0)
    set(_supports_peripheral_examples FALSE)
    set(_supports_uart_logger FALSE)
    set(_supports_dma_probe FALSE)

    if(BOARD_NAME STREQUAL "host")
        set(_found TRUE)
        set(_board_header "boards/linux_host/board.hpp")
        set(_arch "native")
        set(_mcu "native")
        set(_flash_size_bytes 0)
    elseif(BOARD_NAME STREQUAL "nucleo_g071rb")
        set(_found TRUE)
        set(_board_header "boards/nucleo_g071rb/board.hpp")
        set(_linker_script "${CMAKE_SOURCE_DIR}/boards/nucleo_g071rb/STM32G071RBT6.ld")
        set(_vendor "st")
        set(_family "stm32g0")
        set(_device "stm32g071rb")
        set(_arch "cortex-m0plus")
        set(_mcu "STM32G071RBT6")
        set(_flash_size_bytes 131072)
        set(_supports_uart_logger TRUE)
        set(_supports_dma_probe TRUE)
    elseif(BOARD_NAME STREQUAL "nucleo_g0b1re")
        set(_found TRUE)
        set(_board_header "boards/nucleo_g0b1re/board.hpp")
        set(_linker_script "${CMAKE_SOURCE_DIR}/boards/nucleo_g0b1re/STM32G0B1RET6.ld")
        set(_vendor "st")
        set(_family "stm32g0")
        set(_device "stm32g0b1re")
        set(_arch "cortex-m0plus")
        set(_mcu "STM32G0B1RET6")
        set(_flash_size_bytes 524288)
        set(_supports_uart_logger TRUE)
    elseif(BOARD_NAME STREQUAL "nucleo_f401re")
        set(_found TRUE)
        set(_board_header "boards/nucleo_f401re/board.hpp")
        set(_linker_script "${CMAKE_SOURCE_DIR}/boards/nucleo_f401re/STM32F401RET6.ld")
        set(_vendor "st")
        set(_family "stm32f4")
        set(_device "stm32f401re")
        set(_arch "cortex-m4")
        set(_mcu "STM32F401RET6")
        set(_flash_size_bytes 524288)
        set(_supports_uart_logger TRUE)
        set(_supports_dma_probe TRUE)
    elseif(BOARD_NAME STREQUAL "same70_xpld" OR BOARD_NAME STREQUAL "same70_xplained")
        set(_found TRUE)
        set(_board_header "boards/same70_xplained/board.hpp")
        set(_linker_script "${CMAKE_SOURCE_DIR}/boards/same70_xplained/ATSAME70Q21.ld")
        set(_vendor "microchip")
        set(_family "same70")
        set(_device "atsame70q21b")
        set(_arch "cortex-m7")
        set(_mcu "ATSAME70Q21B")
        set(_flash_size_bytes 2097152)
        set(_supports_peripheral_examples TRUE)
        set(_supports_uart_logger TRUE)
        set(_supports_dma_probe TRUE)
    elseif(BOARD_NAME STREQUAL "raspberry_pi_pico")
        set(_found TRUE)
        set(_board_header "boards/raspberry_pi_pico/board.hpp")
        set(_linker_script "${CMAKE_SOURCE_DIR}/boards/raspberry_pi_pico/rp2040.ld")
        set(_vendor "raspberrypi")
        set(_family "rp2040")
        set(_device "pico")
        set(_arch "cortex-m0plus")
        set(_mcu "RP2040")
        set(_flash_size_bytes 2097152)
        set(_supports_uart_logger TRUE)
    elseif(BOARD_NAME STREQUAL "avr128da32_curiosity_nano")
        set(_found TRUE)
        set(_board_header "boards/avr128da32_curiosity_nano/board.hpp")
        set(_vendor "microchip")
        set(_family "avr-da")
        set(_device "avr128da32")
        set(_arch "avr")
        set(_mcu "AVR128DA32")
        set(_flash_size_bytes 131072)
        set(_supports_uart_logger TRUE)
    elseif(BOARD_NAME STREQUAL "esp32c3_devkitm")
        set(_found TRUE)
        set(_board_header "boards/esp32c3_devkitm/board.hpp")
        set(_vendor "espressif")
        set(_family "esp32c3")
        set(_device "esp32c3")
        set(_arch "riscv32")
        set(_mcu "ESP32-C3")
        set(_flash_size_bytes 4194304)
        set(_supports_uart_logger TRUE)
    elseif(BOARD_NAME STREQUAL "esp32s3_devkitc")
        set(_found TRUE)
        set(_board_header "boards/esp32s3_devkitc/board.hpp")
        set(_vendor "espressif")
        set(_family "esp32s3")
        set(_device "esp32s3")
        set(_arch "xtensa")
        set(_mcu "ESP32-S3")
        set(_flash_size_bytes 8388608)
        set(_supports_uart_logger TRUE)
    endif()

    set(${OUT_FOUND} "${_found}" PARENT_SCOPE)
    set(${OUT_BOARD_HEADER} "${_board_header}" PARENT_SCOPE)
    set(${OUT_LINKER_SCRIPT} "${_linker_script}" PARENT_SCOPE)
    set(${OUT_VENDOR} "${_vendor}" PARENT_SCOPE)
    set(${OUT_FAMILY} "${_family}" PARENT_SCOPE)
    set(${OUT_DEVICE} "${_device}" PARENT_SCOPE)
    set(${OUT_ARCH} "${_arch}" PARENT_SCOPE)
    set(${OUT_MCU} "${_mcu}" PARENT_SCOPE)
    set(${OUT_FLASH_SIZE_BYTES} "${_flash_size_bytes}" PARENT_SCOPE)
    set(${OUT_SUPPORTS_PERIPHERAL_EXAMPLES} "${_supports_peripheral_examples}" PARENT_SCOPE)
    set(${OUT_SUPPORTS_UART_LOGGER} "${_supports_uart_logger}" PARENT_SCOPE)
    set(${OUT_SUPPORTS_DMA_PROBE} "${_supports_dma_probe}" PARENT_SCOPE)
endfunction()
