/// Auto-generated peripheral definitions for STM32F303
/// Generated by Alloy SVD Code Generator
/// DO NOT EDIT - Regenerate from SVD if needed

#ifndef UCORE_GENERATED_STM32F303_PERIPHERALS_HPP
#define UCORE_GENERATED_STM32F303_PERIPHERALS_HPP

#include <cstdint>

namespace ucore::generated::stm32f303 {

/// Basic peripheral base addresses
namespace peripherals {
// Peripheral addresses will be added here
// This is a minimal implementation
}

}  // namespace ucore::generated::stm32f303

#endif  // ALLOY_GENERATED_STM32F303_PERIPHERALS_HPP
