/// Auto-generated startup code for STM32F745
/// Generated by Alloy Code Generator from CMSIS-SVD
///
/// Device:  STM32F745
/// Vendor:  STMicro
/// Family:  stm32f7
/// CPU:     CM7
///
/// DO NOT EDIT - Regenerate from SVD if needed

#include <cstdint>
#include <cstring>

// ============================================================================
// LINKER SCRIPT SYMBOLS
// ============================================================================

extern uint32_t _sidata;  // Start of .data section in flash
extern uint32_t _sdata;   // Start of .data section in RAM
extern uint32_t _edata;   // End of .data section in RAM
extern uint32_t _sbss;    // Start of .bss section
extern uint32_t _ebss;    // End of .bss section
extern uint32_t _estack;  // Stack top (defined in linker script)

// ============================================================================
// USER APPLICATION
// ============================================================================

extern "C" int main();

// System initialization (weak, can be overridden by user)
extern "C" void SystemInit() __attribute__((weak));
extern "C" void SystemInit() {}

// ============================================================================
// INTERRUPT HANDLERS
// ============================================================================

// Default handler for unhandled interrupts
extern "C" [[noreturn]] void Default_Handler() {
    // Trap - infinite loop if an unhandled interrupt occurs
    while (true) {
        __asm__ volatile("nop");
    }
}

// All interrupt handlers (weak, can be overridden by user)
extern "C" __attribute__((weak)) void WWDG_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void PVD_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TAMP_STAMP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void RTC_WKUP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void FLASH_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void RCC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI0_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream0_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream6_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void ADC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN1_TX_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN1_RX0_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN1_RX1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN1_SCE_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI9_5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM1_BRK_TIM9_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM1_UP_TIM10_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM1_TRG_COM_TIM11_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM1_CC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C1_EV_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C1_ER_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C2_EV_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C2_ER_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void USART1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void USART2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void USART3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void EXTI15_10_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void RTC_ALARM_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_FS_WKUP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM8_BRK_TIM12_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM8_UP_TIM13_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM8_TRG_COM_TIM14_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM8_CC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA1_Stream7_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void FMC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SDMMC1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void UART4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void UART5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM6_DAC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void TIM7_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream0_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream3_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void ETH_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void ETH_WKUP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN2_TX_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN2_RX0_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN2_RX1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CAN2_SCE_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_FS_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream6_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2_Stream7_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void USART6_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C3_EV_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C3_ER_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_HS_EP1_OUT_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_HS_EP1_IN_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_HS_WKUP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void OTG_HS_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DCMI_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void CRYP_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void HASH_RNG_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void FPU_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void UART7_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void UART8_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI4_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI5_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPI6_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SAI1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void LCD_TFT_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void LTDC_ER_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void DMA2D_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SAI2_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void QuadSPI_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void LPTimer1_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void HDMI_CEC_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C4_EV_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void I2C4_ER_Handler() {
    Default_Handler();
}
extern "C" __attribute__((weak)) void SPDIFRX_Handler() {
    Default_Handler();
}

// ============================================================================
// RESET HANDLER
// ============================================================================

extern "C" [[noreturn]] void Reset_Handler() {
    // 1. Copy initialized data from Flash to RAM (.data section)
    const uint32_t* src = &_sidata;
    uint32_t* dest = &_sdata;
    while (dest < &_edata) {
        *dest++ = *src++;
    }

    // 2. Zero-initialize uninitialized data (.bss section)
    dest = &_sbss;
    while (dest < &_ebss) {
        *dest++ = 0;
    }

    // 3. Call system initialization (clock setup, etc.)
    SystemInit();

    // 4. Call C++ static constructors
    extern void (*__init_array_start[])();
    extern void (*__init_array_end[])();
    for (auto* ctor = __init_array_start; ctor < __init_array_end; ++ctor) {
        (*ctor)();
    }

    // 5. Call main application
    main();

    // 6. If main returns, loop forever
    while (true) {
        __asm__ volatile("nop");
    }
}

// ============================================================================
// VECTOR TABLE
// ============================================================================

__attribute__((section(".isr_vector"), used))
void (* const vector_table[])() = {
    // Core system handlers
    reinterpret_cast<void (*)()>(&_estack), // Initial stack pointer
    Reset_Handler, // Reset handler
    WWDG_Handler, // IRQ 0: WWDG - Window Watchdog interrupt
    PVD_Handler, // IRQ 1: PVD - PVD through EXTI line detection INTERRUPT
    TAMP_STAMP_Handler, // IRQ 2: TAMP_STAMP - Tamper and TimeStamp interrupts through the
        EXTI line
    RTC_WKUP_Handler, // IRQ 3: RTC_WKUP - RTC Tamper or TimeStamp /CSS on LSE through
        EXTI line 19 interrupts
    FLASH_Handler, // IRQ 4: FLASH - Flash global interrupt
    RCC_Handler, // IRQ 5: RCC - RCC global interrupt
    EXTI0_Handler, // IRQ 6: EXTI0 - EXTI Line0 interrupt
    EXTI1_Handler, // IRQ 7: EXTI1 - EXTI Line1 interrupt
    EXTI2_Handler, // IRQ 8: EXTI2 - EXTI Line2 interrupt
    EXTI3_Handler, // IRQ 9: EXTI3 - EXTI Line3 interrupt
    EXTI4_Handler, // IRQ 10: EXTI4 - EXTI Line4 interrupt
    DMA1_Stream0_Handler, // IRQ 11: DMA1_Stream0 - DMA1 Stream0 global interrupt
    DMA1_Stream1_Handler, // IRQ 12: DMA1_Stream1 - DMA1 Stream1 global interrupt
    DMA1_Stream2_Handler, // IRQ 13: DMA1_Stream2 - DMA1 Stream2 global interrupt
    DMA1_Stream3_Handler, // IRQ 14: DMA1_Stream3 - DMA1 Stream3 global interrupt
    DMA1_Stream4_Handler, // IRQ 15: DMA1_Stream4 - DMA1 Stream4 global interrupt
    DMA1_Stream5_Handler, // IRQ 16: DMA1_Stream5 - DMA1 Stream5 global interrupt
    DMA1_Stream6_Handler, // IRQ 17: DMA1_Stream6 - DMA1 Stream6 global interrupt
    ADC_Handler, // IRQ 18: ADC - ADC1 global interrupt
    CAN1_TX_Handler, // IRQ 19: CAN1_TX - CAN1 TX interrupts
    CAN1_RX0_Handler, // IRQ 20: CAN1_RX0 - CAN1 RX0 interrupts
    CAN1_RX1_Handler, // IRQ 21: CAN1_RX1 - CAN1 RX1 interrupts
    CAN1_SCE_Handler, // IRQ 22: CAN1_SCE - CAN1 SCE interrupt
    EXTI9_5_Handler, // IRQ 23: EXTI9_5 - EXTI Line[9:5] interrupts
    TIM1_BRK_TIM9_Handler, // IRQ 24: TIM1_BRK_TIM9 - TIM1 Break interrupt and TIM9 global
        interrupt
    TIM1_UP_TIM10_Handler, // IRQ 25: TIM1_UP_TIM10 - TIM1 Update interrupt and TIM10 global interrupt
    TIM1_TRG_COM_TIM11_Handler, // IRQ 26: TIM1_TRG_COM_TIM11 - TIM1 Trigger and Commutation interrupts and
        TIM11 global interrupt
    TIM1_CC_Handler, // IRQ 27: TIM1_CC - TIM1 Capture Compare interrupt
    TIM2_Handler, // IRQ 28: TIM2 - TIM2 global interrupt
    TIM3_Handler, // IRQ 29: TIM3 - TIM3 global interrupt
    TIM4_Handler, // IRQ 30: TIM4 - TIM4 global interrupt
    I2C1_EV_Handler, // IRQ 31: I2C1_EV - I2C1 event interrupt
    I2C1_ER_Handler, // IRQ 32: I2C1_ER - I2C1 error interrupt
    I2C2_EV_Handler, // IRQ 33: I2C2_EV - I2C2 event interrupt
    I2C2_ER_Handler, // IRQ 34: I2C2_ER - I2C2 error interrupt
    SPI1_Handler, // IRQ 35: SPI1 - SPI1 global interrupt
    SPI2_Handler, // IRQ 36: SPI2 - SPI2 global interrupt
    USART1_Handler, // IRQ 37: USART1 - USART1 global interrupt
    USART2_Handler, // IRQ 38: USART2 - USART2 global interrupt
    USART3_Handler, // IRQ 39: USART3 - USART3 global interrupt
    EXTI15_10_Handler, // IRQ 40: EXTI15_10 - EXTI Line[15:10] interrupts
    RTC_ALARM_Handler, // IRQ 41: RTC_ALARM - RTC alarms through EXTI line 18
        interrupts
    OTG_FS_WKUP_Handler, // IRQ 42: OTG_FS_WKUP - USB On-The-Go FS Wakeup through EXTI line
        interrupt
    TIM8_BRK_TIM12_Handler, // IRQ 43: TIM8_BRK_TIM12 - TIM8 Break interrupt and TIM12 global
        interrupt
    TIM8_UP_TIM13_Handler, // IRQ 44: TIM8_UP_TIM13 - TIM8 Update interrupt and TIM13 global
        interrupt
    TIM8_TRG_COM_TIM14_Handler, // IRQ 45: TIM8_TRG_COM_TIM14 - TIM8 Trigger and Commutation interrupts and
        TIM14 global interrupt
    TIM8_CC_Handler, // IRQ 46: TIM8_CC - TIM8 Capture Compare interrupt
    DMA1_Stream7_Handler, // IRQ 47: DMA1_Stream7 - DMA1 Stream7 global interrupt
    FMC_Handler, // IRQ 48: FMC - FMC global interrupt
    SDMMC1_Handler, // IRQ 49: SDMMC1 - SDMMC1 global interrupt
    TIM5_Handler, // IRQ 50: TIM5 - TIM5 global interrupt
    SPI3_Handler, // IRQ 51: SPI3 - SPI3 global interrupt
    UART4_Handler, // IRQ 52: UART4 - UART4 global interrupt
    UART5_Handler, // IRQ 53: UART5 - UART5 global interrupt
    TIM6_DAC_Handler, // IRQ 54: TIM6_DAC - TIM6 global interrupt, DAC1 and DAC2 underrun
        error interrupt
    TIM7_Handler, // IRQ 55: TIM7 - TIM7 global interrupt
    DMA2_Stream0_Handler, // IRQ 56: DMA2_Stream0 - DMA2 Stream0 global interrupt
    DMA2_Stream1_Handler, // IRQ 57: DMA2_Stream1 - DMA2 Stream1 global interrupt
    DMA2_Stream2_Handler, // IRQ 58: DMA2_Stream2 - DMA2 Stream2 global interrupt
    DMA2_Stream3_Handler, // IRQ 59: DMA2_Stream3 - DMA2 Stream3 global interrupt
    DMA2_Stream4_Handler, // IRQ 60: DMA2_Stream4 - DMA2 Stream4 global interrupt
    ETH_Handler, // IRQ 61: ETH - Ethernet global interrupt
    ETH_WKUP_Handler, // IRQ 62: ETH_WKUP - Ethernet Wakeup through EXTI line
        interrupt
    CAN2_TX_Handler, // IRQ 63: CAN2_TX - CAN2 TX interrupts
    CAN2_RX0_Handler, // IRQ 64: CAN2_RX0 - CAN2 RX0 interrupts
    CAN2_RX1_Handler, // IRQ 65: CAN2_RX1 - CAN2 RX1 interrupts
    CAN2_SCE_Handler, // IRQ 66: CAN2_SCE - CAN2 SCE interrupt
    OTG_FS_Handler, // IRQ 67: OTG_FS - USB On The Go FS global
        interrupt
    DMA2_Stream5_Handler, // IRQ 68: DMA2_Stream5 - DMA2 Stream5 global interrupt
    DMA2_Stream6_Handler, // IRQ 69: DMA2_Stream6 - DMA2 Stream6 global interrupt
    DMA2_Stream7_Handler, // IRQ 70: DMA2_Stream7 - DMA2 Stream7 global interrupt
    USART6_Handler, // IRQ 71: USART6 - USART6 global interrupt
    I2C3_EV_Handler, // IRQ 72: I2C3_EV - I2C3 event interrupt
    I2C3_ER_Handler, // IRQ 73: I2C3_ER - I2C3 error interrupt
    OTG_HS_EP1_OUT_Handler, // IRQ 74: OTG_HS_EP1_OUT - USB On The Go HS End Point 1 Out global
        interrupt
    OTG_HS_EP1_IN_Handler, // IRQ 75: OTG_HS_EP1_IN - USB On The Go HS End Point 1 In global
        interrupt
    OTG_HS_WKUP_Handler, // IRQ 76: OTG_HS_WKUP - USB On The Go HS Wakeup through EXTI
        interrupt
    OTG_HS_Handler, // IRQ 77: OTG_HS - USB On The Go HS global
        interrupt
    DCMI_Handler, // IRQ 78: DCMI - DCMI global interrupt
    CRYP_Handler, // IRQ 79: CRYP - CRYP crypto global interrupt
    HASH_RNG_Handler, // IRQ 80: HASH_RNG - Hash and Rng global interrupt
    FPU_Handler, // IRQ 81: FPU - Floating point unit interrupt
    UART7_Handler, // IRQ 82: UART7 - UART7 global interrupt
    UART8_Handler, // IRQ 83: UART8 - UART 8 global interrupt
    SPI4_Handler, // IRQ 84: SPI4 - SPI 4 global interrupt
    SPI5_Handler, // IRQ 85: SPI5 - SPI 5 global interrupt
    SPI6_Handler, // IRQ 86: SPI6 - SPI 6 global interrupt
    SAI1_Handler, // IRQ 87: SAI1 - SAI1 global interrupt
    LCD_TFT_Handler, // IRQ 88: LCD_TFT - LTDC global interrupt
    LTDC_ER_Handler, // IRQ 89: LTDC_ER - LTDC Error global interrupt
    DMA2D_Handler, // IRQ 90: DMA2D - DMA2D global interrupt
    SAI2_Handler, // IRQ 91: SAI2 - SAI2 global interrupt
    QuadSPI_Handler, // IRQ 92: QuadSPI - QuadSPI global interrupt
    LPTimer1_Handler, // IRQ 93: LPTimer1 - LP Timer1 global interrupt
    HDMI_CEC_Handler, // IRQ 94: HDMI_CEC - HDMI-CEC global interrupt
    I2C4_EV_Handler, // IRQ 95: I2C4_EV - I2C4 event interrupt
    I2C4_ER_Handler, // IRQ 96: I2C4_ER - I2C4 Error interrupt
    SPDIFRX_Handler, // IRQ 97: SPDIFRX - SPDIFRX global interrupt
};
